# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: LazyOwn # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: grisuno # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom:
  - https://github.com/grisuno/LazyOwn
  - https://grisuno.github.io/LazyOwn/
  - https://www.reddit.com/r/LazyOwn/
  - https://web.facebook.com/profile.php?id=61560596232150
  - https://app.hackthebox.com/teams/overview/6429
  - https://app.hackthebox.com/users/1998024
  - https://github.com/grisuno/LazyOwn/archive/refs/tags/release/0.2.27.tar.gz

