name: hostdiscover
description: 'Ejecuta el script hostdiscover.sh que se encuentra en la carpeta modules.

  '
author: LazyOwn RedTeam
version: '1.0'
enabled: true
os: network
trigger: []
tool:
  name: hostdiscover
  repo_url: https://github.com/grisuno/LazyOwn.git
  install_path: modules/
  execute_command: cd .. && bash modules/hostdiscover.sh
category: 01. Reconnaissance
