name: LazyOwnExplorer
description: 'Ejecuta el script LazyOwnExplorer.py que se encuentra en la carpeta
  modules.

  '
author: LazyOwn RedTeam
version: '1.0'
enabled: true
os: any
trigger: []
tool:
  name: LazyOwnExplorer
  repo_url: https://github.com/grisuno/LazyOwn.git
  install_path: modules/
  execute_command: python3 LazyOwnExplorer.py
category: 12. Miscellaneous
