name: lazyownbt
description: 'LAzyOwn BlueTeam Framework, Detecta y reacciona a ataques, haredenización,
  integridad, etc.

  '
author: LazyOwn BlueTeam
version: '1.0'
enabled: true
os: any
trigger: []
tool:
  name: lazyownbt
  repo_url: https://github.com/grisuno/LazyOwnBT.git
  install_path: external/.exploit/LazyOwnBT
  install_command: bash install.sh
  execute_command: rlwrap --always-readline ./env/bin/python3 app.py
category: 12. Miscellaneous
