name: lazybinenc
description: 'Ejecuta el script lazybinenc.py que se encuentra en la carpeta modules.

  '
author: LazyOwn RedTeam
version: '1.0'
enabled: true
os: linux
trigger: []
tool:
  name: lazybinenc_tool
  repo_url: https://github.com/grisuno/LazyOwn.git
  install_path: modules/
  execute_command: python3 lazybinenc.py -i ../sessions/no_priv -o ../sessions/shellcode_enc.bin
category: 04. Post-Exploitation
