name: PrettyPrague
description: 'GenDigital Avast Antivirus ZeroDay Elevation of Privileges Vulnerability
  '
author: Nightmare_Eclipse
version: '1.0'
enabled: true
params:
- name: lhost
  type: string
  required: true
  description: lhost target.
os: windows
trigger: []
tool:
  name: PrettyPrague
  repo_url: https://git.churchofmalware.org/Nightmare_Eclipse/PrettyPrague.git
  install_path: external/.exploit/PrettyPrague
  install_command: git pull
  execute_command: cat README.md
category: 04. Post-Exploitation
