#!/usr/bin/env python
# -*- coding: utf-8 -*-
# This software must not be used by military or secret service organisations.
# License: TODO

import os, sys, argparse, json, glob, subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed
from libnmap.parser import NmapParser

greeter = '''[31m
 ██▓███  █     ████▄    █▄▄▄█████▓▒█████  ███▄ ▄███▓▄▄▄    ▄▄▄█████▓█████
 ▓██░  ██▓█░ █ ░███ ▀█   █▓  ██▒ ▓▒██▒  ██▓██▒▀█▀ ██▒████▄  ▓  ██▒ ▓▓█   ▀
 ▓██░ ██▓▒█░ █ ░▓██  ▀█ ██▒ ▓██░ ▒▒██░  ██▓██    ▓██▒██  ▀█▄▒ ▓██░ ▒▒███
 ▒██▄█▓▒ ░█░ █ ░▓██▒  ▐▌██░ ▓██▓ ░▒██   ██▒██    ▒██░██▄▄▄▄█░ ▓██▓ ░▒▓█  ▄
 ▒██▒ ░  ░░██▒██▒██░   ▓██░ ▒██▒ ░░ ████▓▒▒██▒   ░██▒▓█   ▓██▒▒██▒ ░░▒████▒
 ▒▓▒░ ░  ░ ▓░▒ ▒░ ▒░   ▒ ▒  ▒ ░░  ░ ▒░▒░▒░░ ▒░   ░  ░▒▒   ▓▒█░▒ ░░  ░░ ▒░ ░
 ░▒ ░      ▒ ░ ░░ ░░   ░ ▒░   ░     ░ ▒ ▒░░  ░      ░ ▒   ▒▒ ░  ░    ░ ░  ░
 ░░        ░   ░   ░   ░ ░  ░     ░ ░ ░ ▒ ░      ░    ░   ▒   ░        ░
             ░           ░            ░ ░        ░        ░  ░         ░  ░
[0m'''

cred_path = 'sessions/credentials.txt'
version = "0.0.33#beta" 

parser = argparse.ArgumentParser(description="pwntomate version " + version + "\nhttps://github.com/honze-net/pwntomate", epilog="This software must not be used by military or secret service organisations.", formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("xml", help="path to Nmap XML file")
parser.add_argument("-b", help="path to base directory for tool output (default: ~/.pwntomate)", default="~/.pwntomate", dest="basedir")
parser.add_argument("-t", help="path to custom tool directory (default: ./tools)", default="./tools", dest="tooldir")
parser.add_argument("-x", help="Executes the generated script automatically. (Be careful!)", action="store_true", dest="execute")
if len(sys.argv) == 1: # If no arguments are specified, print greeter, help and exit.
    print(greeter)
    parser.print_help()
    sys.exit(1)    
args = parser.parse_args()

try:
    report = NmapParser.parse_fromfile(args.xml)
except IOError:
    print('file %s not found' % args.xml)
    sys.exit(1)
shellscript = '''#!/bin/bash
# autogenerated script by pwntomate %s
# https://github.com/honze-net/pwntomate
''' % version

with open('payload.json', 'r') as file:
    config = json.load(file)
    rhost = config.get("rhost")
    domain = config.get("domain")
    dirworlist = config.get("dirworlist")

if os.path.exists(cred_path):
    with open(cred_path, 'r') as file:
        text_cred = file.read().strip()
        array_cred = text_cred.split(":")
        username = array_cred[0]
        password = f" -p '{array_cred[1]}' "
else:
    username = "deefbeef"
    password = ''

adomain = domain.split(".")
ext = adomain[1] if len(adomain) > 1 else adomain[0]
nameserver = adomain[0]

cmds = []
for host in report.hosts:
    for service in host.services:
        for filename in glob.glob(args.tooldir+"/*.tool"):
            tool = json.load(open(filename, 'r'))
            if tool["active"] and (service.service in tool["trigger"] or 'all' in tool["trigger"]):
                cmd = tool["command"]

                if service.tunnel == 'ssl':
                    cmd = cmd.replace("{s}", "s")
                else:
                    cmd = cmd.replace("{s}", "")
                    cmd = cmd.replace("{outputdir}", "{baseoutputdir}/{ip}/{port}/{toolname}") # make this configurable
                    cmd = cmd.replace("{ip}", host.address)
                    cmd = cmd.replace("{port}", str(service.port))
                    cmd = cmd.replace("{domain}", domain)
                    cmd = cmd.replace("{ext}", ext)
                    cmd = cmd.replace("{nameserver}", nameserver)
                    cmd = cmd.replace("{baseoutputdir}", args.basedir.replace(" ", "\ "))
                    cmd = cmd.replace("{toolname}", tool["toolname"].replace(" ", "\ "))
                    cmd = cmd.replace("{username}", username)
                    cmd = cmd.replace("{password}", password)
                    print(cmd)
                    mkdir_cmd = 'mkdir -p %s/%s/%s/%s' % (args.basedir.replace(" ", "\ "), host.address, service.port, tool["toolname"].replace(" ", "\ ")) # TODO remove double configuration of {baseoutputdir}/{ip}/{port}/{toolname}. things can go wrong.
                    shellscript += mkdir_cmd + '\n'
                    shellscript += '%s\n' % cmd
                    cmds.append('%s && %s' % (mkdir_cmd, cmd))
if args.execute:
    def _run_tool(cmd):
        return subprocess.run(cmd, shell=True, capture_output=True, text=True)

    with ThreadPoolExecutor(max_workers=4) as executor:
        futures = {executor.submit(_run_tool, cmd): cmd for cmd in cmds}
        for future in as_completed(futures):
            result = future.result()
    os.system("chown 1000:1000 sessions -R")
    os.system("chmod 755 sessions -R")
else:
    print(shellscript)
