# setup.py
from setuptools import setup, find_packages

setup(
    name="lazyown",
    version="1.0.0",
    description="LazyOwn Framework - Red Team & Post-Exploitation Tool",
    long_description=open("README.md", encoding="utf-8").read() if os.path.exists("README.md") else "",
    long_description_content_type="text/markdown",
    author="Gris Iscomeback",
    author_email="grisiscomeback@gmail.com",
    url="https://github.com/grisuno/LazyOwn",
    license="GPL-3.0-only",
    packages=[],
    py_modules=["lazyown"],
    entry_points={
        "console_scripts": [
            "lazyown = lazyown:main",
        ],
    },
    install_requires=[
        "requests",
        "cmd2",
        "python-libnmap",
        "pwncat-cs",
        "pwn",
        "groq",
        "PyPDF2",
        "docx",
        "python-docx",
        "olefile",
        "exifread",
        "pycryptodome",
        "impacket",
        "pandas",
        "colorama",
        "tabulate",
        "pyarrow",
        "keyboard",
        "flask-unsign",
        "name-that-hash",
        "certipy-ad",
        "ast",
        "pykeepass",
        "Pillow",
        "netaddr",
        "stix2",
        "pyautogui",
        "networkx",
        "pyvis",
        "markdown",
        "scapy",
        "watchdog",
        "flask-login",
        "instal flask-wtf",
        "bcrypt",
        "pyyaml",
        "bs4",
        "dnslib",
        "python-telegram-bot",
        "nest_asyncio",
        "rich",
        "flask_socketio",
        "autobloody",
        "minikerberos",
        "tinydb",
        "msldap",
        "prettytable",
        "fire",
        "wget",
        "pypykatz",
        "donut",
        "uro",
        "lupa",
        "flask_sock",
        "donut-shellcode",
        "flask_limiter",
        "aiosmtpd",
        "yagmail",
        "validators",
        "ua_parser",
        "pdf2image",
        "python-magic",
        "packaging",
    ],
    python_requires=">=3.8",
    include_package_data=True,
    zip_safe=False,
)