"""Integration tests for dashboard_bp loot and timeline routes."""
from __future__ import annotations

import csv
import json
import os
from pathlib import Path

import pytest
from flask import Flask

from modules.dashboard_bp import dashboard_bp


@pytest.fixture
def client(tmp_path: Path):
    """Create a Flask test client with dashboard_bp registered and tmp_path as sessions dir."""
    import modules.dashboard_bp as bp_module

    bp_module._SESSIONS_DIR = tmp_path
    app = Flask(__name__)
    app.config["TESTING"] = True
    app.register_blueprint(dashboard_bp)
    return app.test_client(), tmp_path


def _write_credentials_file(sessions_dir: Path, filename: str, lines: list[str]) -> None:
    (sessions_dir / filename).write_text("\n".join(lines))


def _write_hashes_file(sessions_dir: Path, filename: str, lines: list[str]) -> None:
    (sessions_dir / filename).write_text("\n".join(lines))


def _write_loot_file(sessions_dir: Path, rel_path: str, content: str) -> None:
    loot_dir = sessions_dir / "loot"
    loot_dir.mkdir(parents=True, exist_ok=True)
    (loot_dir / rel_path).parent.mkdir(parents=True, exist_ok=True)
    (loot_dir / rel_path).write_text(content)


def _write_csv_report(sessions_dir: Path, rows: list[dict]) -> None:
    headers = ["start", "command", "duration_ms", "destination_ip"]
    with (sessions_dir / "LazyOwn_session_report.csv").open("w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=headers)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def _write_events_jsonl(sessions_dir: Path, events: list[dict]) -> None:
    with (sessions_dir / "events.jsonl").open("w") as fh:
        for ev in events:
            fh.write(json.dumps(ev) + "\n")


class TestLootRoute:
    """Tests for GET /dashboard/loot."""

    def test_loot_route_returns_200_with_data(self, client: tuple):
        """Loot page returns 200 when credentials, hashes, and loot files exist."""
        test_client, tmp_path = client
        _write_credentials_file(tmp_path, "credentials_test.txt", [
            "admin:test123",
            "root:toor",
        ])
        _write_hashes_file(tmp_path, "hash_test.txt", [
            "admin:5f4dcc3b5aa765d61d8327deb882cf99",
            "Administrator:aad3b435b51404eeaad3b435b51404ee:8846f7eaee8fb117ad06bdd830b7586c",
        ])
        _write_loot_file(tmp_path, "browser/edge_passwords.txt", "https://target.local,admin,pass123\n")

        resp = test_client.get("/dashboard/loot")
        assert resp.status_code == 200
        html = resp.data.decode()
        assert "admin:test123" in html
        assert "root:toor" in html
        assert "5f4dcc3b5aa765d61d8327deb882cf99" in html
        assert "edge_passwords.txt" in html

    def test_loot_empty_returns_200(self, client: tuple):
        """Loot page returns 200 with empty state when no loot files exist."""
        test_client, tmp_path = client
        resp = test_client.get("/dashboard/loot")
        assert resp.status_code == 200
        html = resp.data.decode()
        assert "No credentials captured yet." in html
        assert "No hashes captured yet." in html
        assert "No loot files yet." in html

    def test_loot_skips_comment_lines(self, client: tuple):
        """Loot page skips lines starting with # in credential and hash files."""
        test_client, tmp_path = client
        _write_credentials_file(tmp_path, "credentials.txt", [
            "# Generated by LazyOwn",
            "svc_backup:Backup2024!",
            "# End of file",
            "sa:SqlS3rv3r!",
        ])
        _write_hashes_file(tmp_path, "hashes.txt", [
            "# LM:NTLM format below",
            "Guest:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0",
        ])

        resp = test_client.get("/dashboard/loot")
        assert resp.status_code == 200
        html = resp.data.decode()
        assert "svc_backup:Backup2024!" in html
        assert "sa:SqlS3rv3r!" in html
        assert "Guest:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0" in html
        assert "# Generated by LazyOwn" not in html
        assert "# LM:NTLM format below" not in html

    def test_loot_respects_max_entries(self, client: tuple):
        """Loot page caps entries at _LOOT_MAX_ENTRIES (500)."""
        import modules.dashboard_bp as bp_module

        test_client, tmp_path = client
        original_max = bp_module._LOOT_MAX_ENTRIES
        bp_module._LOOT_MAX_ENTRIES = 5
        try:
            _write_credentials_file(tmp_path, "credentials.txt", [f"user{i}:pass{i}" for i in range(10)])
            resp = test_client.get("/dashboard/loot")
            assert resp.status_code == 200
            html = resp.data.decode()
            assert html.count("credentials.txt") == 5
            assert "user9" not in html
        finally:
            bp_module._LOOT_MAX_ENTRIES = original_max

    def test_loot_multiple_credential_files(self, client: tuple):
        """Loot page aggregates all credential*.txt glob matches."""
        test_client, tmp_path = client
        _write_credentials_file(tmp_path, "credentials_domain.txt", ["DOMAIN\\admin:Secret123"])
        _write_credentials_file(tmp_path, "credentials_local.txt", ["localadmin:LocalP@ss"])
        _write_credentials_file(tmp_path, "credentials_smb.txt", ["svc_sql:P@ssw0rd"])

        resp = test_client.get("/dashboard/loot")
        assert resp.status_code == 200
        html = resp.data.decode()
        assert "DOMAIN\\admin:Secret123" in html
        assert "localadmin:LocalP@ss" in html
        assert "svc_sql:P@ssw0rd" in html


class TestTimelineRoute:
    """Tests for GET /dashboard/timeline."""

    def test_timeline_route_returns_200_with_data(self, client: tuple):
        """Timeline page returns 200 when CSV report and events exist."""
        test_client, tmp_path = client
        _write_csv_report(tmp_path, [
            {"start": "1735689600.0", "command": "nmap -sV 10.0.0.1", "duration_ms": "4250", "destination_ip": "10.0.0.1"},
            {"start": "1735689700.0", "command": "smbclient //10.0.0.1/share", "duration_ms": "1200", "destination_ip": "10.0.0.1"},
        ])
        _write_events_jsonl(tmp_path, [
            {"timestamp": "1735689650.0", "event_type": "vuln_found", "suggest": "SMB signing disabled on 10.0.0.1", "severity": "high"},
            {"timestamp": "1735689750.0", "event_type": "credential_captured", "detail": "NetNTLMv2 hash from 10.0.0.1", "severity": "info"},
        ])

        resp = test_client.get("/dashboard/timeline")
        assert resp.status_code == 200
        html = resp.data.decode()
        assert "nmap -sV 10.0.0.1" in html
        assert "smbclient //10.0.0.1/share" in html
        assert "command" in html.lower()
        assert "vuln_found" in html
        assert "credential_captured" in html

    def test_timeline_empty_returns_200(self, client: tuple):
        """Timeline page returns 200 with empty state when no data files exist."""
        test_client, tmp_path = client
        resp = test_client.get("/dashboard/timeline")
        assert resp.status_code == 200
        html = resp.data.decode()
        assert "No timeline entries yet" in html

    def test_timeline_sorted_newest_first(self, client: tuple):
        """Timeline entries are sorted by timestamp descending (newest first)."""
        test_client, tmp_path = client
        _write_csv_report(tmp_path, [
            {"start": "1735689400.0", "command": "early_command", "duration_ms": "100", "destination_ip": ""},
        ])
        _write_events_jsonl(tmp_path, [
            {"timestamp": "1735689500.0", "event_type": "later_event", "detail": "happened later", "severity": "info"},
        ])

        resp = test_client.get("/dashboard/timeline")
        assert resp.status_code == 200
        html = resp.data.decode()
        later_pos = html.find("later_event")
        early_pos = html.find("early_command")
        assert later_pos < early_pos, "Newer event should appear before older command"

    def test_timeline_handles_csv_tool_column(self, client: tuple):
        """Timeline CSV reader uses the 'tool' column as fallback for 'command'."""
        test_client, tmp_path = client
        _write_csv_report(tmp_path, [
            {"start": "1735689600.0", "command": "", "duration_ms": "500", "destination_ip": "10.0.0.5"},
        ])
        resp = test_client.get("/dashboard/timeline")
        assert resp.status_code == 200

    def test_timeline_csv_without_timestamp(self, client: tuple):
        """Timeline skips CSV rows that have no command/tool value."""
        test_client, tmp_path = client
        with (tmp_path / "LazyOwn_session_report.csv").open("w", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=["start", "command", "duration_ms", "destination_ip"])
            writer.writeheader()
            writer.writerow({"start": "1735689600.0", "command": "", "duration_ms": "500", "destination_ip": "10.0.0.5"})
            writer.writerow({"start": "1735689700.0", "command": "valid_command", "duration_ms": "200", "destination_ip": ""})

        resp = test_client.get("/dashboard/timeline")
        assert resp.status_code == 200
        html = resp.data.decode()
        assert "valid_command" in html

    def test_timeline_respects_max_rows(self, client: tuple):
        """Timeline caps at _TIMELINE_MAX_ROWS (200)."""
        import modules.dashboard_bp as bp_module

        test_client, tmp_path = client
        original_max = bp_module._TIMELINE_MAX_ROWS
        bp_module._TIMELINE_MAX_ROWS = 3
        try:
            _write_csv_report(tmp_path, [
                {"start": f"173568900{i}.0", "command": f"cmd_{i}", "duration_ms": "100", "destination_ip": ""}
                for i in range(10)
            ])
            resp = test_client.get("/dashboard/timeline")
            assert resp.status_code == 200
            html = resp.data.decode()
            assert html.count('<td class="kind-command">') == 3
        finally:
            bp_module._TIMELINE_MAX_ROWS = original_max

    def test_timeline_normalizes_iso_timestamps(self, client: tuple):
        """Timeline normalizes ISO-format timestamps from events."""
        test_client, tmp_path = client
        _write_events_jsonl(tmp_path, [
            {"timestamp": "2026-01-15T14:30:00", "event_type": "recon_started", "detail": "Scan initiated", "severity": "info"},
        ])

        resp = test_client.get("/dashboard/timeline")
        assert resp.status_code == 200
        html = resp.data.decode()
        assert "recon_started" in html
        assert "2026-01-15T14:30:00" in html

    def test_timeline_only_events_no_csv(self, client: tuple):
        """Timeline works when only events.jsonl exists (no CSV report)."""
        test_client, tmp_path = client
        _write_events_jsonl(tmp_path, [
            {"timestamp": "1735689600.0", "event_type": "session_start", "detail": "LazyOwn started", "severity": "info"},
        ])

        resp = test_client.get("/dashboard/timeline")
        assert resp.status_code == 200
        html = resp.data.decode()
        assert "session_start" in html
        assert "LazyOwn started" in html

    def test_timeline_only_csv_no_events(self, client: tuple):
        """Timeline works when only CSV report exists (no events.jsonl)."""
        test_client, tmp_path = client
        _write_csv_report(tmp_path, [
            {"start": "1735689600.0", "command": "whoami /all", "duration_ms": "50", "destination_ip": "10.0.0.7"},
        ])

        resp = test_client.get("/dashboard/timeline")
        assert resp.status_code == 200
        html = resp.data.decode()
        assert "whoami /all" in html

    def test_timeline_handles_malformed_jsonl(self, client: tuple):
        """Timeline gracefully skips malformed JSONL lines."""
        test_client, tmp_path = client
        (tmp_path / "events.jsonl").write_text(
            '{"timestamp": "1735689600.0", "event_type": "good", "detail": "valid", "severity": "info"}\n'
            'this is not json\n'
            '{"timestamp": "1735689700.0", "event_type": "also_good", "detail": "valid too", "severity": "info"}\n'
        )

        resp = test_client.get("/dashboard/timeline")
        assert resp.status_code == 200
        html = resp.data.decode()
        assert "good" in html
        assert "also_good" in html


class TestDashboardIndexRoute:
    """Sanity tests for the main dashboard index route."""

    def test_dashboard_index_returns_200(self, client: tuple):
        """Main dashboard page returns 200."""
        test_client, tmp_path = client
        resp = test_client.get("/dashboard/")
        assert resp.status_code == 200
        assert "LazyOwn SOC Dashboard" in resp.data.decode()

    def test_dashboard_api_data_returns_json(self, client: tuple):
        """API data endpoint returns valid JSON with expected keys."""
        test_client, tmp_path = client
        resp = test_client.get("/dashboard/api/data")
        assert resp.status_code == 200
        data = resp.get_json()
        assert "generated_at" in data
        assert "beacon_count" in data
        assert "hosts_discovered" in data
        assert "credentials_found" in data
        assert "recent_events" in data
        assert "tactic_counts" in data
