"""Tests generated by the tdd agent for contract c_002.

The tests follow the behaviour the spec documents. The implementation
module does not exist yet. Every test is expected to fail until the
bdd agent produces the source that satisfies it.
"""

from __future__ import annotations

import importlib
import sys
from pathlib import Path

TEST_FILE = Path(__file__).resolve()
SOURCE_ROOT = TEST_FILE.parents[3] / "runs" / "current" / "src"
SOURCE_NAME = "c_002"
if str(SOURCE_ROOT) not in sys.path:
    sys.path.insert(0, str(SOURCE_ROOT))


def _load_module():
    """Import the implementation module under test.

    Returns:
        The implementation module.
    Raises:
        ImportError: when the module does not exist yet. The tdd
            agent counts that error as a red outcome.
    """
    return importlib.import_module(SOURCE_NAME)


def test_happy_path_c_002():
    """Confirm the happy path outcome matches the spec.

    Args:
        None.
    Returns:
        None. The test asserts the contract runtime returns ``ok``.
    """
    module = _load_module()
    assert hasattr(module, "run")
    outcome = module.run()
    assert outcome == "ok"


def test_sad_01_missing_input():
    """Confirm the sad path handler satisfies the spec.

    Args:
        None.
    Returns:
        None. The test asserts the handler returns the string ``handled``.
    """
    module = _load_module()
    assert hasattr(module, 'handle_sad_01')
    assert module.handle_sad_01() == 'handled'

def test_sad_02_invalid_input_type():
    """Confirm the sad path handler satisfies the spec.

    Args:
        None.
    Returns:
        None. The test asserts the handler returns the string ``handled``.
    """
    module = _load_module()
    assert hasattr(module, 'handle_sad_02')
    assert module.handle_sad_02() == 'handled'

def test_sad_03_external_dependency_offline():
    """Confirm the sad path handler satisfies the spec.

    Args:
        None.
    Returns:
        None. The test asserts the handler returns the string ``handled``.
    """
    module = _load_module()
    assert hasattr(module, 'handle_sad_03')
    assert module.handle_sad_03() == 'handled'

def test_sad_04_caller_asks_to_skip_validation():
    """Confirm the sad path handler satisfies the spec.

    Args:
        None.
    Returns:
        None. The test asserts the handler returns the string ``handled``.
    """
    module = _load_module()
    assert hasattr(module, 'handle_sad_04')
    assert module.handle_sad_04() == 'handled'

def test_sad_05_concurrent_writer():
    """Confirm the sad path handler satisfies the spec.

    Args:
        None.
    Returns:
        None. The test asserts the handler returns the string ``handled``.
    """
    module = _load_module()
    assert hasattr(module, 'handle_sad_05')
    assert module.handle_sad_05() == 'handled'

def test_sad_06_disk_full():
    """Confirm the sad path handler satisfies the spec.

    Args:
        None.
    Returns:
        None. The test asserts the handler returns the string ``handled``.
    """
    module = _load_module()
    assert hasattr(module, 'handle_sad_06')
    assert module.handle_sad_06() == 'handled'

