"""Post-scan side effects executed at the tail of ``do_lazynmap``.

Three artefacts are produced after every successful scan:

1. ``sessions/recon_plan_<target>.md`` — operator + LLM-readable plan
   generated by :func:`cli.recon_plan.build_recon_plan`.
2. ``sessions/world_model.json`` — phase bumped to ``enum`` so the
   daemon / autonomous loop / status bar agree we have just transitioned
   past pure recon.
3. ``sessions/autonomous_events.jsonl`` — one ``lazynmap.recon_plan``
   event so MCP consumers (``lazyown_poll_events`` and the dashboard)
   see the transition.

Every step is best-effort: failure in one branch must not block the
others or propagate back into :class:`LazyOwnShell`. The implementation
is pure Python (no ``cmd2``, ``rich`` or ``flask`` imports) so the suite
can exercise it with hand-rolled fixtures.
"""

from __future__ import annotations

import json
import os
import tempfile
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Mapping

from cli.exploration import (
    ExplorationConfig,
    ExplorationEngine,
    resolve_current_os,
)
from cli.recon_plan import (
    ReconPlan,
    ReconPlanConfig,
    build_recon_plan,
    render_rich,
    write_plan,
)

_DEFAULT_ENABLED_KEY = "enable_recon_plan"
_DEFAULT_WORLD_MODEL_FILE = "world_model.json"
_DEFAULT_EVENTS_FILE = "autonomous_events.jsonl"
_DEFAULT_PHASE = "enum"
_DEFAULT_EVENT_KIND = "lazynmap.recon_plan"
_DEFAULT_EVENT_SEVERITY = "info"
_FILE_MODE = 0o600
_TRUTHY = ("1", "true", "yes", "on")
_FALSY = ("0", "false", "no", "off")


@dataclass(frozen=True)
class PostScanConfig:
    """Immutable configuration for :func:`run_post_scan`.

    Every default mirrors a key already documented in ``CLAUDE.md`` so
    the operator can adjust behaviour via ``payload.json`` without
    touching code.
    """

    sessions_dir: str = "sessions"
    enabled_key: str = _DEFAULT_ENABLED_KEY
    world_model_file: str = _DEFAULT_WORLD_MODEL_FILE
    events_file: str = _DEFAULT_EVENTS_FILE
    phase: str = _DEFAULT_PHASE
    event_kind: str = _DEFAULT_EVENT_KIND
    event_severity: str = _DEFAULT_EVENT_SEVERITY
    file_mode: int = _FILE_MODE


@dataclass(frozen=True)
class PostScanResult:
    """Structured outcome of :func:`run_post_scan`.

    Attributes:
        skipped: ``True`` when the operator toggled the feature off.
        plan: The generated :class:`ReconPlan`, or ``None`` on failure.
        plan_path: Filesystem path the plan was written to, when any.
        world_model_updated: ``True`` when the phase write succeeded.
        event_emitted: ``True`` when the events.jsonl append succeeded.
    """

    skipped: bool
    plan: ReconPlan | None
    plan_path: str | None
    world_model_updated: bool
    event_emitted: bool


def run_post_scan(
    target: str,
    payload: Mapping[str, Any],
    console: Any = None,
    config: PostScanConfig | None = None,
    engine_factory: Callable[[], ExplorationEngine] | None = None,
    plan_config: ReconPlanConfig | None = None,
    clock: Callable[[], float] | None = None,
) -> PostScanResult:
    """Generate the plan, bump the world model and emit an event.

    Args:
        target: Host the scan was performed on.
        payload: ``payload.json`` mapping. Used to resolve the active
            platform and the ``enable_recon_plan`` toggle.
        console: Optional duck-typed console (``rich.console.Console``
            compatible). When ``None`` the plan is still written to
            disk; only the inline preview is suppressed.
        config: Optional :class:`PostScanConfig` override.
        engine_factory: Zero-arg callable returning an
            :class:`ExplorationEngine`. Defaults to one wired against
            ``cfg.sessions_dir`` and the payload-resolved OS.
        plan_config: Optional :class:`ReconPlanConfig` override.
        clock: Zero-arg callable returning epoch seconds.

    Returns:
        A :class:`PostScanResult` summarising what was produced. The
        function never raises — every error path is logged via
        ``console.print`` and recorded as ``False`` in the result.
    """
    cfg = config or PostScanConfig()
    clock_fn = clock or time.time
    if not _enabled(payload, cfg):
        return PostScanResult(
            skipped=True,
            plan=None,
            plan_path=None,
            world_model_updated=False,
            event_emitted=False,
        )
    plan: ReconPlan | None = None
    plan_path: Path | None = None
    try:
        engine = engine_factory() if engine_factory else _default_engine_factory(payload, cfg)
        plan = build_recon_plan(
            target=target,
            engine=engine,
            payload=payload,
            config=plan_config or ReconPlanConfig(sessions_dir=cfg.sessions_dir),
            clock=clock_fn,
        )
        plan_path = write_plan(plan, sessions_dir=cfg.sessions_dir)
        if console is not None:
            try:
                render_rich(plan, console)
            except Exception as exc:
                _safe_log(console, f"recon plan render failed: {exc}")
    except Exception as exc:
        _safe_log(console, f"recon plan generation failed: {exc}")
    world_model_updated = _update_world_model_phase(cfg, target, clock_fn)
    event_emitted = _emit_event(cfg, target, plan, plan_path, clock_fn)
    return PostScanResult(
        skipped=False,
        plan=plan,
        plan_path=str(plan_path) if plan_path else None,
        world_model_updated=world_model_updated,
        event_emitted=event_emitted,
    )


def _enabled(payload: Mapping[str, Any], cfg: PostScanConfig) -> bool:
    """Return the resolved value of the recon-plan toggle."""
    raw = payload.get(cfg.enabled_key, True)
    if isinstance(raw, bool):
        return raw
    if isinstance(raw, (int, float)):
        return bool(raw)
    if isinstance(raw, str):
        token = raw.strip().lower()
        if token in _TRUTHY:
            return True
        if token in _FALSY:
            return False
    return True


def _default_engine_factory(
    payload: Mapping[str, Any],
    cfg: PostScanConfig,
) -> ExplorationEngine:
    expl = ExplorationConfig(sessions_dir=cfg.sessions_dir)
    return ExplorationEngine(config=expl, current_os=resolve_current_os(payload))


def _update_world_model_phase(
    cfg: PostScanConfig,
    target: str,
    clock_fn: Callable[[], float],
) -> bool:
    sessions = Path(cfg.sessions_dir)
    try:
        sessions.mkdir(parents=True, exist_ok=True)
    except OSError:
        return False
    wm_path = sessions / cfg.world_model_file
    data: dict[str, Any] = {}
    if wm_path.exists():
        try:
            loaded = json.loads(wm_path.read_text(encoding="utf-8"))
            if isinstance(loaded, dict):
                data = loaded
        except (OSError, json.JSONDecodeError):
            data = {}
    data["phase"] = cfg.phase
    data["target"] = target
    data["phase_updated_at"] = clock_fn()
    return _atomic_write_json(wm_path, data, cfg.file_mode)


def _emit_event(
    cfg: PostScanConfig,
    target: str,
    plan: ReconPlan | None,
    plan_path: Path | None,
    clock_fn: Callable[[], float],
) -> bool:
    sessions = Path(cfg.sessions_dir)
    try:
        sessions.mkdir(parents=True, exist_ok=True)
    except OSError:
        return False
    record = {
        "id": uuid.uuid4().hex[:12],
        "ts": clock_fn(),
        "type": cfg.event_kind,
        "severity": cfg.event_severity,
        "payload": {
            "target": target,
            "plan_path": str(plan_path) if plan_path else None,
            "item_count": len(plan.items) if plan is not None else 0,
            "service_count": len(plan.services) if plan is not None else 0,
            "phase": cfg.phase,
        },
    }
    try:
        encoded = json.dumps(record, ensure_ascii=False, default=str) + "\n"
    except (TypeError, ValueError):
        return False
    events_path = sessions / cfg.events_file
    try:
        fd = os.open(
            str(events_path),
            os.O_WRONLY | os.O_CREAT | os.O_APPEND,
            cfg.file_mode,
        )
    except OSError:
        return False
    try:
        os.write(fd, encoded.encode("utf-8"))
    except OSError:
        return False
    finally:
        try:
            os.close(fd)
        except OSError:
            pass
    return True


def _atomic_write_json(path: Path, data: Mapping[str, Any], mode: int) -> bool:
    try:
        encoded = json.dumps(data, ensure_ascii=False, indent=2, default=str)
    except (TypeError, ValueError):
        return False
    try:
        fd, tmp = tempfile.mkstemp(
            prefix=f".{path.name}.",
            suffix=".tmp",
            dir=str(path.parent),
        )
    except OSError:
        return False
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(encoded)
        os.chmod(tmp, mode)
        os.replace(tmp, path)
    except OSError:
        if os.path.exists(tmp):
            try:
                os.unlink(tmp)
            except OSError:
                pass
        return False
    return True


def _safe_log(console: Any, message: str) -> None:
    if console is None:
        return
    try:
        console.print(f"[dim]{message}[/]")
    except Exception:
        pass


__all__ = ["PostScanConfig", "PostScanResult", "run_post_scan"]
