"""Read-only loader for ``cli/command_index.json``.

The CLI palette command, the C2 ``/palette`` endpoint and the MCP
``lazyown_palette`` tool all consume the same on-disk JSON document
generated by ``scripts/build_command_index.py``. This module exposes a tiny,
zero-dependency API so each surface stays in sync.

The loader is deliberately minimal: it parses the JSON once per process,
caches the result, and offers ergonomic filters. The catalogue is treated
as data — never mutated in place — so callers can safely share the cached
object across threads.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INDEX_PATH = REPO_ROOT / "cli" / "command_index.json"


class CommandIndexError(RuntimeError):
    """Raised when the on-disk index is missing or malformed."""


@lru_cache(maxsize=8)
def load_index(path: str | None = None) -> dict[str, Any]:
    """Return the parsed catalogue as a dict.

    Args:
        path: Override the default index location. ``None`` uses
            :data:`DEFAULT_INDEX_PATH`.

    Returns:
        The full document with keys ``schema_version``, ``totals``,
        ``commands``, ``phase_to_commands`` and ``category_to_commands``.

    Raises:
        CommandIndexError: when the file is missing or unparseable.
    """
    target = Path(path) if path is not None else DEFAULT_INDEX_PATH
    if not target.exists():
        raise CommandIndexError(
            f"Command index not found at {target}. Run 'python3 scripts/build_command_index.py' to generate it."
        )
    try:
        return json.loads(target.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise CommandIndexError(f"Invalid JSON in {target}: {exc}") from exc


def all_commands(*, include_duplicates: bool = False) -> list[dict[str, Any]]:
    """Return every command entry, sorted by name.

    Args:
        include_duplicates: When ``False`` (default), shadowed duplicate
            definitions are filtered out — only the canonical entry remains
            for each name. Set to ``True`` to inspect the raw method-level
            list (useful for the ``/duplicates`` audit view).
    """
    doc = load_index()
    rows = list(doc.get("commands", []))
    if not include_duplicates:
        rows = [c for c in rows if c.get("duplicate_of") is None]
    rows.sort(key=lambda c: c["name"])
    return rows


def all_phases() -> list[str]:
    """Return the sorted list of phase identifiers present in the index."""
    return sorted(load_index().get("phase_to_commands", {}).keys())


def all_categories() -> list[str]:
    """Return the sorted list of cmd2 category labels present in the index."""
    return sorted(load_index().get("category_to_commands", {}).keys())


def filter_by_phase(phase: str) -> list[dict[str, Any]]:
    """Return command entries whose ``phase`` matches ``phase``.

    Unknown phases yield an empty list instead of raising — the palette UI
    is meant to be tolerant.
    """
    target = phase.strip().lower()
    return [c for c in all_commands() if c["phase"] == target]


def filter_by_category(category: str) -> list[dict[str, Any]]:
    """Return command entries with the given cmd2 category label."""
    return [c for c in all_commands() if c.get("category") == category]


def search(query: str, *, limit: int | None = None) -> list[dict[str, Any]]:
    """Substring search over ``name`` and ``summary`` (case-insensitive).

    Args:
        query: Free-form search term. An empty string returns the full list
            (capped by ``limit`` if provided).
        limit: Optional cap on the result count.
    """
    needle = query.strip().lower()
    rows = all_commands()
    if needle:
        rows = [c for c in rows if needle in c["name"].lower() or needle in (c.get("summary") or "").lower()]
    if limit is not None and limit >= 0:
        rows = rows[:limit]
    return rows


def get(name: str) -> dict[str, Any] | None:
    """Return the canonical entry for ``name`` or ``None`` if unknown."""
    target = name.strip()
    if not target.startswith("do_"):
        target = f"do_{target}"
    for entry in all_commands():
        if entry["name"] == target:
            return entry
    return None


def duplicates() -> list[dict[str, Any]]:
    """Return the duplicate-method audit list as stored in the index."""
    return list(load_index().get("duplicates", []))


def totals() -> dict[str, int]:
    """Return the ``totals`` block (counts of methods, unique names, ...)."""
    return dict(load_index().get("totals", {}))


__all__ = [
    "CommandIndexError",
    "DEFAULT_INDEX_PATH",
    "all_categories",
    "all_commands",
    "all_phases",
    "duplicates",
    "filter_by_category",
    "filter_by_phase",
    "get",
    "load_index",
    "search",
    "totals",
]
