"""Core primitives for the LazyOwn framework.

Stable, dependency-light building blocks shared by the CLI (``lazyown.py``),
the C2 (``lazyc2.py``), the MCP server (``skills/lazyown_mcp.py``) and the
autonomous skill stack. ``utils.py`` re-exports these symbols for backwards
compatibility with legacy import paths.
"""

from core.config import PAYLOAD_FILENAME, PAYLOAD_PATH, Config, load_payload, save_payload
from core.console import (
    BG_BLACK,
    BG_BLUE,
    BG_BRIGHT_BLACK,
    BG_BRIGHT_BLUE,
    BG_BRIGHT_CYAN,
    BG_BRIGHT_GREEN,
    BG_BRIGHT_MAGENTA,
    BG_BRIGHT_RED,
    BG_BRIGHT_WHITE,
    BG_BRIGHT_YELLOW,
    BG_COLOR_256,
    BG_CYAN,
    BG_GREEN,
    BG_MAGENTA,
    BG_RED,
    BG_TRUE_COLOR,
    BG_WHITE,
    BG_YELLOW,
    BLACK,
    BLINK,
    BLUE,
    BOLD,
    BRIGHT_BLACK,
    BRIGHT_BLUE,
    BRIGHT_CYAN,
    BRIGHT_GREEN,
    BRIGHT_MAGENTA,
    BRIGHT_RED,
    BRIGHT_WHITE,
    BRIGHT_YELLOW,
    COLOR_256,
    CYAN,
    GREEN,
    INVERT,
    MAGENTA,
    RED,
    RESET,
    SURROGATE_CHARS,
    TRANSLATION_TABLE,
    TRUE_COLOR,
    UNDERLINE,
    WHITE,
    YELLOW,
    print_error,
    print_msg,
    print_succ,
    print_warn,
)
from core.crypto import xor_encrypt_decrypt
from core.payload_schema import (
    SCHEMA,
    FieldKind,
    FieldSpec,
    Severity,
    ValidationIssue,
    categories,
    coerce_value,
    default_payload,
    field_for,
    format_issue,
    validate_payload,
    validate_value,
)
from core.validators import check_lhost, check_lport, check_port, check_rhost

__all__ = [
    "Config",
    "PAYLOAD_FILENAME",
    "PAYLOAD_PATH",
    "load_payload",
    "save_payload",
    "RESET",
    "BOLD",
    "UNDERLINE",
    "INVERT",
    "BLINK",
    "BLACK",
    "RED",
    "GREEN",
    "YELLOW",
    "BLUE",
    "MAGENTA",
    "CYAN",
    "WHITE",
    "BG_BLACK",
    "BG_RED",
    "BG_GREEN",
    "BG_YELLOW",
    "BG_BLUE",
    "BG_MAGENTA",
    "BG_CYAN",
    "BG_WHITE",
    "BRIGHT_BLACK",
    "BRIGHT_RED",
    "BRIGHT_GREEN",
    "BRIGHT_YELLOW",
    "BRIGHT_BLUE",
    "BRIGHT_MAGENTA",
    "BRIGHT_CYAN",
    "BRIGHT_WHITE",
    "BG_BRIGHT_BLACK",
    "BG_BRIGHT_RED",
    "BG_BRIGHT_GREEN",
    "BG_BRIGHT_YELLOW",
    "BG_BRIGHT_BLUE",
    "BG_BRIGHT_MAGENTA",
    "BG_BRIGHT_CYAN",
    "BG_BRIGHT_WHITE",
    "COLOR_256",
    "BG_COLOR_256",
    "TRUE_COLOR",
    "BG_TRUE_COLOR",
    "SURROGATE_CHARS",
    "TRANSLATION_TABLE",
    "print_msg",
    "print_warn",
    "print_error",
    "print_succ",
    "xor_encrypt_decrypt",
    "check_rhost",
    "check_lhost",
    "check_lport",
    "check_port",
    "SCHEMA",
    "FieldKind",
    "FieldSpec",
    "Severity",
    "ValidationIssue",
    "categories",
    "coerce_value",
    "default_payload",
    "field_for",
    "format_issue",
    "validate_payload",
    "validate_value",
]
