"""Artificial Intelligence command set.

Pending phase module covering the ``do_ask``, ``do_groq``, ``do_ai_playbook``
and ``do_ai_toggle`` commands that delegate prompts to the configured LLM
backend (Groq via API key, Ollama locally) or toggle the AI assistant
on/off.

Pending status: this set inherits from
:class:`cli.commands._dormancy.PendingCommandSet`, so it is discovered for
test coverage but not registered onto the shell while ``LazyOwnShell``
still defines the original methods. Promote it to
:class:`cli.commands._base.LazyOwnCommandSet` once the legacy copies are
deleted from ``lazyown.py``.
"""

from __future__ import annotations

import csv
import json
import os
import traceback

import cmd2

from cli.commands._dormancy import PendingCommandSet
from utils import (
    ai_category,
    load_knowledge_base,
    manual_yaml_extraction,
    parse_nmap_csv,
    parse_yaml_response,
    preprocess_llm_response,
    print_error,
    print_msg,
    print_warn,
    query_ollama,
    save_playbook,
)

CONFIG_KEY_API_KEY = "api_key"
CONFIG_KEY_MODEL_OLLAMA = "llm_model_ollama"
DEFAULT_OLLAMA_MODEL = "deepseek-r1:1.5b"

SESSIONS_DIRECTORY_NAME = "sessions"
WORLD_MODEL_FILENAME = "world_model.json"
SESSION_REPORT_FILENAME = "LazyOwn_session_report.csv"
RECENT_COMMAND_HISTORY = 5
OS_LABELS = {"1": "Linux", "2": "Windows"}
UNKNOWN_LABEL = "unknown"
NONE_LABEL = "none"
ASK_CONTEXT_KEYS = ("tool", "command", "name")
GROQ_API_KEY_ENV = "GROQ_API_KEY"
GROQ_CONSOLE_URL = "https://console.groq.com"
LAZYGPT_CLI_RELATIVE_PATH = "modules/lazygptcli2.py"
PLAYBOOK_DEBUG_DIRECTORY = "debug"
PLAYBOOK_DEFAULT_NAME = "AutoGeneratedPlaybook"
PLAYBOOK_LLM_MAX_ATTEMPTS = 3
PLAYBOOK_VALID_PREFIX = "apt_name:"
PLAYBOOK_VALID_PREFIX_HEAD = 100
PLAYBOOK_DESCRIPTION_PREVIEW = 50
PLAYBOOK_VULNS_CSV_TEMPLATE = "sessions/vulns_{target}.csv"
PLAYBOOK_FORCE_YAML_REMINDER = "\n\nIMPORTANT: YOUR RESPONSE MUST BE PURE YAML ONLY! NO EXPLANATION TEXT!"
AI_TOGGLE_ONLINE = "Online"
AI_TOGGLE_OFFLINE = "Offline"


class AiCommandSet(PendingCommandSet):
    """Pending phase module for the Artificial Intelligence commands."""

    phase = "ai"
    category = ai_category

    @cmd2.with_category(ai_category)
    def do_ask(self, line):
        """Ask the AI a question with current session context pre-loaded.

        Injects rhost, lhost, phase, OS, latest scan summary, and recent
        commands into the prompt so the AI can give targeted advice
        without the operator having to copy-paste context manually.

        Requires an ``api_key`` set via ``assign api_key <groq-key>``.

        Usage:
            ``ask what are the best privesc paths for this Linux host?``
            ``ask what services look exploitable on this target?``
            ``ask how do I exploit SMB signing disabled?``

        Args:
            line: Free-form question forwarded to the LLM.

        Returns:
            None.
        """
        question = (line or "").strip()
        if not question:
            print_error("Usage: ask <question>")
            return
        api_key = self.params.get(CONFIG_KEY_API_KEY) or ""
        if not api_key:
            print_error(f"api_key not set. Get a free key at {GROQ_CONSOLE_URL} then: assign api_key <key>")
            return
        rhost = self.params.get("rhost") or UNKNOWN_LABEL
        lhost = self.params.get("lhost") or UNKNOWN_LABEL
        os_id = str(self.params.get("os_id", "?"))
        os_label = OS_LABELS.get(os_id, UNKNOWN_LABEL)
        domain = self.params.get("domain") or NONE_LABEL
        world: dict = {}
        sessions_root = os.path.join(self.path, SESSIONS_DIRECTORY_NAME)
        world_model_path = os.path.join(sessions_root, WORLD_MODEL_FILENAME)
        if os.path.isfile(world_model_path):
            try:
                with open(world_model_path, encoding="utf-8") as handle:
                    world = json.load(handle)
            except (OSError, json.JSONDecodeError):
                world = {}
        phase = (world.get("phase") or world.get("current_phase") or UNKNOWN_LABEL).upper()
        hosts = list(world.get("hosts", {}).keys())
        vulnerabilities = world.get("vulnerabilities") or []
        recent_commands: list[str] = []
        report_path = os.path.join(sessions_root, SESSION_REPORT_FILENAME)
        if os.path.isfile(report_path):
            try:
                with open(report_path, newline="", encoding="utf-8", errors="ignore") as handle:
                    rows = list(csv.DictReader(handle))
                column = next((c for c in ASK_CONTEXT_KEYS if rows and c in rows[0]), None)
                if column:
                    recent_commands = [r[column] for r in rows[-RECENT_COMMAND_HISTORY:] if r.get(column)]
            except OSError:
                recent_commands = []
        context = (
            f"Target: {rhost} | Attacker: {lhost} | Domain: {domain} | "
            f"OS: {os_label} | Phase: {phase}\n"
            f"Known hosts: {', '.join(hosts) or NONE_LABEL}\n"
            f"Vulnerabilities found: {len(vulnerabilities)}\n"
            f"Recent commands: {', '.join(recent_commands) or NONE_LABEL}\n"
        )
        full_prompt = f"Session context:\n{context}\n\nOperator question: {question}"
        print_msg(f"Asking AI with session context ({len(recent_commands)} recent commands)...")
        cli_script = os.path.join(self.path, LAZYGPT_CLI_RELATIVE_PATH)
        os.system(f"export {GROQ_API_KEY_ENV}=\"{api_key}\" && python3 {cli_script} --prompt '{full_prompt}'")

    @cmd2.with_category(ai_category)
    def do_groq(self, line):
        """Send a prompt to the Groq API using the configured ``api_key``.

        When the input line is empty the shell's current prompt string is
        forwarded as the message. The ``GROQ_API_KEY`` environment
        variable is exported for the helper CLI invocation.

        Args:
            line: Prompt text. Empty falls back to ``self.prompt``.

        Returns:
            None.
        """
        api_key = self.params[CONFIG_KEY_API_KEY]
        prompt = self.prompt if not line else line.strip()
        cli_script = os.path.join(self.path, LAZYGPT_CLI_RELATIVE_PATH)
        print_msg(f"Executing... python3 {cli_script} --prompt '{prompt}'")
        os.system(f"export {GROQ_API_KEY_ENV}=\"{api_key}\" && python3 {cli_script} --prompt '{prompt}'")

    @cmd2.with_category(ai_category)
    def do_ai_playbook(self, line):
        """Generate an offensive playbook from Nmap CSV + KB + Ollama.

        Combines a parsed Nmap CSV export, the local technique knowledge
        base, and an Ollama LLM completion to render a YAML playbook
        under ``playbooks/``.

        Usage:
            ``ai_playbook <csv_file> [playbook_name] [model_name]``

        Args:
            line: Whitespace-separated positional arguments. All are
                optional; missing values fall back to
                ``sessions/vulns_<rhost>.csv``, ``AutoGeneratedPlaybook``
                and the ``llm_model_ollama`` payload value.

        Returns:
            None.
        """
        arguments = line.strip().split()
        target = self.params.get("rhost") or UNKNOWN_LABEL
        default_model = self.params.get(CONFIG_KEY_MODEL_OLLAMA, DEFAULT_OLLAMA_MODEL)
        if not arguments:
            csv_file = PLAYBOOK_VULNS_CSV_TEMPLATE.format(target=target)
            playbook_name = PLAYBOOK_DEFAULT_NAME
            model_name = default_model
        elif len(arguments) == 1:
            csv_file = arguments[0]
            playbook_name = PLAYBOOK_DEFAULT_NAME
            model_name = default_model
        elif len(arguments) == 2:
            csv_file = arguments[0]
            playbook_name = arguments[1]
            model_name = default_model
        else:
            csv_file = arguments[0]
            playbook_name = arguments[1]
            model_name = arguments[2]
        try:
            if not os.path.exists(csv_file):
                print_error(f"[!] File not found: {csv_file}")
                return
            print_msg("[*] Parsing Nmap CSV results...")
            nmap_services = parse_nmap_csv(csv_file)
            if not nmap_services:
                print_warn("[!] No services found in the CSV.")
                return
            print_msg(f"[+] Found {len(nmap_services)} services")
            print_msg("[*] Loading knowledge base...")
            knowledge_base = load_knowledge_base()
            if not knowledge_base:
                print_warn("[!] Knowledge base is empty.")
            print_msg(f"[+] Loaded {len(knowledge_base)} techniques")
            print_msg("[*] Creating prompt for LLM...")
            base_prompt = f"Generate attack plan for target: {os.path.basename(csv_file)}"
            complex_prompt = self._create_strict_yaml_prompt(
                base_prompt=base_prompt,
                nmap_services=nmap_services,
                knowledge_base=knowledge_base,
            )
            print_msg(f"[*] Generating playbook with {model_name}...")
            os.makedirs(PLAYBOOK_DEBUG_DIRECTORY, exist_ok=True)
            prompt_path = os.path.join(PLAYBOOK_DEBUG_DIRECTORY, f"prompt_{playbook_name}.txt")
            with open(prompt_path, "w", encoding="utf-8") as handle:
                handle.write(complex_prompt)
            response = None
            for attempt in range(1, PLAYBOOK_LLM_MAX_ATTEMPTS + 1):
                response = query_ollama(complex_prompt, model=model_name)
                if not response:
                    print_error(f"[!] Attempt {attempt}: Failed to get response from Ollama")
                    continue
                self._last_llm_response = response
                head = response[:PLAYBOOK_VALID_PREFIX_HEAD]
                if response.strip().startswith(PLAYBOOK_VALID_PREFIX) or PLAYBOOK_VALID_PREFIX in head:
                    print_msg(f"[+] Attempt {attempt}: Got valid-looking YAML response")
                    break
                print_warn(f"[!] Attempt {attempt}: Response doesn't look like valid YAML, retrying...")
                if attempt < PLAYBOOK_LLM_MAX_ATTEMPTS:
                    complex_prompt += PLAYBOOK_FORCE_YAML_REMINDER
            raw_path = os.path.join(PLAYBOOK_DEBUG_DIRECTORY, f"raw_{playbook_name}.txt")
            with open(raw_path, "w", encoding="utf-8") as handle:
                handle.write(response or "")
            print_msg(f"[*] Raw response saved to {raw_path}")
            print_msg("[*] Parsing LLM response...")
            processed_response = preprocess_llm_response(response or "")
            playbook_data = parse_yaml_response(processed_response)
            if not playbook_data:
                print_error("[!] Failed to parse YAML response")
                print_error("[!] Attempting fallback manual YAML extraction...")
                playbook_data = manual_yaml_extraction(processed_response)
                if not playbook_data:
                    print_error("[!] All parsing attempts failed")
                    print_msg("[*] You can run 'debug_yaml' to analyze the response")
                    return
            print_msg("[*] Saving playbook...")
            playbook_path = save_playbook(playbook_data, playbook_name)
            print_msg(f"[+] Playbook generated: {playbook_path}")
            print_msg("\n[+] Playbook Summary:")
            print_msg(f"  Name: {playbook_data.get('apt_name', 'Unknown')}")
            description = playbook_data.get("description", "No description")
            print_msg(f"  Description: {description[:PLAYBOOK_DESCRIPTION_PREVIEW]}...")
            print_msg(f"  Steps: {len(playbook_data.get('steps', []))}")
        except Exception as error:
            print_error(f"[!] Unexpected error: {error}")
            print_error(traceback.format_exc())

    @cmd2.with_category(ai_category)
    def do_ai_toggle(self, _arg):
        """Toggle the in-process AI assistant on or off.

        Flips ``use_ai`` on the shell so subsequent prompts either consult
        the configured LLM backend or pass through untouched.

        Args:
            _arg: Unused command-line argument.

        Returns:
            None.
        """
        self.use_ai = not self.use_ai
        status = AI_TOGGLE_ONLINE if self.use_ai else AI_TOGGLE_OFFLINE
        self.poutput(f"AI status {status}.")


__all__ = ["AiCommandSet"]
