"""misc commands migrated from lazyown.py.

Auto-generated by scripts/migrate_lazyown.py.
"""
from __future__ import annotations

import base64
import glob
import os
import shlex
import shutil
import subprocess
import sys
import time

import cmd2

from cli.aliases import load_aliases as _load_aliases
from cli.assign import apply_assign as _apply_assign
from cli.autosuggest import render_hint_line as _render_autosuggest_hint
from cli.banner_config import banner_summary as _banner_summary
from cli.banner_config import configure_banner_interactive as _configure_banner_interactive
from cli.commands._base import LazyOwnCommandSet
from cli.graph_advisor import GraphAdvisor as _GraphAdvisor
from cli.graph_advisor import format_god_nodes as _format_god_nodes
from cli.graph_advisor import format_neighbors as _format_neighbors
from cli.graph_advisor import format_search_table as _format_search_table
from cli.ops_commands import PHASES as _PHASES
from cli.ops_commands import loot_graph as _loot_graph
from cli.ops_commands import loot_mark as _loot_mark
from cli.ops_commands import loot_reuse as _loot_reuse
from cli.ops_commands import loot_search as _loot_search
from cli.ops_commands import loot_show as _loot_show
from cli.ops_commands import note_add as _note_add
from cli.ops_commands import note_list as _note_list
from cli.ops_commands import pivot_add as _pivot_add
from cli.ops_commands import pivot_list as _pivot_list
from cli.ops_commands import print_ctx as _print_ctx
from cli.ops_commands import print_phase as _print_phase
from cli.ops_commands import read_phase as _read_phase
from cli.ops_commands import scans_list as _scans_list
from cli.ops_commands import sitrep as _sitrep
from cli.ops_commands import tasks_add as _tasks_add
from cli.ops_commands import tasks_done as _tasks_done
from cli.ops_commands import tasks_list as _tasks_list
from cli.ops_commands import tasks_start as _tasks_start
from cli.ops_commands import tgrep as _tgrep
from cli.ops_commands import write_phase as _write_phase
from cli.palette import CommandIndexError as _CommandIndexError
from cli.palette import load_index as _load_command_index
from cli.palette_command import PaletteRenderConfig as _PaletteRenderConfig
from cli.palette_command import render as _render_palette
from cli.show import format_payload as _format_payload
from cli.wizard import run as _run_wizard
from core.config import save_payload as _save_payload
from core.process import ensure_tmux_session as _ensure_tmux_session
from core.safe_exec import safe_run_shell as _safe_run_shell
from modules.module_registry import ModuleRegistry as _ModuleRegistry
from modules.module_registry import format_module_detail as _format_module_detail
from modules.module_registry import format_module_table as _format_module_table
from modules.payload_factory import format_payload_table as _format_payload_table
from rich.table import Table as _Table
from utils import (
    BLUE,
    BOLD,
    CYAN,
    GREEN,
    MAGENTA,
    RED,
    RESET,
    WHITE,
    YELLOW,
    check_lhost,
    check_rhost,
    print_error,
    print_msg,
    print_warn,
)

_PALETTE_RENDER_CONFIG = _PaletteRenderConfig()

_TMUX_SESSION = "lazyown"
_TMUX_SIZE = 50


class MiscMigratedCommandSet(LazyOwnCommandSet):
    phase = "misc"
    category = "12. Miscellaneous"

    @cmd2.with_category("12. Miscellaneous")
    def do_notify(self, arg):
        """Command to trigger a toastr-like notification.
        Usage: notify <type> <message>
        Example: notify success Implant checked in!
        """
        try:
            args = arg.split(maxsplit=1)
            if len(args) < 2:
                print_warn("Usage: notify <type> <message>")
                return
            type, message = args[0], args[1]
            if type.lower() not in ["success", "error", "warning", "info"]:
                print_error("Invalid type. Use: success, error, warning, info")
                return
            self.display_toastr(message, type=type)
        except Exception:
            print_error("Error:")

    @cmd2.with_category("12. Miscellaneous")
    def do_EOF(self, line):
        """
        Handle the end-of-file (EOF) condition.

        This method is called when the user sends an end-of-file (EOF) signal
        by pressing Ctrl+D. It is typically used to handle cleanup or exit
        operations when the user terminates input.

        In this implementation, it prints a farewell message and returns True
        to indicate that the shell should exit.

        License: This function is part of a program released under the GNU General
        Public License v3.0 (GPLv3). You can redistribute it and/or modify it
        under the terms of the GPLv3, as published by the Free Software Foundation.

        Note: This method is a part of the `cmd` library's command handling
        system. You can override it in a subclass to customize its behavior.

        Example:
            >>> shell = LazyOwnShell()
            >>> shell.do_EOF(None)
            LazyOwn say Goodbye!
            (shell exits)
        """
        print_warn("LazyOwn say Goodbye!")
        return True
















    def _handle_killchain_auto(self, spec: str) -> None:
        """Set the kill-chain auto-refresh cadence for the current session."""
        shell = self._resolve_shell()
        engine = getattr(shell, "_tips_engine", None)
        value = (spec or "").strip().lower()
        current = int(getattr(engine.config, "killchain_auto_every", 0) or 0) if engine else 0
        if value in ("on", "yes"):
            current = current or 3
            if engine:
                engine.config.killchain_auto_every = current
                engine.config.killchain_auto_on_phase_change = True
            print_msg(f"Kill-chain auto-refresh enabled (every {current} commands, on phase change)")
        elif value in ("off", "no", "0"):
            if engine:
                engine.config.killchain_auto_every = 0
                engine.config.killchain_auto_on_phase_change = False
            print_msg("Kill-chain auto-refresh disabled")
        elif value.isdigit() and int(value) > 0:
            if engine:
                engine.config.killchain_auto_every = int(value)
                engine.config.killchain_auto_on_phase_change = True
            print_msg(f"Kill-chain auto-refresh set to every {value} commands")
        else:
            state = f"enabled (every {current})" if current else "disabled"
            print_msg(f"Kill-chain auto-refresh: {state}  (phase-change trigger: {getattr(engine.config, 'killchain_auto_on_phase_change', True) if engine else True})")












    @cmd2.with_category("12. Miscellaneous")
    def do_palette(self, line):
        """Browse the operator command catalogue grouped by kill-chain phase.

        The data source is :file:`cli/command_index.json`, generated by
        ``scripts/build_command_index.py``. Rendering is delegated to
        :func:`cli.palette_command.render` so the same logic powers the C2
        ``/palette`` endpoint and the MCP ``lazyown_palette`` tool.

        Usage:
            ``palette``                     overview of every phase
            ``palette <phase>``             list commands in a phase
            ``palette <phase> <query>``     filter that listing
            ``palette --search <query>``    fuzzy search across all phases
            ``palette --info <name>``       full detail for a single command
        """
        try:
            index = _load_command_index()
        except _CommandIndexError as exc:
            print_error(f"{exc}")
            return
        rendered = _render_palette(index, line, config=_PALETTE_RENDER_CONFIG)
        if rendered:
            print_msg(rendered)

    @cmd2.with_category("12. Miscellaneous")
    def do_graph_search(self, line):
        """Fuzzy search the graphify knowledge graph for nodes by label.

        Usage: ``graph_search <query> [limit]``. Returns ranked nodes from
        ``graphify-out/graph_lazyown.json`` with degree, community and
        source location. Run ``/graphify .`` from the project root once if
        the graph is missing.

        :param line: free-text query, optionally followed by a numeric limit.
        :type line: str
        :return: None
        """
        parts = (line or "").rsplit(maxsplit=1)
        if len(parts) == 2 and parts[1].isdigit():
            query, limit = parts[0], int(parts[1])
        else:
            query, limit = line, None
        advisor = _GraphAdvisor.from_path()
        if not advisor.is_available():
            print_warn(advisor.summary().get("reason", "graph unavailable"))
            return
        if not (query or "").strip():
            print_error("usage: graph_search <query> [limit]")
            return
        results = advisor.search(query, limit=limit)
        print_msg(_format_search_table(results))

    @cmd2.with_category("12. Miscellaneous")
    def do_neighbors(self, line):
        """Show graph neighbors of a node or command from the graphify graph.

        Usage: ``neighbors <node_or_command> [depth] [limit]``. Resolves
        the closest matching node (by id or label) and walks the graph
        outward. Useful for the question *"if I just ran X, what is it
        connected to?"*.

        :param line: node id or label, optional integer depth, optional
            integer limit.
        :type line: str
        :return: None
        """
        tokens = (line or "").split()
        if not tokens:
            print_error("usage: neighbors <node> [depth] [limit]")
            return
        query = tokens[0]
        depth = int(tokens[1]) if len(tokens) >= 2 and tokens[1].isdigit() else None
        limit = int(tokens[2]) if len(tokens) >= 3 and tokens[2].isdigit() else None
        advisor = _GraphAdvisor.from_path()
        if not advisor.is_available():
            print_warn(advisor.summary().get("reason", "graph unavailable"))
            return
        print_msg(_format_neighbors(advisor.neighbors(query, depth=depth, limit=limit)))

    @cmd2.with_category("12. Miscellaneous")
    def do_god_nodes(self, line):
        """Show the most-connected nodes ("god nodes") from the graph.

        Usage: ``god_nodes [N]``. These are the core abstractions of the
        codebase by degree centrality. Useful as orientation when you've
        just started a campaign and want a map of the framework.

        :param line: optional numeric limit (default from the advisor config).
        :type line: str
        :return: None
        """
        bound = int(line) if (line or "").strip().isdigit() else None
        advisor = _GraphAdvisor.from_path()
        if not advisor.is_available():
            print_warn(advisor.summary().get("reason", "graph unavailable"))
            return
        print_msg(_format_god_nodes(advisor.god_nodes(limit=bound)))

    @cmd2.with_category("12. Miscellaneous")
    def do_suggest_next(self, line):
        """Suggest next commands by walking the graph from recent activity.

        Usage: ``suggest_next [N]``. Reads ``sessions/LazyOwn_session_report.csv``
        to find recent commands and recommends graph neighbours weighted by
        inverse distance. Pass space-separated command names to override the
        recent history (``suggest_next lazynmap do_ping 7``).

        :param line: optional list of seed commands, optionally followed by
            a numeric limit.
        :type line: str
        :return: None
        """
        import csv as _csv2
        import json as _j

        tokens = (line or "").split()
        if tokens and tokens[-1].isdigit():
            limit  = int(tokens[-1])
            seeds  = tokens[:-1]
        else:
            limit  = 6
            seeds  = tokens

        # Determine phase
        phase     = self.params.get("phase", "") or "recon"
        _palias   = {
            "recon": "recon", "scan": "recon",
            "enum": "enum",
            "exploit": "exploit",
            "privesc": "privesc", "postexp": "postexp",
            "lateral": "lateral",
            "cred": "cred",
            "exfil": "exfil",
            "c2": "c2",
            "report": "report",
        }
        phase_key = _palias.get(phase.lower(), "recon")

        # Commands already run this session
        _seen2: set = set()
        try:
            with open("sessions/LazyOwn_session_report.csv", newline="", errors="ignore") as _fh2:
                for _row2 in _csv2.DictReader(_fh2):
                    _v2 = (_row2.get("tool") or _row2.get("command") or "").strip().split()[0]
                    if _v2:
                        _seen2.add(_v2)
                        _seen2.add(f"do_{_v2}")
        except OSError:
            pass

        # Load command index
        try:
            _idx    = _j.loads(open("cli/command_index.json").read())
            _ptc    = _idx.get("phase_to_commands", {})
            _meta   = {
                e["name"]: e.get("summary", "")
                for e in _idx.get("commands", []) if isinstance(e, dict) and "name" in e
            }
        except Exception:
            _idx  = {}
            _ptc  = {}
            _meta = {}

        # Trigger-matched addons/tools from the latest nmap scan
        _trigger_shown = 0
        try:
            from cli.exploration import ExplorationEngine, resolve_current_os
            _rhost_seed = self.params.get("rhost") or None
            _engine = ExplorationEngine(current_os=resolve_current_os(self.params))
            _ux_addons = _engine.unexplored_addons(_rhost_seed)
            _ux_tools = _engine.unexplored_tools(_rhost_seed)
            _ux_combined: list[tuple[str, str]] = []
            for _a in _ux_addons:
                _ux_combined.append((_a.name, "addon"))
            for _t in _ux_tools:
                _ux_combined.append((_t.name, "tool"))
            if _ux_combined:
                print_msg("Triggered by your scan (never run):")
                for _entry_name, _kind in _ux_combined[:limit]:
                    print_msg(f"  {_entry_name:<26} [{_kind}]")
                    _trigger_shown += 1
        except Exception as _exc:
            print_warn(f"Trigger suggestions unavailable: {_exc}")

        # Use seeds as extra priority if provided
        _shown = _trigger_shown
        if seeds:
            print_msg(f"Suggestions after: {', '.join(seeds)}")
            from cli.reactive_hints import _KILL_CHAIN_NEXT as _KCN
            for _seed in seeds:
                for _next in _KCN.get(_seed, [])[:limit]:
                    if _next not in _seen2:
                        _lbl = _next.replace("do_", "")
                        _sum = _meta.get(f"do_{_next}", _meta.get(_next, ""))[:70]
                        print_msg(f"  {_lbl:<26} {_sum}")
                        _shown += 1
                        if _shown >= limit:
                            break
                if _shown >= limit:
                    break

        if _shown < limit:
            # Phase-priority suggestions not yet run
            _candidates = [
                c for c in _ptc.get(phase_key, [])
                if c not in _seen2 and c.replace("do_", "") not in _seen2
            ]
            if not _candidates:
                # Always useful basics if index empty
                _candidates = ["do_ping", "do_lazynmap", "do_gobuster", "do_enum4linux", "do_searchsploit"]
            if _shown == 0:
                print_msg(f"Suggested next for phase '{phase_key}':")
            for _c in _candidates[:limit - _shown]:
                _lbl = _c.replace("do_", "")
                _sum = _meta.get(_c, "")[:70]
                print_msg(f"  {_lbl:<26} {_sum}")
                _shown += 1

        if _shown == 0:
            print_msg("  All phase commands have been run. Try: recommend_next")

        if not _seen2:
            print_msg("  (No session history yet — start with:  ping  →  lazynmap)")

    @cmd2.with_category("12. Miscellaneous")
    def do_recommend_next(self, line):
        """Recommend the next action via the unified recommendation engine.

        This is the single source of truth for "what next". The engine in
        ``cli/recommendation.py`` fuses every available signal into one ranked
        list with full provenance:

        - **policy** (``skills/lazyown_policy.py``) — learned kill-chain category
          priors that up-weight matching concrete actions.
        - **recon plan** (``cli/recon_plan.py``) — addons/tools/commands whose
          trigger matches services in the latest nmap scan.
        - **graph** (``cli/graph_advisor.py``) — graphify neighbours of your
          recent activity. Requires ``/graphify .`` at least once.
        - **kill-chain** — static adjacency / phase-priority tables.

        Signals whose backend is absent degrade silently. This is the CLI
        equivalent of the MCP tool ``lazyown_recommend_next``.

        Usage:
            ``recommend_next [N]``
        """
        from rich.console import Console as _RC
        from rich.rule import Rule

        from cli.recommendation import KIND_CATEGORY
        from cli.recommendation_signals import build_context, build_default_engine

        c = _RC(highlight=False, soft_wrap=True)
        tokens = (line or "").split()
        limit = int(tokens[0]) if tokens and tokens[0].isdigit() else 5

        engine = build_default_engine(payload=self.params)
        ctx = build_context(self.params, target=self.params.get("rhost") or None, limit=limit)
        recommendations = engine.recommend(ctx)

        if not recommendations:
            print_warn("No recommendations yet.")
            print_msg("Start with 'lazynmap' to generate scan data, then run 'recommend_next' again.")
            return

        c.print(Rule("[bold]Next-best actions[/] (fused: policy + recon + graph + kill-chain)"))
        for i, rec in enumerate(recommendations, 1):
            normalised = min(rec.score, 1.0)
            bar = "█" * int(normalised * 10)
            tag = "category" if rec.kind == KIND_CATEGORY else rec.kind
            sources = ", ".join(rec.sources)
            c.print(
                f"  [bold cyan]{i}.[/] [{bar:<10}] [bold]{rec.action}[/] "
                f"[dim]({tag} · {sources})[/]"
            )
            for reason in rec.reasons:
                c.print(f"       [dim]{reason}[/]")
            if rec.command_preview:
                c.print(f"       [green]$ {rec.command_preview}[/]")
        c.print()

    @cmd2.with_category("12. Miscellaneous")
    def do_explore(self, line):
        """Show exploration coverage and addon/tool suggestions per service.

        Reads ``sessions/scan_*.nmap.xml`` for discovered services, joins
        them with the ``trigger`` and ``os`` fields declared in every
        ``lazyaddons/*.yaml`` and ``tools/*.tool``, and renders a Rich
        tree alongside a coverage table summarising how much of the
        attack surface has already been touched by previous commands.

        Usage:
            ``explore``                show coverage for the active rhost
            ``explore <target>``       force a target (defaults to ``rhost``)

        The view highlights items whose trigger matches a discovered
        service but have never been run, so the operator can pick the
        next high-value command without manually scanning the YAMLs.
        """
        from rich.console import Console as _RC

        from cli.exploration import ExplorationEngine, resolve_current_os
        from cli.exploration_view import render_exploration

        tokens = (line or "").split()
        target = tokens[0] if tokens else (self.params.get("rhost") or None)
        current_os = resolve_current_os(self.params)
        engine = ExplorationEngine(current_os=current_os)
        console = _RC(highlight=False, soft_wrap=True)
        history = engine.history()
        render_exploration(console, engine, target, history)

    @cmd2.with_category("12. Miscellaneous")
    def do_prev(self, line):
        """Show prerequisite commands for a verb (the chain's ``prev`` arrow).

        Usage:
            ``prev <command>``     list ordered prerequisites
            ``prev``               use the most recent command from history

        The list reflects the static prerequisite registry declared in
        ``cli/command_chain.py`` and is also exposed via the MCP tool
        ``lazyown_command_prev`` so the AI loop sees the same view.

        :param line: command verb (with or without the ``do_`` prefix).
        :type line: str
        :return: None
        """
        from cli.command_chain import CommandChain
        chain = CommandChain()
        verb = (line or "").strip()
        if not verb:
            from cli.exploration import ExplorationEngine, resolve_current_os
            engine = ExplorationEngine(current_os=resolve_current_os(self.params))
            history = sorted(engine.history())
            if not history:
                print_warn("No command history yet. Pass a verb, e.g. `prev lazynmap`.")
                return
            verb = history[-1]
        prereqs = chain.prev(verb)
        if not prereqs:
            print_msg(f"No prerequisites declared for '{verb}'.")
            return
        print_msg(f"Prerequisites for '{verb}':")
        for item in prereqs:
            print_msg(f"  {item}")

    @cmd2.with_category("12. Miscellaneous")
    def do_dashboard(self, line):
        """Launch the full-screen LazyOwn operator dashboard (Textual TUI).

        Opens an auto-refreshing terminal dashboard showing the active target,
        kill chain progress, recent commands, objectives, credentials, beacons
        and graph-driven next-step hints. Press Q or Ctrl-C to close and return
        to the shell.

        Usage: ``dashboard``

        The dashboard reads from:
        - ``payload.json`` — target / attacker config and feature flags.
        - ``sessions/world_model.json`` — current phase and objectives.
        - ``sessions/tasks.json`` — active task list.
        - ``sessions/LazyOwn_session_report.csv`` — recent commands.
        - ``sessions/credentials*.txt`` / ``sessions/hash*.txt`` — credential counts.
        - ``graphify-out/graph_lazyown.json`` — next-step hints (requires ``/graphify .``).

        The ``textual`` package must be installed (``pip install textual``). When
        the package is missing the command prints an install hint and returns.

        :param line: Unused. Reserved for future flags.
        :type line: str
        :return: None
        """
        try:
            from cli.dashboard_tui import launch as _launch_dashboard
        except ImportError:
            print_error(
                "textual is not installed. Run: pip install textual"
            )
            return
        payload_path = "payload.json"
        sessions_dir = getattr(self, "sessions_dir", "sessions") or "sessions"
        _launch_dashboard(payload_path=payload_path, sessions_dir=sessions_dir)

    @cmd2.with_category("12. Miscellaneous")
    def do_palette_k(self, line):
        """Open the fuzzy Command-K palette overlay.

        Modal Textual overlay that lists every ``do_*`` command, ranks
        recents first, narrows on substring input and returns the
        selected verb back to the shell for execution.

        Usage: ``palette_k``

        Requires ``textual``. When the package is missing or the command
        index is unavailable, the call prints an install hint and
        returns without raising.
        """
        try:
            from cli.palette_overlay import launch_overlay as _launch_palette_k
        except ImportError:
            print_error("palette overlay unavailable. Run: pip install textual")
            return
        selected = _launch_palette_k(payload=self.params)
        if not selected:
            return
        verb = selected[3:] if selected.startswith("do_") else selected
        print_msg(f"selected: {verb}")
        try:
            self.onecmd_plus_hooks(verb)
        except Exception as exc:
            print_warn(f"command dispatch failed: {exc}")

    @cmd2.with_category("12. Miscellaneous")
    def do_browse(self, line):
        """Open the sessions/ TUI browser.

        Categorised view of ``sessions/`` artefacts (credentials,
        hashes, vulnerabilities, scans, notes, events, world model)
        with a side preview pane and substring filter.

        Usage: ``browse``

        Requires ``textual``. When the package is missing, the command
        prints an install hint and returns.
        """
        try:
            from cli.sessions_browser import launch_browser as _launch_sessions_browser
        except ImportError:
            print_error("sessions browser unavailable. Run: pip install textual")
            return
        sessions_dir = getattr(self, "sessions_dir", "sessions") or "sessions"
        _launch_sessions_browser(payload=self.params, state=None)
        _ = sessions_dir

    @cmd2.with_category("12. Miscellaneous")
    def do_timeline_browser(self, line):
        """Open the timeline scrubber over the session report CSV.

        Scrollable, filterable view over
        ``sessions/LazyOwn_session_report.csv``. Highlight a row to see
        every recorded column for that command.

        Usage: ``timeline_browser``

        Requires ``textual``.
        """
        try:
            from cli.timeline_browser import launch_scrubber as _launch_timeline_scrubber
        except ImportError:
            print_error("timeline scrubber unavailable. Run: pip install textual")
            return
        _launch_timeline_scrubber(payload=self.params)

    @cmd2.with_category("12. Miscellaneous")
    def do_graph_overlay(self, line):
        """Open the graph overlay over the graphify knowledge graph.

        Shows the top central nodes by default and switches to the
        neighbourhood of a focus node when the operator types one. Esc
        closes; Tab toggles between modes.

        Usage: ``graph_overlay``

        Requires ``textual`` and a populated ``graphify-out/graph_lazyown.json``
        (produced by ``/graphify .``).
        """
        try:
            from cli.graph_overlay import launch_overlay as _launch_graph_overlay
        except ImportError:
            print_error("graph overlay unavailable. Run: pip install textual")
            return
        _launch_graph_overlay(payload=self.params)

    @cmd2.with_category("12. Miscellaneous")
    def do_toast_clear(self, line):
        """Mark every pending toast event as seen without printing them.

        Useful after long pauses where the autonomous daemon backlogged
        events the operator no longer cares to read. The state file at
        ``sessions/.toast_state.json`` is updated atomically.

        Usage: ``toast_clear``
        """
        try:
            from cli.toast_bus import build_default_bus as _build_toast_bus
        except ImportError:
            print_error("toast subsystem unavailable.")
            return
        sessions_dir = getattr(self, "sessions_dir", "sessions") or "sessions"
        bus = _build_toast_bus(payload=self.params, sessions_dir=sessions_dir)
        bus.mark_all_seen()
        print_msg("toast offsets advanced to current file sizes.")







    @cmd2.with_category("12. Miscellaneous")
    def do_exit(self, arg):
        """Exit the command line interface.

        This function prompts the user to confirm whether they want to exit the command line interface. If confirmed, it will terminate the program. Otherwise, it will cancel the exit.

        Usage:
            exit

        :param arg: This parameter is not used in this function.
        :type arg: str

        :returns: None

        Manual execution:
        1. Prompt the user with a confirmation message to exit the CLI.
        2. If the user confirms with 's', print a message and exit the program.
        3. If the user provides any other input, print a cancellation message and remain in the CLI.

        Dependencies:
        - `sys.exit` function for exiting the program.

        Example:
            To execute the function, simply call `exit`.

        Note:
            - The confirmation prompt is in Spanish.
            - Ensure that `sys` is imported in your script.
        """


        confirm = (
            input(f"    [!] {YELLOW} Do you wanna exit? {GREEN}(s/n): {RESET}")
            .strip()
            .lower()
        )
        if confirm == "s":
            print_msg(f"{RED}GoodBy RedTeamer...{RESET}")
            sys.exit(0)
        else:
            print_warn(f"{RED}Exit canceled.{RESET}")
            return False












    def _persist_chainmode(self, enabled: bool) -> None:
        """Persist the chain-mode toggle through the sanctioned assign path.

        Keeps ``payload.json`` and the runtime session state in agreement
        so the choice survives future boots and payload rewrites.

        Args:
            enabled: New chain-mode state to persist.

        Returns:
            None.
        """
        try:
            _apply_assign(self.params, "enable_chainmode", enabled, save=_save_payload)
        except Exception:
            pass







    @cmd2.with_category("12. Miscellaneous")
    def do_banner(self, line):
        """Show the banner"""
        if NOBANNER is False:
            subprocess.run(["python3", "banner.py"], check=False)
            print_msg(
                f"    {BG_BLACK}{RED}{BANNER}{MAGENTA}Autor: {CYAN}grisUN0{RESET}"
            )

            print_msg(self.intro)
        return

    @cmd2.with_category("12. Miscellaneous")
    def do_config_banner(self, line):
        """Open a Powerlevel10k-style wizard to toggle prompt segments.

        Arrow keys move, Space toggles, Enter saves to ``payload.json`` under
        the ``banner`` block, Escape cancels. ``d`` resets to factory
        defaults; ``a`` enables every segment; ``n`` disables every segment.
        The shell prompt refreshes immediately after a save without
        requiring a restart.

        :param line: optional sub-action. ``show`` prints the current
            enabled segments without opening the wizard. ``reset`` writes
            the factory-default segment selection back to payload.json.
        :type line: str
        :return: None
        """
        action = (line or "").strip().lower()
        payload = load_payload()
        if action in {"show", "list", "status"}:
            from cli.banner_config import BannerSettings, build_default_registry
            registry = build_default_registry()
            settings = BannerSettings.from_payload(registry, payload, "banner")
            print_msg(f"banner segments enabled: {_banner_summary(settings, registry)}")
            return
        if action in {"reset", "defaults"}:
            from cli.banner_config import BannerSettings, build_default_registry
            registry = build_default_registry()
            settings = BannerSettings.defaults(registry)
            payload["banner"] = settings.to_payload_block()
            _save_payload(payload)
            self.refresh_prompt()
            print_msg(f"banner reset to defaults: {_banner_summary(settings, registry)}")
            return
        result = _configure_banner_interactive(payload)
        if result is None:
            print_warn("banner configuration cancelled, payload unchanged")
            return
        payload["banner"] = result.to_payload_block()
        _save_payload(payload)
        self.refresh_prompt()
        print_msg(f"banner saved: {_banner_summary(result)}")


















    @cmd2.with_category("12. Miscellaneous")
    def do_aliass(self, line):
        """
        Prints all configured aliases and their associated commands.

        1. Retrieves the list of aliases from the `LazyOwnShell` instance:
        - Iterates through each alias and its associated command.

        2. For each alias:
        - Displays the alias name and the full command it represents.

        :param line: This parameter is not used in the function.
        :type line: str
        :returns: None

        Manual execution:
        To manually run these tasks, you would need to:
        - Ensure that aliases are configured in the `LazyOwnShell` instance.
        - Manually review the aliases and their commands as displayed.

        Note: This function assumes that aliases are managed by the `LazyOwnShell` instance and are available for retrieval.
        """

        aliases = self.aliases
        for alias, command in aliases.items():
            print_msg(
                f"{WHITE} Alias {GREEN} {alias}{WHITE} : Full command: {CYAN}{command}{RESET} "
            )
        return







    @cmd2.with_category("12. Miscellaneous")
    def do_graph(self, line):
        """
        Generates a graph from JSON payload files containing URL, RHOST, and RPORT.

        :param line: Not used in this implementation but reserved for future use.

        :returns: None
        """
        json_files = glob.glob("*payload*.json")

        if not json_files:
            print_error("No JSON payload files found.")
            return

        graph_content = "digraph G {\n"
        parent_node_name = "LazyOwn"
        parent_node_label = f"{parent_node_name}\nIP: 127.0.0.1\nPort: 5555"
        graph_content += f'"{parent_node_name}" [label="{parent_node_label}"];\n'

        child_nodes = []

        for json_file in json_files:
            try:
                with open(json_file) as file:
                    data = json.load(file)
                    url = data.get("url", "Unknown URL")
                    rhost = data.get("self.params['rhost']", "Unknown RHOST")
                    rport = data.get("rport", "Unknown RPORT")
                    node_label = f"{url}\nRHOST: {self.params['rhost']}\nRPORT: {rport}"
                    node_name = os.path.splitext(json_file)[0]
                    graph_content += f'"{node_name}" [label="{node_label}"];\n'
                    child_nodes.append(node_name)

            except json.JSONDecodeError:
                print_error(f"Error decoding JSON in file: {json_file}")
                continue
            except FileNotFoundError:
                print_error(f"File not found: {json_file}")
                continue
        for child in child_nodes:
            graph_content += f'"{parent_node_name}" -> "{child}";\n'

        for i in range(len(child_nodes)):
            for j in range(i + 1, len(child_nodes)):
                graph_content += f'"{child_nodes[i]}" -> "{child_nodes[j]}";\n'

        graph_content += "}\n"
        with open("sessions/graph.dot", 'w') as dot_file:
            dot_file.write(graph_content)

        subprocess.run(
            ["dot", "-Tpng", "sessions/graph.dot", "-o", "sessions/graph.png",
             "-Gbgcolor=lightgrey", "-Ecolor=blue"],
            capture_output=True, timeout=30, check=False,
        )

        return



    @cmd2.with_category("12. Miscellaneous")
    def do_h(self, arg):
        """
        Open a new window within a tmux session using the LazyOwn RedTeam Framework.

        This method is designed to create a new horizontal split window in an existing
        tmux session, where the specified command will be executed. The command
        used to open the new window is the `./run --no-banner` script, which is
        intended for use within the LazyOwn RedTeam Framework environment.

        The method first ensures that the specified tmux session is active by calling
        the `ensure_tmux_session` function. If the session is not already running,
        it will create a new one. After confirming that the session is active, it
        proceeds to create a new horizontal window with a specified size. The size of
        the new window is currently set to 50% of the available terminal space.

        Args:
            arg (str): Additional arguments passed to the command, if any. This can be
                        used to customize the behavior of the command executed in the
                        new window. However, in the current implementation, this
                        argument is not utilized and can be left as an empty string.

        Example:
            If this method is called within a command-line interface of the LazyOwn
            RedTeam Framework, it will open a new horizontal tmux window and execute
            the `./run --no-banner` command within it.

        Note:
            - Ensure that tmux is installed and properly configured on the system.
        """
        _ensure_tmux_session(_TMUX_SESSION)
        print_msg(f"Open new Windows: {_TMUX_SIZE}")
        argv = [
            "tmux",
            "split-window",
            "-v",
            "-t",
            _TMUX_SESSION,
            "-p",
            str(_TMUX_SIZE),
            "./run",
            "--no-banner",
        ]
        print_msg(" ".join(argv))
        subprocess.run(argv, shell=False)

    @cmd2.with_category("12. Miscellaneous")
    def do_v(self, arg):
        """
        Open a new window within a tmux session using the LazyOwn RedTeam Framework.

        This method is designed to create a new vertical split window in an existing
        tmux session, where the specified command will be executed. The command
        used to open the new window is the `./run --no-banner` script, which is
        intended for use within the LazyOwn RedTeam Framework environment.

        The method first ensures that the specified tmux session is active by calling
        the `ensure_tmux_session` function. If the session is not already running,
        it will create a new one. After confirming that the session is active, it
        proceeds to create a new vertical window with a specified size. The size of
        the new window is currently set to 50% of the available terminal space.

        Args:
            arg (str): Additional arguments passed to the command, if any. This can be
                        used to customize the behavior of the command executed in the
                        new window. However, in the current implementation, this
                        argument is not utilized and can be left as an empty string.

        Example:
            If this method is called within a command-line interface of the LazyOwn
            RedTeam Framework, it will open a new vertical tmux window and execute
            the `./run --no-banner` command within it.

        Note:
            - Ensure that tmux is installed and properly configured on the system.
        """
        _ensure_tmux_session(_TMUX_SESSION)
        print_msg(f"Open new Windows: {_TMUX_SIZE}")
        argv = [
            "tmux",
            "split-window",
            "-h",
            "-t",
            _TMUX_SESSION,
            "-p",
            str(_TMUX_SIZE),
            "./run",
            "--no-banner",
        ]
        print_msg(" ".join(argv))
        subprocess.run(argv, shell=False)





    @cmd2.with_category("12. Miscellaneous")
    def do_links(self, line=""):
        """
        Displays a list of useful links and allows the user to select and copy a link to the clipboard.

        This function performs the following actions:
        1. Defines a list of links with their aliases.
        2. Filters the links based on the input `line` if provided.
        3. Displays the filtered links with their aliases and URLs.
        4. Prompts the user to select a link by entering the corresponding number.
        5. Copies the selected link to the clipboard.

        Parameters:
        line (str, optional): A string to filter the links. If provided, only the links containing
                            the string in their alias or URL will be displayed. Defaults to an empty string.

        Returns:
        None
        """
        links = [
            ("Browser Leaks","https://browserleaks.com/"),
            ("CrackStation", "https://crackstation.net/"),
            ("Codebeautify", "https://codebeautify.org/ntlm-hash-generator"),
            ("CyberChef","https://gchq.github.io/CyberChef/"),
            ("Ioc", "https://ioc.one/"),
            ("Ip Info", "https://ipinfo.io/"),
            ("Mitre Navigator", "https://mitre-attack.github.io/attack-navigator/"),
            ("Threatfox Abuse", "https://threatfox.abuse.ch/browse/"),
            ("Threatminer", "https://www.threatminer.org/"),
            ("THC segfault (FREER00TSHELL)", "https://www.thc.org/segfault/"),
            ("Vpn Detector","https://ip.teoh.io/vpn-detection"),
            ("gsocket", "https://www.gsocket.io/"),
            ("linux-elf-runtime-crypter", "https://www.guitmz.com/linux-elf-runtime-crypter/"),
            ("Binary download", "https://bin.ajam.dev/"),
            ("cryptpad","https://cryptpad.fr/"),
            ("kycnot","https://kycnot.me/"),
            ("socks proxy list","https://spys.one/en/socks-proxy-list/"),
            ("Config ntlm2 BurpSuit", "https://portswigger.net/support/configuring-ntlm-with-burp-suite"),
            ("Facial recon","https://pimeyes.com/es")




        ]
        filtered_links = [(alias, cmd) for alias, cmd in links if line.lower() in alias.lower() or line.lower() in cmd.lower()] if line else links

        for idx, (alias, cmd) in enumerate(filtered_links):
            if cmd:
                print_msg(f"{idx + 1}{RESET}. Alias:{GREEN} {alias}{RESET}, Link:{CYAN} {cmd}")

        try:
            choice = int(input("    [!] Enter the number of the command you want to execute: ")) - 1
            if 0 <= choice < len(filtered_links):
                selected_cmd = filtered_links[choice]

                copy2clip(selected_cmd[1])
            else:
                print_error("Invalid choice. Please select a valid number.")
        except ValueError:
            print_error("Invalid input. Please enter a number.")
        self.logcsv(f"links {line}")
        return

    @cmd2.with_category("12. Miscellaneous")
    def do_news(self, line):
        """
        Show the Hacker News in the terminal.

        Parameters:
            line (str): optional
        Return None
        """
        titles, links, scores = scrape_news()
        display_news(titles, links, scores)
        return

    @cmd2.with_category("12. Miscellaneous")
    def do_check_update(self, line):
        """
        Checks for updates by comparing the local version with the remote version.

        This function:
            - Fetches the remote version from a JSON file hosted on GitHub.
            - Reads the local version from a JSON file in the script's root directory.
            - Compares the version numbers and determines if an update is needed.

        Behavior:
            - Requires `requests` library to fetch the remote version.
            - Uses JSON parsing to extract version numbers.

        Usage:
            check_update
        """
        try:
            response = requests.get("https://raw.githubusercontent.com/grisuno/LazyOwn/refs/heads/main/version.json")
            remote_version_data = response.json()
            remote_version = remote_version_data.get("version", "release/0.0.0").split('/')[-1]
            if remote_version == "release/0.0.0":
                print_error("Connect to internet to check updates.")
                return

            local_version_path = os.path.join(os.getcwd(), "version.json")
            with open(local_version_path) as local_version_file:
                local_version_data = json.load(local_version_file)
                local_version = local_version_data.get("version", "release/0.0.0").split('/')[-1]

            if local_version == "release/0.0.0":
                print_error("Integrity fail, please reinstall.")
                return
            if remote_version > local_version:
                print_warn("An update is available. Please update to the latest version.")
                print_msg("Updating")
                self.onecmd("update")
            elif remote_version == local_version:
                print_msg("You are already using the latest version.")
            else:
                print_error("Warning: Your local version is newer than the remote version. This should not happen.")

        except Exception as e:
            print_error(f"An error occurred: {e}")





    @cmd2.with_category("12. Miscellaneous")
    def do_addalias(self, arglist):
        """
        Add a new alias with support for placeholders like {rhost}, {lhost}, {lport}, etc.

        Usage:
            addalias <name> <command>

        Example:
            addalias myrev sh rlwrap nc {rhost} {lport} -e bash
            addalias scan run_script "lazyscripts/nmap_scan.ls {rhost}"
        """
        if len(arglist) < 2:
            self.display_toastr("Usage: addalias <name> <command>", type="error")
            return

        name = arglist[0]
        command = ' '.join(arglist[1:])

        # Validate name
        if not name.isidentifier():
            self.display_toastr(f"[!] Invalid alias name: '{name}'. Must be a valid identifier (no spaces, no special chars except _).", type="error")
            return

        if hasattr(self, f"do_{name}"):
            self.display_toastr(f"[!] '{name}' is a built-in command and cannot be used as an alias.", type="error")
            return

        # Add to runtime aliases
        self.aliases[name] = command

        # Save to JSON file
        try:
            # Reload current aliases from file to avoid overwriting
            if os.path.exists(USER_ALIASES_FILE):
                with open(USER_ALIASES_FILE) as f:
                    user_aliases = json.load(f)
            else:
                user_aliases = {}

            user_aliases[name] = command
            with open(USER_ALIASES_FILE, 'w') as f:
                json.dump(user_aliases, f, indent=2)

            self.display_toastr(f"[+] Alias '{name}' added and saved to {USER_ALIASES_FILE}")

        except Exception as e:
            self.display_toastr(f"[!] Failed to save alias: {e}", type="error")

    @cmd2.with_category("12. Miscellaneous")
    def do_listaliases(self, _):
        """List all available aliases."""
        if not self.aliases:
            self.display_toastr("[*] No aliases defined.")
            return

        self.display_toastr("Custom and built-in aliases:")
        for name, cmd in sorted(self.aliases.items()):
            print_msg(f"  {name:20} → {cmd}")



import utils as _lazy_utils

for _lazy_name in dir(_lazy_utils):
    if not _lazy_name.startswith('_'):
        globals().setdefault(_lazy_name, getattr(_lazy_utils, _lazy_name))
del _lazy_utils, _lazy_name

__all__ = ["MiscMigratedCommandSet"]


def __getattr__(name: str):
    """Fall back to ``utils`` for bare-name references used by migrated commands."""
    import utils as _utils
    try:
        return getattr(_utils, name)
    except AttributeError:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from None
