"""recon commands migrated from lazyown.py.

Auto-generated by scripts/migrate_lazyown.py.
"""
from __future__ import annotations

import cmd2

from cli.commands._base import LazyOwnCommandSet
from cli.commands._dormancy import PendingCommandSet
from utils import (
    print_msg, print_error, print_warn, print_succ,
    check_rhost, check_lhost, check_lport, check_port,
    GREEN, RED, BLUE, MAGENTA, CYAN, YELLOW, WHITE, RESET,
    UNDERLINE, BOLD,
)

class ReconMigratedCommandSet(PendingCommandSet):
    phase = "recon"
    category = "recon_category"

    def do_surface(self, line):
        """Render the network surface graph in the terminal.

        Mirrors the ``vis.js`` graph at ``http://<lhost>:<c2_port>/`` but
        works entirely from the filesystem: it reads the same artefacts
        ``lazyc2.py`` consumes (``sessions/hostsdiscovery.txt``,
        ``sessions/scan_discovery*.csv``, per-implant ``sessions/<id>.log``,
        ``payload.json``) so the operator can inspect the picture from a
        cmd2 shell with no Flask server attached.

        Usage:
            ``surface``         — print a static Rich tree + stats table.
            ``surface --tui``   — open the full-screen Textual explorer.
            ``surface --json``  — emit the graph as JSON.
            ``surface --help``  — show this message.

        :param line: optional flags ``--tui``, ``--json`` or ``--help``.
        :type line: str
        :return: None
        """
        tokens = (line or "").split()
        if "--help" in tokens or "-h" in tokens:
            print_msg(self.do_surface.__doc__ or "")
            return
        sessions_dir = getattr(self, "sessions_dir", "sessions") or "sessions"
        payload_path = "payload.json"
        try:
            from cli.surface_tui import (
                TextualNotInstalled,
            )
            from cli.surface_tui import (
                launch_tui as _surface_launch_tui,
            )
            from cli.surface_tui import (
                render_json as _surface_render_json,
            )
            from cli.surface_tui import (
                render_static as _surface_render_static,
            )
        except ImportError as exc:
            print_error(f"surface renderer unavailable: {exc}")
            return
        if "--json" in tokens:
            print_msg(_surface_render_json(sessions_dir=sessions_dir, payload_path=payload_path))
            return
        if "--tui" in tokens:
            try:
                _surface_launch_tui(sessions_dir=sessions_dir, payload_path=payload_path)
            except TextualNotInstalled as exc:
                print_error(str(exc))
            return
        _surface_render_static(sessions_dir=sessions_dir, payload_path=payload_path)

    def do_getcap(self, line):
        """Retrieve and display file capabilities on the system.

        This function uses the `getcap` command to recursively list capabilities for files starting from the root directory (`/`). The output is filtered to suppress error messages.

        Usage:
            getcap

        :param line: This parameter is not used in this function.
        :type line: str

        :returns: None

        Manual execution:
        1. Run the `getcap -r /` command to list file capabilities recursively from the root directory.
        2. Redirect standard error to `/dev/null` to suppress error messages.
        3. Copy to clipboard the command to appy in the victim machine.
        Dependencies:
        - `getcap` must be installed on the system.

        Example:
            To execute the function, simply call `do_getcap`.

        Note:
            - The command may require elevated permissions to access certain directories and files.
        """
        command = "getcap -r / 2>/dev/null"
        print_msg(f"Try get capabilities {RESET}")
        print_msg(command)
        self.cmd(command)
        copy2clip(command)
        return

    def do_launchpad(self, line):
        """
        Searches for packages on Launchpad based on the provided search term and extracts codenames from the results. The distribution is extracted from the search term.

        :param line: The search term to be used for querying Launchpad. The `line` parameter should be a string containing
                    the search term, e.g., "8.2p1 Ubuntu 4ubuntu0.11".

        :returns: None

        Manual execution:
        To manually execute the equivalent command, use the following steps:

        1. Extract the distribution from the search term:
        - This function assumes the distribution name is part of the search term and is used to build the URL.

        2. URL encode the search term:
        - Replace spaces with `%20` to form the encoded search query.

        3. Use `curl` to perform the search and filter results:
        curl -s "https://launchpad.net/+search?field.text=<encoded_search_term>" | grep 'href' | grep '<distribution>' | grep -oP '(?<=href="https://launchpad.net/<distribution>/)[^/"]+' | sort -u

        Example:
            If the search term is "8.2p1 Ubuntu 4ubuntu0.11", the command would be:
            curl -s "https://launchpad.net/+search?field.text=8.2p1%20Ubuntu%204ubuntu0.11" | grep 'href' | grep 'ubuntu' | grep -oP '(?<=href="https://launchpad.net/ubuntu/)[^/"]+' | sort -u

        Notes:
            - Ensure that `curl` is installed and accessible in your environment.
            - The extracted codenames are printed to the console.
        """

        parts = line.split()
        if len(parts) > 1:
            distribution = parts[1].lower()
        else:
            distribution = "ubuntu"

        encoded_line = quote(line.strip())

        command = f"curl -s \"https://launchpad.net/+search?field.text={encoded_line}\" | grep 'href' | grep '{distribution}' | grep -oP '(?<=href=\"https://launchpad.net/{distribution}/)[^/\"]+' | sort -u"

        print_msg(
            "Searches for packages on Launchpad based on the provided search, no warranties. ssh package give the best results"
        )
        self.cmd(command)

    def do_ping(self, line):
        """Perform a ping to check host availability and infer the operating system based on TTL values.

        :param line: This parameter is not used in the function but could be used for additional options or settings.

        :returns: None

        Manual execution:
        To manually ping a host and determine its operating system, use the following command:

            ping -c 1 <target>

        Example:
            ping -c 1 10.10.10.10

        The TTL (Time To Live) value is used to infer the operating system:
        - TTL values around 64 typically indicate a Linux system.
        - TTL values around 128 typically indicate a Windows system.

        Ensure you have assign `self.params['rhost']` to the target host for the command to work.
        """
        os_json = []
        rhost = self.params['rhost']
        if check_rhost(self.params['rhost']):
            print_msg(f"Try... ping -c 1 {self.params['rhost']} ")
            result = subprocess.run(
                ["ping", "-c", "1", self.params['rhost']], capture_output=True, text=True
            )

            if result.returncode == 0:
                try:
                    ttl_index = result.stdout.find("ttl=")
                    if ttl_index != -1:
                        ttl_value = int(
                            result.stdout[ttl_index + 4 : ttl_index + 7]
                        )
                        print_msg(f"TTL:{ttl_value}")
                        if ttl_value <= 64:
                            print_msg(
                                f"{GREEN}Host alive {CYAN}likely {BLUE}Linux{RESET}"
                            )
                            os_json.append({
                                "id": '1',
                                "os": 'Linux',
                                "ttl": ttl_value,
                                "state": 'active'
                            })
                        elif ttl_value <= 128:
                            print_msg(
                                f"{GREEN}Host alive {CYAN}likely {RED}Windows{RESET}"
                            )
                            os_json.append({
                                "id": '2',
                                "os": 'Windows',
                                "ttl": ttl_value,
                                "state": 'active'
                            })
                        else:
                            print_error(
                                "Cannot determine operating system with certainty"
                            )
                            os_json.append({
                                "id": '4',
                                "os": 'Unknown',
                                "ttl": ttl_value,
                                "state": 'active'
                            })
                    else:
                        print_error("TTL not found in ping output")
                        os_json.append({
                            "id": '4',
                            "os": 'Unknown',
                            "ttl": 'NULL',
                            "state": 'inactive'
                        })
                except ValueError:
                    print_error("Could not convert TTL to an integer")
            else:
                print_error("Ping to host failed")
            print_msg(f"Done... ping -c 1 {self.params['rhost']} ")
            with open('sessions/os.json', 'w') as json_file:
                json.dump(os_json, json_file, indent=4)

            # Persist the detected OS into the live shell params so every
            # subsequent command in this session uses the correct platform.
            # The autonomous loop and tool selectors read os_id from params.
            if os_json:
                detected_os_id = os_json[0].get("id", "4")
                detected_os_name = os_json[0].get("os", "Unknown")
                _apply_assign(self.params, "os_id", detected_os_id, save=_save_payload)
                try:
                    self.aliases.update(_load_aliases(self.params))
                except Exception:
                    pass
                print_msg(f"os_id set to {detected_os_id} ({detected_os_name}) — persisted to payload.json")
        return

    def do_gospider(self, line):
        """Try gospider for web spidering.

        This function executes the `gospider` tool to perform web spidering. It can either use a URL provided as a parameter or the remote host defined in `self.params`.

        Usage:
            gospider url
            gospider

        :param line: Command parameter that determines the execution mode. Use "url" to specify a URL, or leave empty to use the remote host.
        :type line: str

        - If `line` is "url", the method uses the URL specified in `self.params['url']`.
        - If `line` is not "url", the method uses the remote host specified in `self.params['rhost']`.

        :returns: None

        Manual execution:
        1. Ensure that the `gospider` tool is installed on the system.
        2. assign the `url` parameter if using the "url" mode.
        3. Run the method to perform the spidering operation.

        Dependencies:
        - `gospider` must be installed on the system.
        - The `sudo` command must be available for installing `gospider`.

        Examples:
            1. To scan a specific URL: `gospider url`
            2. To scan the remote host: `gospider`

        Note:
            - If `gospider` is not installed, the method will attempt to install it.
            - Ensure that the network and tools are configured correctly for successful execution.
        """
        cmd = f"""{RED}
            ──▐─▌──▐─▌──
            ─▐▌─▐▌▐▌─▐▌─
            ─█▄▀▄██▄▀▄█─
            ──▄──██▌─▄──
            ▄▀─█▀██▀█─▀▄
            ▐▌▐▌─▐▌─▐▌▐▌
            ─▐─█────█─▌─
            ────▌──▐────
        """
        print_msg(cmd)
        rhost = self.params['rhost']
        if line == "url":
            url = self.params['url']
            if not url:
                print_error(
                    "If you pass the param url, url mus be assign, ex: assign url http://url.ext"
                )
                return

            print_msg(f"Try gospider -s {url}")
            self.cmd(f"gospider -s {url}")

            print_msg(cmd)
            return

        if line == "ssl":
            url = self.params['url'].replace("http","https")
            if not url:
                print_error(
                    "If you pass the param url, url mus be assign, ex: assign url http://url.ext"
                )
                return

            print_msg(f"Try gospider -s {url}")
            self.cmd(f"gospider -s {url}")

            print_msg(cmd)
            return

        if not check_rhost(self.params['rhost']):
            return
        if is_binary_present("gospider"):
            print_msg(f"try... gospider -s http://{self.params['rhost']}")
            self.cmd(f"gospider -s http://{self.params['rhost']}")
            print_msg(cmd)
        else:
            print_msg(
                "gospider is not installed, installing... (control + c to cancel)"
            )
            self.cmd(f"sudo apt install gospider -y && gospider -s http://{self.params['rhost']}")
            print_msg(cmd)

    def do_proxy(self, line):
        """
        Runs a small proxy server to modify HTTP requests on the fly.

        This function starts the `lazyproxy.py` script, which acts as a proxy server for intercepting and modifying HTTP requests. The server listens on port 8888.

        Usage:
            proxy

        :param line: This parameter is not used in the current implementation.
        :type line: str
        :returns: None

        Manual execution:
        1. Executes the `lazyproxy.py` script to start the proxy server.
        2. The proxy server will run and modify requests as configured in the script.

        Dependencies:
        - The `lazyproxy.py` script must be available in the `modules` directory.

        Example:
            proxy

        Note:
            - Ensure that the `lazyproxy.py` script is correctly configured before running.
            - The proxy server will be accessible at `http://localhost:8888`.
            - To stop the proxy server, terminate the running process manually.
        """


        print_msg("Running Lazy Proxy ...")
        self.cmd("python3 modules/lazyproxy.py")
        print_msg(
            f"{YELLOW} Shutdown proxy server at sessions in port {RED} 8888 {RESET}"
        )
        return

    def do_ports(self, line):
        """
        Lists all open TCP and UDP ports on the local system.

        This function performs the following actions:
        1. Calls the `get_open_ports` function to retrieve lists of open TCP and UDP ports.
        2. Prints a header for open TCP ports.
        3. Iterates over the list of open TCP ports, printing each IP address and port number.
        4. Prints a header for open UDP ports.
        5. Iterates over the list of open UDP ports, printing each IP address and port number.

        Usage:
            ports

        :param line: This parameter is not used in the function.
        :type line: str
        :returns: None

        Manual execution:
        To manually use this function:
        1. Ensure the `get_open_ports` function is defined and properly implemented to return lists of open TCP and UDP ports.
        2. Run the function to display open TCP and UDP ports on the local system.

        Note: The `get_open_ports` function should return two lists of tuples: one for TCP ports and one for UDP ports. Each tuple should contain an IP address and a port number.
        """
        tcp_ports, udp_ports = get_open_ports()
        print_msg(f"Open TCP Ports:{RESET}")
        print_warn("To enter use Ctrl + Clic: ")
        for ip, port in tcp_ports:
            print_msg(f"{CYAN}{ip}{YELLOW}:{BLUE}{port}{RESET}")
            print_msg(f"{BLUE}{UNDERLINE}https://www.speedguide.net/port.php?port={port}")
        print_msg(f"{GREEN}Open UDP Ports:{RESET}")
        print_warn("To enter use Ctrl + Clic: ")
        for ip, port in udp_ports:
            print_msg(f"{CYAN}{ip}{YELLOW}:{BLUE}{port}{RESET}")
            print_msg(f"{BLUE}{UNDERLINE}https://www.speedguide.net/port.php?port={port}")
        command = "ss -ntlp"
        print_msg(f"Try... {command}")
        self.cmd(command)
        return

    def do_tcpdump_icmp(self, line):
        """
        Starts `tcpdump` to capture ICMP traffic on the specified interface.

        1. Checks if the `line` argument (interface) is provided:
        - Displays an error message and exits if the interface is missing.

        2. If the interface is provided:
        - Displays the `tcpdump` command that will be executed.
        - Runs the `tcpdump` command to capture ICMP traffic on the specified interface.

        :param line: The network interface on which to capture ICMP traffic (e.g., `tun0`).
        :type line: str
        :returns: None

        Manual execution:
        To manually run these tasks, you would need to:
        - Provide a valid network interface for capturing ICMP traffic.
        - Execute the `tcpdump` command manually to capture ICMP traffic on the specified interface.

        Note: Ensure that you have sufficient permissions to run `tcpdump` on the specified interface.
        """

        if not line:
            print_error(
                "necesitas pasarle la interfaz que se quedarà en escucha ej: tcpdump_icmp tun0"
            )
            return
        print_msg(f"{WHITE}sudo tcpdump -i {GREEN}{line}{WHITE}{CYAN} icmp -n{RESET} ")
        self.cmd(f"sudo tcpdump -i {line} icmp -n")
        return

    def do_tcpdump_capture(self, line):
        """
        Starts packet capture using `tcpdump` on the specified interface.

        1. Checks if the `line` argument (interface) is provided:
        - Displays an error message and exits if the interface is missing.

        2. Validates the `self.params['rhost']` (remote host IP):
        - Exits the function if the `self.params['rhost']` is not valid.

        3. If the interface and `self.params['rhost']` are valid:
        - Displays the `tcpdump` command that will be executed.
        - Runs the `tcpdump` command to capture packets on the specified interface and save the capture file to `pcaps/capture_<self.params['rhost']>.pcap`.

        :param line: The network interface on which to capture packets (e.g., `tun0`).
        :type line: str
        :returns: None

        Manual execution:
        To manually run these tasks, you would need to:
        - Provide a valid network interface for capturing packets.
        - Ensure the remote host IP is assign correctly.
        - Execute the `tcpdump` command manually to capture packets on the specified interface.

        Note: Ensure that the `pcaps` directory exists and is writable for saving the capture file.
        """

        if not line:
            print_error(
                "necesitas pasarle la interfaz que se quedarà en escucha ej: tcpdump_icmp tun0"
            )
            return
        rhost = self.params['rhost']
        if not check_rhost(self.params['rhost']):
            return

        print_msg(f"{WHITE}sudo tcpdump -i {GREEN}{line}{WHITE}{CYAN} -w pcaps/capture_{self.params['rhost']}.pcap {RESET} ")
        self.cmd(f"sudo tcpdump -i {line}  -w pcaps/capture_{self.params['rhost']}.pcap ")
        return

    def do_tshark_analyze(self, line):
        """
        Analyzes a packet capture file using `tshark` based on the provided remote host IP.

        1. Checks if the `self.params['rhost']` (remote host IP) is valid:
        - Displays an error message and exits if the `self.params['rhost']` is not valid.

        2. Verifies the existence of the packet capture file:
        - Displays an error message and exits if the capture file is missing.
        - Prompts the user to run the `do_tcpdump_capture` command first.

        3. If the capture file exists:
        - Displays the `tshark` command that will be executed.
        - Runs the `tshark` command to analyze the packet capture file and print out IP destination and frame time fields.

        :param line: The command line input specifying the interface for capturing packets.
        :type line: str
        :returns: None

        Manual execution:
        To manually run these tasks, you would need to:
        - Ensure the remote host IP is valid.
        - Run the `do_tcpdump_capture` command to capture packets.
        - Execute the `tshark` command manually to analyze the packet capture file.

        Note: Ensure that the capture file `pcaps/capture_<self.params['rhost']>.pcap` is available in the `pcaps` directory.
        """

        pcaps_dir = 'pcaps'
        all_items = os.listdir(pcaps_dir)

        for item in all_items:
            item_path = os.path.join(pcaps_dir, item)

            try:
                if os.path.isfile(item_path):
                    print_msg("Analizing...")

                    rhost = self.params['rhost']
                    if not check_rhost(self.params['rhost']):
                        return

                    pcap_file = item_path
                    if not os.path.exists(pcap_file):
                        print_error("you must run command do_tcpdump_capture tun0 first.")
                        return
                    if os.path.splitext(pcap_file)[1].lower() == '.pcap':

                        command = f'tshark -r {pcap_file} -T fields -e frame.number -e frame.time -e frame.len -e ip.src -e ip.dst -e ip.proto -e tcp.srcport -e tcp.dstport -e udp.srcport -e udp.dstport -e http.request.uri -e http.response.code -e ftp.request.command -e ftp.request.arg -e dns.qry.name '
                        print_msg(command)
                        self.cmd(command)
                        command = f'tshark -r {pcap_file} -q -z conv,tcp,ip '
                        print_msg(command)
                        self.cmd(command)
                        command = f"tshark -r {pcap_file} -Y 'ftp.request.command == USER || ftp.request.command == PASS' -T fields -e ip.dst -e frame.time -e ftp.request.command -e ftp.request.arg"
                        print_msg(command)
                        self.cmd(command)
                    else:
                        print_error("No pcap files found in pcaps directory")

            except Exception as e:
                print_error(f"Failed to delete {item_path}: {e}")

        return

    def do_waybackmachine(self, line):
        """
        Fetch URLs from the Wayback Machine for a given website.
        The URL is taken from line. If the URL is not provided, an error is printed.
        The limit of results is taken from self.params['limit'] if provided; otherwise, defaults to 10.
        Results are printed directly to the console.
        """
        if not line:
            print_error("you need pass the search keyword as argument")
            return
        url = line
        limit = self.params.get("limit", 10)

        wayback_url = (
            f"https://web.archive.org/cdx/search?url={url}&matchType=prefix&collapse=urlkey&output=text&fl=original&filter=&limit={limit}"
        )

        headers = {
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0) Gecko/20100101 Firefox/68.0"
        }
        self.cmd("clear")

        try:
            r = requests.get(wayback_url, headers=headers)
            r.raise_for_status()
            results = r.text



            print_msg(f"{GREEN}############ All websites from the WayBack Machine ###########")

            for j, i in enumerate(results.split(), start=1):
                print_msg(f"{j} : {i}")
            print_msg(f"{CYAN}https://web.archive.org/web/*/{line}/*")
            print_msg(f"{CYAN}############## Thanks for using LazyOwn! ###############")

        except requests.exceptions.RequestException as e:
            print_warn(f"Warning: Failed to fetch data from the Wayback Machine. {str(e)}")

    def do_sslscan(self, line):
        """
        Run an SSL scan on the specified remote host.

        This function initiates an SSL scan on a specified remote host (`self.params['rhost']`)
        using the `sslscan-singleip.sh` script. If a specific port is provided in the
        `line` argument, the scan will target that port; otherwise, it will scan
        all available ports.

        Parameters:
        line (str): The port number to scan (optional). If omitted, the scan will target all ports.

        Internal Variables:
        self.params['rhost'] (str): The remote host IP address or hostname extracted from the `params` attribute.

        Returns:
        None

        Example Usage:
        - To scan all ports on the specified `self.params['rhost']`: `sslscan`
        - To scan a specific port (e.g., port 443) on `self.params['rhost']`: `sslscan 443`

        Note:
        - The `check_rhost()` function is used to validate the `self.params['rhost']` before running the scan.
        - The `sslscan-singleip.sh` script must be present in the `sessions` directory.
        """
        rhost = self.params['rhost']
        if not check_rhost(self.params['rhost']):
            return

        if not line:
            port = ""
        else:
            port = ":"+line

        command = f"cd sessions && ./sslscan-singleip.sh {self.params['rhost']}{port}"
        print_msg(f"Attempting to execute: {command}")
        self.cmd(command)
        return

    def do_graudit(self, line):
        """
        Executes the graudit command to perform a static code analysis with the specified options.

        This function runs the 'graudit' tool with the '-A' option for an advanced scan and
        the '-i sessions' option to include session files. The results will be displayed
        directly in the terminal.

        Args:
            line (str): Input line from the command interface. This argument is currently
                        not used within the function but is required for the command
                        interface structure.

        Example:
            To run this function from the command interface, simply type 'graudit' and press enter.
            The function will execute the 'graudit -A -i sessions' command.

        Note:
            Ensure that 'graudit' is installed and properly configured in your system's PATH
            for this function to work correctly.
        """

        if not is_binary_present("graudit"):
            print_warn("Installing graudit...")
            self.cmd("sudo apt install graudit -y")

        command = "graudit -A -i sessions"
        self.cmd(command)
        return

    def do_sherlock(self, line):
        """
        Executes the Sherlock tool to find usernames across social networks.

        This function takes a username as an argument and runs the Sherlock tool
        to check for the username's presence on various social networks. The
        results are saved in CSV format in the `sessions` directory.

        Parameters:
        line (str): The username to be checked by Sherlock. If not provided, an
                    error message is printed and the function returns.

        Returns:
        None

        Raises:
        None

        Example:
        >>> do_sherlock("example_user")
        Running command: sherlock example_user --local -v --csv --print-found

        Additional Notes:
        - The Sherlock tool must be installed and available in the system path.
        - The results are saved in the `sessions` directory as a CSV file.
        - The `--local` flag forces the use of a local `data.json` file,
        which should be present in the appropriate directory.
        """
        if not is_binary_present("sherlock"):
            print_warn("installing sherlock...")
            self.cmd("sudo apt install sherlock -y")

        if not line:
            print_error("You must pass the username like argument.")
            return
        command = f"cd sessions && sherlock {line} --local -v --csv --print-found"
        print_msg(f"sherlock {line} --local -v --csv --print-found")
        self.cmd(command)
        return

    def do_trufflehog(self, line):
        """
        Executes trufflehog to search for secrets in a given Git repository URL.
        If trufflehog is not installed, it installs the tool automatically.
        This function navigates to the 'sessions' directory and runs trufflehog
        with the provided Git URL, outputting the results in JSON format.

        Args:
            line (str): The Git repository URL to scan for secrets.

        Returns:
            None

        Raises:
            None

        Example:
            trufflehog https://github.com/user/repo.git

        Notes:
            - Ensure that trufflehog is installed or it will be installed automatically.
            - The output of the trufflehog scan is printed and executed in the 'sessions' directory.
        """

        if not is_binary_present("trufflehog"):
            print_warn("installing trufflehog...")
            self.cmd("sudo apt install trufflehog -y")

        if not line:
            print_error("You must pass the git url like argument.")
            return

        command = f"cd sessions && trufflehog git {line} --json"
        print_msg(f"trufflehog git {line} --json")
        self.cmd(command)
        return

    def do_apache_users(self, line):
        """
        Performs enumeration of users from a target system using `apache-users`.

        1. Executes the `apache-users` command with the `-h` option to specified target.

        :param line: This parameter is not used in the current implementation but could be used to pass additional options or arguments if needed.
        :param self.params['rhost']: The target host for enumeration, specified in the `params` dictionary.

        :returns: None

        Manual execution:
        To manually enumerate information from a system, use the following command:
            apache-users -h <target_host> -l <wordlist> -p <apache_port> -s 0 -e 403 -t 10

        Replace `<target_host>` with the IP address or hostname of the target system.

        For example:
            apache-users -h 192.168.1.202 -l /usr/share/wordlists/metasploit/unix_users.txt -p 80 -s 0 -e 403 -t 10
        """

        if not is_binary_present("apache-users"):
            print_warn("Installing apache-users...")
            self.cmd("sudo apt install apache-users -y")

        usrwordlist = self.params['usrwordlist']
        if not usrwordlist:
            print_error("User wordlist must be assigned, use: assign usrwordlist /path/to/wordlist")
            return

        if line:
            rhost = line
        else:
            rhost = self.params['rhost']
            if not check_rhost(self.params['rhost']):
                return

        rhost = self.params['rhost']
        users = get_users_dic()
        print_msg(f"Try... apache-users -h  {self.params['rhost']} -l {users} -p 80 -s 0 -e 403 -t 10 {RESET}")
        self.cmd(f"apache-users -h  {self.params['rhost']} -l {users} -p 80 -s 0 -e 403 -t 10")
        if input("    [?] Do you want extend the userenum ? (y/n)") == 'y':
            print_msg(f"Try... apache-users -h  {self.params['rhost']} -l {usrwordlist} -p 80 -s 0 -e 403 -t 10 {RESET}")
            self.cmd(f"apache-users -h  {self.params['rhost']} -l {usrwordlist} -p 80 -s 0 -e 403 -t 10")
        return

    def do_trace(self, line):
        """
        Traces the DNS information for a given self.params['domain'] using the FreeDNS service. (using freedns IP Not your IP)

        This method performs a DNS trace lookup for the specified self.params['domain'] by
        sending an HTTP GET request to the FreeDNS service. If no self.params['domain'] is provided
        in the input parameter `line`, it defaults to using the URL specified in the
        instance's parameters.

        Parameters:
        line (str): The self.params['domain'] name to trace. If not provided, the method uses the
                    self.params['domain'] extracted from `self.params['url']`.

        Returns:
        None: This method executes a system command and does not return a value.

        Example:
        >>> self.do_trace("example.com")
        Executes a DNS trace for "example.com".

        Notes:
        - Ensure that the `self.params['url']` is set with a valid URL if no self.params['domain']
        is provided.
        - The method uses `os.system` to execute the trace command, which may not
        be the most secure or efficient method for production code. Consider using
        a library like `requests` for HTTP operations if security and efficiency
        are concerns.
        """
        if not line:
            url = self.params['url']
            domain = get_domain(url)
        else:
            domain = line
        if not is_binary_present("batcat"):
            print_warn("Installing batcat")
            self.cmd("sudo apt install bat -y")

        command = f"curl -s -X GET https://freedns.afraid.org/self.params['domain']/dnstrace.php\\?self.params['domain']\\={self.params['domain']}\\&submit\\=Trace | batcat"
        print_msg(command)
        self.cmd(command)
        return

    def do_alterx(self, line):
        """
        Executes the 'alterx' command for subdomain enumeration on the provided self.params['domain']. If 'alterx'
        is not installed, the function automatically downloads, installs, and configures it. The result
        of the subdomain enumeration is saved in a session-specific text file.

        Steps performed by the function:

        1. **Check if 'alterx' is installed:**
        - Uses `is_binary_present("alterx")` to verify if the 'alterx' binary is available in the system.
        - If the binary is not found, the function prints a warning and proceeds to download and install 'alterx'.

        2. **Installation of 'alterx':**
        - Executes a system command to create a directory named 'alterx' in the user's home directory.
        - Downloads the 'alterx' version 0.0.4 (Linux 64-bit) from GitHub and extracts it into the 'alterx' directory.

        3. **Add 'alterx' to system PATH:**
        - Depending on the user's shell (`bash` or `zsh`), it appends the 'alterx' directory to the system PATH
            by modifying the appropriate shell configuration file (`~/.bashrc` or `~/.zshrc`). This ensures 'alterx'
            can be executed from any directory.

        4. **Obtain the self.params['domain']:**
        - Retrieves the URL from the class parameter `self.params['url']`.
        - Extracts the self.params['domain'] from the URL using `get_domain(url)`.
        - If no self.params['domain'] is provided as an argument in `line`, prompts the user to input a self.params['domain'], defaulting to
            the previously extracted self.params['domain'].

        5. **Execute 'alterx' on the self.params['domain']:**
        - Executes the 'alterx' tool on the specified self.params['domain'] via a system command.
        - The subdomain enumeration results are saved to a file in the 'sessions' directory, with the filename
            `subdomain_dic_<self.params['domain']>.txt`.

        Parameters:
        - line (str): The self.params['domain'] on which to run 'alterx'. If empty, the function prompts the user for input.

        Returns:
        - None: The function performs its operations but does not return any value.

        Dependencies:
        - The function relies on the external tool 'alterx' and assumes the presence of the `is_binary_present()`
        and `get_domain()` helper functions.
        """
        if not is_binary_present("alterx"):
            print_warn("alterx not found. Installing...")
            command = "cd && mkdir alterx && cd alterx && wget https://github.com/projectdiscovery/alterx/releases/download/v0.0.4/alterx_0.0.4_linux_amd64.zip && unzip alterx_0.0.4_linux_amd64.zip"
            self.cmd(command)
            command = """
            bash -c '
            if [[ "$SHELL" == */bash ]]; then
                echo "    [!] Bash"
                echo "export PATH=$PATH:~/alterx" >> ~/.bashrc
            elif [[ "$SHELL" == */zsh ]]; then
                echo "    [!] Zsh"
                echo "export PATH=$PATH:~/alterx" >> ~/.zshrc
            fi
            '
            """.replace("            ", "")
            os.system(command)

        url = self.params['url']
        domain = get_domain(url)
        if not line:
            line = input(f"    [!] Enter the self.params['domain']: (Default: {self.params['domain']})") or self.params['domain']

        command = f"echo {line} | alterx > sessions/subdomain_dic_{line}.txt"
        print_msg(command)
        self.cmd(command)
        return

    def do_windapsearchscrapeusers(self, line):
        """
        Extracts usernames from a JSON output generated by go-windapsearch and appends them
        to the file sessions/users.txt.

        The function loads the JSON file, parses the `sAMAccountName` attribute for each user, and appends
        the username to the sessions/users.txt file.

        :param line: Path to the JSON file (e.g., 'sessions/<dc_ip>_windap.json').
        :returns: None
        """
        json_file = line.strip()

        if not os.path.exists(json_file):
            print_error(f"Error: El archivo {json_file} no existe.")
            return

        try:
            with open(json_file, 'r') as f:
                data = json.load(f)

            user_file = "sessions/users.txt"
            with open(user_file, 'a') as uf:
                for entry in data:
                    if 'sAMAccountName' in entry:
                        uf.write(entry['sAMAccountName'] + '\n')
                        print_msg(f"Agregado usuario: {entry['sAMAccountName']}")

            print_msg(f"Todos los usuarios se han agregado a {user_file}.")

        except json.JSONDecodeError:
            print_error(f"Error: Could not decode {json_file}. Make sure it is valid JSON.")
        except Exception as e:
            print_error(f"Error: {str(e)}")

    def do_cve(self, line):
        """
        Search for a CVE using the CIRCL API.

        This function sends a GET request to the CIRCL API to retrieve CVE details
        and prints relevant information to the screen.

        :param line: A string containing the CVE ID (optional).
        :returns: None
        """
        if not line.strip():
            line = generate_random_cve_id()
            print_msg(f"No CVE ID provided. Generated ID: {line}")

        url = f"https://cve.circl.lu/api/cve/{line}"

        try:
            response = requests.get(url)

            if response.status_code != 200:
                print_error(f"Failed to retrieve data: HTTP {response.status_code}")
                return

            cve_data = response.json()

            cwe = cve_data.get("cwe", "No CWE info")
            cve_id = cve_data.get("id", "No ID")
            references = cve_data.get("references", [])
            summary = cve_data.get("summary", "No summary available")
            assigner = cve_data.get("assigner", "No assigner info")
            published = cve_data.get("Published", "No publish date")
            modified = cve_data.get("Modified", "No modification date")

            print_msg(f"[*] CWE: {cwe}")
            print_msg(f"[*] ID: {cve_id}")
            print_msg(f"[*] References: {', '.join(references) if references else 'No references'}")
            print_msg(f"[*] Summary: {summary}")
            print_msg(f"[*] Assigner: {assigner}")
            print_msg(f"[*] Published: {published}")
            print_msg(f"[*] Modified: {modified}")

        except requests.exceptions.RequestException as req_e:
            print_error(f"A request error occurred: {req_e}")
        except ValueError as json_e:
            print_error(f"Error parsing JSON response: {json_e}")
        except Exception as e:
            print_error(f"An error occurred: {e}")

    def do_serveralive2(self, line):
        """
        Command serveralive2: Uses Impacket to connect to a remote MSRPC interface and retrieves the server bindings.

        This function allows the user to:
        1. Establish a connection to a remote MSRPC interface using a specified target from self.params['rhost'].
        2. Set the authentication level to none.
        3. Retrieve and print the network addresses from the server bindings using the IObjectExporter.

        Args:
            line (str): Unused in this context. The target is derived from self.params['rhost'].

        Returns:
            None

        Example:
            serveralive2
        """

        target = f"ncacn_ip_tcp:{self.params['rhost']}"
        rpcTransport = transport.DCERPCTransportFactory(target)
        portmap = rpcTransport.get_dce_rpc()
        portmap.set_auth_level(RPC_C_AUTHN_LEVEL_NONE)
        portmap.connect()

        obj = IObjectExporter(portmap)
        bindings = obj.ServerAlive2()

        for binding in bindings:
            addr = binding['aNetworkAddr']
            print_msg(f"Address: {addr}")
        return

    def do_binarycheck(self, line):
        """
        Performs various checks on a selected binary to gather information and protections.

        This function executes the following checks:
        1. Checks program protections using checksec.
        2. Displays information about the ELF binary using readelf.
        3. Retrieves the address of the system() function using objdump.
        4. Searches for a known string within the binary using objdump.
        5. Generates a cyclic pattern for padding using pwntools.
        6. Lists gadgets in the binary using ROPgadget.

        Parameters:
        line (str): Command argument not used in this function.

        Returns:
        None
        """

        binaries_list = list_binaries()
        if not binaries_list:
            print_error("No binaries found in the specified directory.")
            return

        selected_binary = select_binary(binaries_list)

        print_msg(f"Checking protections for {selected_binary}...")
        self.cmd(f"checksec --file {selected_binary}")

        print_msg(f"Getting ELF information for {selected_binary}...")
        self.cmd(f"readelf -a {selected_binary}")

        print_msg(f"Getting system() address for {selected_binary}...")
        self.cmd(f"objdump -D {selected_binary} | grep system")

        print_msg(f"Looking for known strings in {selected_binary}...")
        self.cmd(f"objdump -s {selected_binary} | grep 'GNU'")

        print_msg(f"Generating padding using pwntools for {selected_binary}...")


        print_msg(f"Listing gadgets for {selected_binary}...")
        self.cmd(f"env/bin/ROPgadget --binary {selected_binary}")

    def do_dnstool_py(self, line):
        """
        Executes the dnstool.py tool to modify Active Directory-integrated DNS records.

        This function performs the following actions:
        1. Checks if Krbrelayx is installed; if not, it clones the repository and installs dependencies.
        2. Modifies DNS records by adding, removing, or querying based on the specified options.

        Parameters:
        line (str): Command arguments specifying the DNS action, target record, and data.
                    Expected format:
                        - hostname user password record action -options
                        - Options include:
                        - -a to add a record
                        - -r to remove a record
                        - --forest to target ForestDnsZones

        Returns:
        None
        """
        path = os.getcwd()
        krbrelayx_git = "https://github.com/dirkjanm/krbrelayx.git"
        krbrelayx_path = os.path.join("external", ".exploit", "krbrelayx")
        krbrelayx_path = f"{path}/{krbrelayx_path}"

        if not os.path.exists(krbrelayx_path):
            self.cmd(f"git clone {krbrelayx_git} {krbrelayx_path}")
            self.cmd("pip3 install impacket ldap3 dnspython")


        subdomain = self.params['subdomain']
        domain = self.params['domain']
        lhost = self.params['lhost']
        credentials = get_credentials()

        if not credentials:
            print_error("Credentials required. Use: createcredentials admin:admin")
            return

        for user, password in credentials:
            dns_command = f"python3 {krbrelayx_path}/dnstool.py -u {self.params['domain']}\\\\{user} -p {password} --zone {self.params['domain']} -r {subdomain}.{self.params['domain']} -a add -t A -d {self.params['lhost']} {self.params['domain']}"
            print_msg(dns_command)
            self.cmd(dns_command)
        return

    def do_metabigor(self, line):
        """
        Executes Metabigor commands for OSINT and scanning tasks with guided input or predefined arguments.

        This function performs the following actions:
        1. Verifies the presence of Metabigor; if not installed, it clones the repository and installs the required dependencies.
        2. Guides the user through selecting the type of task (IP discovery, related domains, scan, etc.), target, and additional parameters.
        3. Constructs and executes the appropriate Metabigor command based on the user's input or the provided argument.

        Parameters:
        line (str): Command-line arguments for Metabigor. If not provided, interactive input will be used.

        Returns:
        None
        """
        path = os.getcwd()
        metabigor_path = os.path.join("external", ".exploit", "metabigor")
        metabigor_path = f"{path}/{metabigor_path}"
        metabigor_repo = "https://github.com/j3ssie/metabigor.git"
        rhost = self.params['rhost']
        if not os.path.exists(metabigor_path):
            print_warn("Metabigor is not installed. Cloning the repository and installing dependencies.")
            self.cmd(f"git clone {metabigor_repo} {metabigor_path}")
            os.chdir(metabigor_path)
            self.cmd("go install")
            print_msg("Metabigor installation completed.")
            os.chdir(path)

        if line:
            echo_command = f'echo "{line}" | metabigor net --org -o {path}/sessions/result_{line}.txt'
            print_msg(f"Executing Metabigor with command: {echo_command}")
            self.cmd(echo_command)
            return

        task_types = {
            "1": "Discovery IP of a company/organization",
            "2": "Discovery IP of an ASN",
            "3": "Find related domains using certificate info",
            "4": "Run scan with rustscan, masscan, or nmap",
            "5": "Get IP address summary",
            "6": "Extract Shodan IPInfo"
        }

        print_msg("Select the type of task to perform:")
        for key, description in task_types.items():
            print_msg(f"  {key}. {description}")

        task_choice = input("    [!] Enter the number corresponding to your choice (default: 1): ").strip() or "1"
        task = task_types.get(task_choice, "1")

        if task == "Discovery IP of a company/organization":
            target = input("    [!] Enter the organization name: ").strip()
            command = f"echo \"{target}\" | metabigor net --org -o {path}/sessions/result_{target}.txt"
        elif task == "Discovery IP of an ASN":
            target = input("    [!] Enter the ASN: ").strip()
            command = f"echo \"{target}\" | metabigor net --asn -o {path}/sessions/result_{target}.txt"
        elif task == "Find related domains using certificate info":
            target = input("    [!] Enter the company/organization name: ").strip()
            command = f"echo \"{target}\" | metabigor related -s 'cert' -o {path}/sessions/result_{target}.txt"
        elif task == "Run scan with rustscan, masscan, or nmap":
            target = input(f"    [!] Enter the target IP/CIDR (e.g., {self.params['rhost']}/24: ").strip() or f"{self.params['rhost']}/24"
            command = f"echo \"{target}\" | metabigor scan -o {path}/sessions/result_{target}.txt"
        elif task == "Get IP address summary":
            target = input(f"    [!] Enter the IP address {self.params['rhost']}: ").strip() or self.params['rhost']
            command = f"echo \"{target}\" | metabigor ipc --json -o {path}/sessions/result_{target}.txt"
        elif task == "Extract Shodan IPInfo":
            target = input(f"    [!] Enter the IP address: {self.params['rhost']}: ").strip() or self.params['rhost']
            command = f"echo \"{target}\" | metabigor ip -open -o {path}/sessions/result_{target}.txt"

        print_msg(f"Executing Metabigor with command: {command}")
        self.cmd(command)
        self.logcsv(f"metabigor {command}")
        os.chdir(path)
        return

    def do_httprobe(self, line):
        """
        Executes the httprobe tool to probe domains for working HTTP and HTTPS servers.

        This function performs the following actions:
        1. Verifies if httprobe is installed; if not, it installs the tool automatically.
        2. Probes domains from the input file or standard input.
        3. Simplifies the user experience by minimizing required commands and leveraging self.params for defaults.

        Parameters:
        line (str): Optional command arguments specifying the self.params['domain'] or just httprobe.
                    Example usage:
                    just provide the self.params['domain']: httprobe example.com

        Returns:
        None
        """

        httprobe_binary = "httprobe"
        domain = self.params['domain']
        install_command = "go install github.com/tomnomnom/httprobe@latest"
        if not os.path.exists(os.path.expanduser("~/go/bin/httprobe")):
            self.cmd(install_command)

        input_file = get_users_dic('txt')
        http = input("    [!] Enter the http port default 80: ") or '80'
        https = input("    [!] Enter the https port default 443: ") or '443'
        concurrency = input("    [!] Enter the concurrency level default 50: ") or '50'
        timeout = input("    [!] Enter the Timeout in milisecs default 20000: ") or '20000'
        additional_params = f" -p http:{http} -p https:{https} -c {concurrency} -t {timeout}"
        if line:
            command = f"echo \"{line.strip()}\" | {httprobe_binary} {additional_params}"
        else:
            if input_file is not None:
                command = f"cat {input_file} | {httprobe_binary} {additional_params}"
            else:
                command = f"echo \"{self.params['domain']}\" | {httprobe_binary} {additional_params}"
        print_msg(command)
        self.cmd(command)
        self.logcsv(f"httprobe {command}")
        return

    def do_recon(self, line):
        """
        Performs reconnaissance on a specified self.params['domain'] using crt.sh (the target must be visible on internet), pup, httprobe, and EyeWitness.

        This function automates the process of gathering subdomains for a given self.params['domain'], verifying
        their reachability, and generating a report using the EyeWitness tool.

        Workflow:
            1. Determines the target self.params['domain'] from the `line` argument or defaults to `self.params['domain']`.
            2. Queries the crt.sh certificate transparency logs for subdomains using `curl`.
            3. Filters and extracts self.params['domain']-related text data using `pup`.
            4. Sorts and removes duplicate entries, then validates subdomains with `httprobe`.
            5. Saves the results to a temporary file.
            6. Executes EyeWitness to generate a web-based reconnaissance report for the subdomains.

        Requirements:
            - `pup`: A command-line HTML parser.
            - `httprobe`: A tool to check live HTTP/HTTPS endpoints.
            - EyeWitness: A tool for generating web reconnaissance reports.

        Parameters:
            line (str): The self.params['domain'] to target for reconnaissance. If omitted, the self.params['domain'] defaults to `self.params['domain']`.

        Examples:
            1. Specify a self.params['domain'] directly:
                >>> recon self.params['domain'].com

            2. Use the default self.params['domain'] from self.params:
                >>> recon
        Raises:
            None. Errors in execution will be logged or printed as part of the command output.

        """
        path = os.getcwd()
        sessions = f"{path}/sessions"
        eyewitness_path = os.path.join("external", ".exploit", "EyeWitness")
        eyewitness_path = path + "/" + eyewitness_path

        if line:
            domain = line.strip()
        else:
            domain = self.params['domain']

        command_eye = "/usr/share/eyewitness/EyeWitness.py "
        command = "domain={dom};curl -fsSL \"https://crt.sh/?q=${self.params['domain']}\" | pup 'td text{}' | grep \"${self.params['domain']}\" | sort -n | uniq | httprobe > {sessions}/enum_tmp_{dom}.txt;  {command_eye} -f {sessions}/enum_tmp_{dom}.txt --web".replace("{dom}", self.params['domain']).replace("{command_eye}",command_eye).replace("{sessions}",sessions)

        print_msg(command)
        time.sleep(1)
        self.cmd(command)
        print_msg(command)
        self.logcsv(f"recon {command}")
        return

    def do_dnschef(self, line):
        """
        Executes the DNSChef tool to monitor DNS queries and intercept responses.

        This function:
            - Installs DNSChef if not already installed.
            - Executes the DNSChef command with the provided parameters.
            - Displays the result in the terminal.

        Behavior:
            - Requires `python3`, `python3-pip`, and `git` to be installed.
            - Uses parameters from `self.params` for self.params['domain'], username, password, and target.

        Usage:
            dnschef
        """
        path = os.getcwd()
        dnschef_repo = "https://github.com/iphelix/dnschef.git"
        dnschef_path = os.path.join(path, "external", ".exploit", "dnschef")

        try:
            if not os.path.exists(dnschef_path):
                print_msg("DNSChef is not installed. Installing...")
                self.cmd(f"git clone {dnschef_repo} {dnschef_path}")
                self.cmd(f"cd {dnschef_path} && pip3 install -r requirements.txt")

            rhost = self.params['rhost']
            domain = self.params['domain']
            command = f"sudo python3 -W ignore {dnschef_path}/dnschef.py --fakeip {self.params['rhost']} --fakedomains {self.params['domain']}"
            self.cmd(command)
        except Exception as e:
            print_error(f"Error: {e}")
        return

    def do_ipinfo(self, line):
        """
        Retrieves detailed information about an IP address using the ARIN API.

        This function takes an IP address as input, queries the ARIN API to get detailed
        information about the IP, and then displays the organization name and the network
        range associated with the IP.

        Args:
            line (str): The command line input containing the IP address to query.

        Returns:
            None

        Raises:
            None

        Example:
            >>> ipinfo 1.1.1.1
        """
        ip = line.strip()
        if not ip:
            print_error("Error: Please provide an IP address.")
            return

        data = query_arin_ip(ip)
        if not data:
            print_error(f"No information found for IP: {ip}")
            return

        if not data.get("net"):
            print_error(f"Formato de respuesta inesperado de la API de ARIN para la IP: {ip}")
            return

        name = get_org(data)
        try:
            net_blocks = data.get("net", {}).get("netBlocks", [])
            if net_blocks:
                netblock = net_blocks[0].get("netBlock", {})
                start_address = netblock.get("$", {}).get("startAddress")
                cidr_length = netblock.get("$", {}).get("cidrLength")

                if start_address and cidr_length:
                    range = f"{start_address}/{cidr_length}"
                else:
                    range = "N/A (Error incomplete info)"
            else:
                range = "N/A (No network blocks)"
        except (KeyError, AttributeError, IndexError) as e:
            print_warn(f"Error IP: {ip}. Error code: {e}")
            range = "N/A (Error)"

        print_msg(f"[!] {ip}")
        print_msg(f" |_ {name}")
        print_msg(f" \\_ {range}")
        return

__all__ = [f"{phase.title()}CommandSet"]