#!/usr/bin/env bash
# =============================================================================
# LazyOwn MCP — One-time system setup
# Configures sudoers NOPASSWD and Linux capabilities so LazyOwn tools can run
# without interactive password prompts (required for MCP / non-TTY contexts).
#
# Usage:  bash skills/setup.sh
#
# Safe to re-run — all operations are idempotent.
# Supported: Debian/Ubuntu/Kali, Arch, Fedora/RHEL, macOS (capabilities skipped)
# =============================================================================
set -euo pipefail

RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; RESET='\033[0m'
info()  { echo -e "${GREEN}[+]${RESET} $*"; }
warn()  { echo -e "${YELLOW}[!]${RESET} $*"; }
die()   { echo -e "${RED}[-]${RESET} $*" >&2; exit 1; }

# ── Sanity checks ─────────────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] || die "Do NOT run as root. Run as your normal user: bash skills/setup.sh"
command -v sudo >/dev/null 2>&1 || die "sudo not found."

CURRENT_USER="$(whoami)"
info "Setting up LazyOwn MCP for user: ${CURRENT_USER}"
echo

# ── 1. Linux capabilities (replaces sudo for raw-socket tools) ────────────────
if [[ "$(uname)" == "Linux" ]]; then
    info "Setting Linux capabilities (raw socket access without sudo)..."

    declare -A CAPS=(
        ["/usr/bin/nmap"]="cap_net_raw,cap_net_admin=eip"
        ["/usr/bin/masscan"]="cap_net_raw,cap_net_admin=eip"
        ["/usr/bin/tcpdump"]="cap_net_raw,cap_net_admin=eip"
        ["/usr/sbin/arp-scan"]="cap_net_raw,cap_net_admin=eip"
        ["/usr/sbin/hping3"]="cap_net_raw,cap_net_admin=eip"
        ["/usr/bin/hping3"]="cap_net_raw,cap_net_admin=eip"
        ["/usr/sbin/nbtscan"]="cap_net_raw,cap_net_admin=eip"
    )

    for binary in "${!CAPS[@]}"; do
        if [[ -x "$binary" ]]; then
            sudo setcap "${CAPS[$binary]}" "$binary"
            info "  setcap OK: $binary"
        else
            warn "  not found (skip): $binary"
        fi
    done
    echo
else
    warn "macOS detected — skipping setcap (not supported). Use sudoers only."
    echo
fi

# ── 2. sudoers NOPASSWD for tools that genuinely need root ────────────────────
SUDOERS_FILE="/etc/sudoers.d/lazyown-${CURRENT_USER}"

info "Writing sudoers file: ${SUDOERS_FILE}"

# Collect paths that exist on this system
paths_for_sudo() {
    local candidates=("$@")
    local found=()
    for p in "${candidates[@]}"; do
        [[ -x "$p" ]] && found+=("$p")
    done
    # Return space-separated, empty string if none found
    echo "${found[*]:-}"
}

JOHN=$(paths_for_sudo /usr/sbin/john /usr/bin/john)
NMAP=$(paths_for_sudo /usr/bin/nmap)
MASSCAN=$(paths_for_sudo /usr/bin/masscan)
NC=$(paths_for_sudo /usr/bin/nc /bin/nc /usr/bin/ncat)
RLWRAP=$(paths_for_sudo /usr/bin/rlwrap)
RESPONDER=$(paths_for_sudo /usr/bin/responder /usr/share/responder/Responder.py)
LSOF=$(paths_for_sudo /usr/bin/lsof)
IP=$(paths_for_sudo /usr/sbin/ip /usr/bin/ip /sbin/ip)
PYTHON3=$(paths_for_sudo /usr/bin/python3)
BASH=$(paths_for_sudo /usr/bin/bash /bin/bash)
RM=$(paths_for_sudo /usr/bin/rm /bin/rm)
NANO=$(paths_for_sudo /usr/bin/nano)
KEEPASS2JOHN=$(paths_for_sudo /usr/bin/keepass2john /usr/sbin/keepass2john)

# Build sudoers lines — only for binaries that actually exist
LINES=("# LazyOwn MCP — generated by skills/setup.sh")
LINES+=("# Remove this file to revert: sudo rm ${SUDOERS_FILE}")
LINES+=("")
LINES+=("# Allow password-less sudo for pentest tools that cannot use setcap")
LINES+=("# Format: user ALL=(ALL) NOPASSWD: /path/to/binary")

add_nopasswd() {
    local label="$1"; shift
    local bins=("$@")
    for b in "${bins[@]}"; do
        [[ -n "$b" ]] && LINES+=("${CURRENT_USER} ALL=(ALL) NOPASSWD: ${b}")
    done
}

add_nopasswd "john"           $JOHN
add_nopasswd "nmap"           $NMAP
add_nopasswd "masscan"        $MASSCAN
add_nopasswd "nc"             $NC
add_nopasswd "rlwrap"         $RLWRAP
add_nopasswd "responder"      $RESPONDER
add_nopasswd "lsof"           $LSOF
add_nopasswd "ip"             $IP
add_nopasswd "python3"        $PYTHON3
add_nopasswd "bash"           $BASH
add_nopasswd "rm"             $RM
add_nopasswd "nano"           $NANO
add_nopasswd "keepass2john"   $KEEPASS2JOHN

# Write to a temp file and validate with visudo before installing
TMPFILE="$(mktemp)"
printf '%s\n' "${LINES[@]}" > "$TMPFILE"

if sudo visudo -c -f "$TMPFILE" >/dev/null 2>&1; then
    sudo cp "$TMPFILE" "$SUDOERS_FILE"
    sudo chmod 440 "$SUDOERS_FILE"
    info "sudoers file installed and validated."
else
    warn "visudo validation failed — sudoers file NOT installed."
    warn "Check $TMPFILE manually."
fi
rm -f "$TMPFILE"
echo

# ── 3. Verify ─────────────────────────────────────────────────────────────────
info "Verification:"
echo
echo "  Capabilities:"
for binary in /usr/bin/nmap /usr/bin/masscan /usr/bin/tcpdump /usr/sbin/arp-scan; do
    if [[ -x "$binary" ]]; then
        caps="$(getcap "$binary" 2>/dev/null || echo 'none')"
        printf "    %-30s %s\n" "$binary" "$caps"
    fi
done

echo
echo "  Sudoers entries:"
sudo grep "^${CURRENT_USER}" "${SUDOERS_FILE}" 2>/dev/null | sed 's/^/    /' || warn "No entries found."

echo
info "Setup complete. Restart Claude Code (or run 'claude mcp restart lazyown') to apply."
echo
warn "To undo everything:"
echo "    sudo rm /etc/sudoers.d/lazyown-${CURRENT_USER}"
echo "    sudo setcap -r /usr/bin/nmap /usr/bin/masscan /usr/bin/tcpdump"
echo
