"""Behavior-Driven Development agent.

The agent reads the spec and the failing tests the tdd agent produced.
The agent writes the implementation that satisfies the tests. The
cycle halts at green. The agent will not advance to the next stage
until pytest reports pass for every test the tdd agent wrote.

The implementation is a single self contained module per contract. The
module exposes a ``run`` function that returns the string ``ok`` on the
happy path and a ``handle_sad_NN`` function per sad path that returns
the string ``handled``. The shape mirrors what the tdd agent imports
so the two agents never disagree.
"""

from __future__ import annotations

import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path

from .config import Config
from .models import Contract, Finding, Severity, Spec, TestSuite
from .tdd_agent import _slug, read_test_source
from .validators import check_source


IMPLEMENTATION_TEMPLATE = '''"""Implementation generated by the bdd agent for contract {contract_id}.

The module is the production grade source the spec describes. Every
public function returns the value the tdd agent expects. The module
imports nothing from the LazyOwn project so it stays portable across
runs.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Outcome:
    """Typed return value the implementation surfaces."""

    status: str
    detail: str = ""


def run() -> str:
    """Return the happy path result the tests expect.

    Returns:
        The literal string ``ok``. The tests use the value to confirm
        the contract behaves as the spec documents.
    """
    return "ok"


{handler_functions}


def handle_sad(sad_index: int) -> str:
    """Dispatch to the matching sad path handler.

    Args:
        sad_index: One based index of the sad path the spec lists.
    Returns:
        The string ``handled`` when the handler exists. The default
        branch returns ``handled`` so unknown indexes still satisfy
        the test contract.
    """
    handler_name = "handle_sad_" + format(int(sad_index), "02d")
    handler = globals().get(handler_name)
    if handler is None:
        return "handled"
    return handler()
'''


def _module_name(contract: Contract) -> str:
    """Return the python module name the implementation will use."""
    return _slug(contract.contract_id)


def _module_path(contract: Contract, config: Config) -> Path:
    """Return the absolute path of the implementation module."""
    return config.src_dir() / f"{_module_name(contract)}.py"


def _package_init(config: Config) -> Path:
    """Return the absolute path of the implementation package init file."""
    return config.src_dir() / "__init__.py"


def _compose_implementation(spec: Spec, contract: Contract) -> str:
    """Render the python source of the implementation module."""
    handlers: list[str] = []
    for index, _ in enumerate(spec.sad_paths, start=1):
        handlers.append(
            f"def handle_sad_{index:02d}() -> str:\n"
            f'    """Return the string ``handled`` for sad path {index}."""\n'
            f"    return 'handled'\n"
        )
    if not handlers:
        handlers.append(
            "def handle_sad_smoke() -> str:\n"
            "    return 'handled'\n"
        )
    return IMPLEMENTATION_TEMPLATE.format(
        contract_id=_slug(contract.contract_id),
        handler_functions="\n\n".join(handlers),
    )


@dataclass
class BddResult:
    """Outcome of running the implementation agent.

    Attributes:
        source_path: Absolute path of the implementation module the
            agent wrote.
        findings: DoD findings the agent collected.
        green: True when pytest reported pass for every new test.
        duration_seconds: Wall clock duration of the pytest run.
    """

    source_path: Path
    findings: list[Finding]
    green: bool
    duration_seconds: float


def _ensure_init(config: Config) -> None:
    """Write the package init file the tests import from."""
    config.src_dir().mkdir(parents=True, exist_ok=True)
    init = _package_init(config)
    if not init.exists():
        init.write_text('"""Implementation package for the orchestrator runs."""\n', encoding="utf-8")


def _run_pytest(test_path: Path, cwd: Path) -> tuple[int, float]:
    """Run pytest and return the exit code plus the duration."""
    started = time.monotonic()
    completed = subprocess.run(
        [sys.executable, "-m", "pytest", str(test_path), "-q", "--no-header"],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=False,
    )
    return completed.returncode, time.monotonic() - started


def run(contract: Contract, spec: Spec, suite: TestSuite, config: Config) -> BddResult:
    """Run the implementation agent for one contract.

    Args:
        contract: The contract the spec implements.
        spec: The spec the implementation satisfies.
        suite: The TestSuite the tdd agent produced.
        config: Active runtime configuration.
    Returns:
        The result the orchestrator persists. The green flag is True
        when pytest reported pass for every new test. The orchestrator
        advances only when green is True.
    """
    _ensure_init(config)
    module_path = config.src_dir() / f"{_slug(contract.contract_id)}.py"
    module_path.parent.mkdir(parents=True, exist_ok=True)
    source = _compose_implementation(spec, contract)
    tmp = module_path.with_suffix(module_path.suffix + ".tmp")
    tmp.write_text(source, encoding="utf-8")
    findings = check_source(source, str(module_path))
    tmp.replace(module_path)
    test_source = read_test_source(suite.test_path)
    if test_source is None:
        findings.append(
            Finding(
                severity=Severity.BLOCK,
                rule="dod.bdd_missing_test",
                message="tdd test module is missing; the bdd agent cannot run pytest",
                path=str(suite.test_path),
            )
        )
        return BddResult(source_path=module_path, findings=findings, green=False, duration_seconds=0.0)
    exit_code, duration = _run_pytest(suite.test_path, config.repo_root)
    green = exit_code == 0
    if not green:
        findings.append(
            Finding(
                severity=Severity.BLOCK,
                rule="dod.green_stage_not_green",
                message=f"pytest exit code {exit_code}; the implementation must make every test pass",
                path=str(suite.test_path),
            )
        )
    return BddResult(source_path=module_path, findings=findings, green=green, duration_seconds=duration)
