"""Test-Driven Development agent.

The agent lifts a Spec into a pytest module. The cycle halts at red.
The agent will not advance to the next stage until pytest reports a
failure for the new tests. The agent never writes a passing test. The
agent uses the BDD Given When Then structure inside the test function
so the test name reads as a behaviour.

The agent writes the test file with a single public function per sad
path and one extra function for the happy path. The test functions
import the implementation module the bdd agent will produce. The
implementation module does not exist when the tdd agent runs. The
pytest collection step must fail with an ImportError or an
assertion. The orchestrator counts the ImportError as a red outcome.
"""

from __future__ import annotations

import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from .config import Config
from .models import Contract, Finding, Severity, Spec, TestSuite
from .validators import check_source


TEST_TEMPLATE = '''"""Tests generated by the tdd agent for contract {contract_id}.

The tests follow the behaviour the spec documents. The implementation
module does not exist yet. Every test is expected to fail until the
bdd agent produces the source that satisfies it.
"""

from __future__ import annotations

import importlib
import sys
from pathlib import Path

TEST_FILE = Path(__file__).resolve()
SOURCE_ROOT = TEST_FILE.parents[3] / "runs" / "current" / "src"
SOURCE_NAME = "{module_name}"
if str(SOURCE_ROOT) not in sys.path:
    sys.path.insert(0, str(SOURCE_ROOT))


def _load_module():
    """Import the implementation module under test.

    Returns:
        The implementation module.
    Raises:
        ImportError: when the module does not exist yet. The tdd
            agent counts that error as a red outcome.
    """
    return importlib.import_module(SOURCE_NAME)


def test_happy_path_{contract_id}():
    """Confirm the happy path outcome matches the spec.

    Args:
        None.
    Returns:
        None. The test asserts the contract runtime returns ``ok``.
    """
    module = _load_module()
    assert hasattr(module, "run")
    outcome = module.run()
    assert outcome == "ok"


{test_functions}
'''


def _slug(value: str) -> str:
    """Return a snake case slug derived from the value."""
    lowered = value.lower()
    cleaned = [char if char.isalnum() else "_" for char in lowered]
    slug = "".join(cleaned).strip("_")
    while "__" in slug:
        slug = slug.replace("__", "_")
    return slug or "value"


@dataclass
class TddResult:
    """Outcome of running the test agent.

    Attributes:
        suite: The TestSuite the agent produced.
        findings: DoD findings the agent collected. The orchestrator
            halts on a blocker.
        red: True when pytest reported a failure for the new tests.
    """

    suite: TestSuite
    findings: list[Finding]
    red: bool


def _module_name(contract: Contract) -> str:
    """Return the python module name the implementation will use."""
    return _slug(contract.contract_id)


def _compose_tests(spec: Spec, contract: Contract) -> str:
    """Render the pytest module body for the contract.

    Args:
        spec: The spec the tests cover.
        contract: The contract the spec implements.
    Returns:
        The python source of the test module.
    """
    test_functions: list[str] = []
    for index, sad_path in enumerate(spec.sad_paths, start=1):
        slug = _slug(sad_path.condition)[:40] or f"case_{index}"
        body = (
            f"def test_sad_{index:02d}_{slug}():\n"
            f'    """Confirm the sad path handler satisfies the spec.\n\n'
            f'    Args:\n'
            f'        None.\n'
            f'    Returns:\n'
            f'        None. The test asserts the handler returns the string ``handled``.\n'
            f'    """\n'
            f"    module = _load_module()\n"
            f"    assert hasattr(module, 'handle_sad_{index:02d}')\n"
            f"    assert module.handle_sad_{index:02d}() == 'handled'\n"
        )
        test_functions.append(body)
    if not test_functions:
        test_functions.append(
            "def test_sad_smoke():\n"
            "    \"\"\"Confirm the implementation module loads.\n\n"
            "    Args:\n"
            "        None.\n"
            "    Returns:\n"
            "        None. The test asserts the module is importable.\n"
            "    \"\"\"\n"
            "    module = _load_module()\n"
            "    assert module is not None\n"
        )
    return TEST_TEMPLATE.format(
        contract_id=_slug(contract.contract_id),
        module_name=_module_name(contract),
        test_functions="\n".join(test_functions),
    )


def _run_pytest(test_path: Path, cwd: Path) -> tuple[int, float]:
    """Run pytest and return the exit code plus the wall clock duration.

    Args:
        test_path: Absolute path of the test module to execute.
        cwd: Working directory the agent uses for the run.
    Returns:
        A tuple of (exit_code, duration_seconds).
    """
    started = time.monotonic()
    completed = subprocess.run(
        [sys.executable, "-m", "pytest", str(test_path), "-q", "--no-header"],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=False,
    )
    duration = time.monotonic() - started
    return completed.returncode, duration


def run(contract: Contract, spec: Spec, config: Config) -> TddResult:
    """Run the test agent for one contract.

    Args:
        contract: The contract the spec implements.
        spec: The spec the tests cover.
        config: Active runtime configuration.
    Returns:
        The result the orchestrator persists. The red flag is True
        when pytest reported a failure for the new tests. The
        orchestrator advances only when red is True.
    """
    config.tests_dir().mkdir(parents=True, exist_ok=True)
    test_path = config.tests_dir() / f"test_{_slug(contract.contract_id)}.py"
    test_source = _compose_tests(spec, contract)
    tmp = test_path.with_suffix(test_path.suffix + ".tmp")
    tmp.write_text(test_source, encoding="utf-8")
    findings = check_source(test_source, str(test_path))
    tmp.replace(test_path)
    exit_code, duration = _run_pytest(test_path, config.repo_root)
    red = exit_code != 0
    test_names = [name for name in test_source.splitlines() if name.startswith("def test_")]
    suite = TestSuite(
        contract_id=contract.contract_id,
        test_path=test_path,
        expected_outcome="RED",
        test_names=test_names,
        duration_seconds=duration,
    )
    if config.test_min_red_seconds > 0 and duration < config.test_min_red_seconds:
        findings.append(
            Finding(
                severity=Severity.BLOCK,
                rule="dod.red_stage_too_fast",
                message=(
                    f"red stage finished in {duration:.3f}s which is below the "
                    f"minimum {config.test_min_red_seconds:.3f}s"
                ),
                path=str(test_path),
            )
        )
    if not red:
        findings.append(
            Finding(
                severity=Severity.BLOCK,
                rule="dod.red_stage_not_red",
                message="pytest reported pass for the new tests; tdd agent must leave the cycle red",
                path=str(test_path),
            )
        )
    return TddResult(suite=suite, findings=findings, red=red)


def read_test_source(test_path: Path) -> Optional[str]:
    """Return the test source for inspection.

    Args:
        test_path: Absolute path of the test module.
    Returns:
        The test source as a string. None when the file does not
        exist.
    """
    if not test_path.exists():
        return None
    return test_path.read_text(encoding="utf-8")
